### ISSUE TITLE
problem with redial

### ISSUE THREAD

**Issue by mpasokolov** [gregberge/loadable-components#1000]
Hello everyone, I used react-loadable in a project before and everything worked well. I decided to switch to your library, but a problem appeared.

I'm using redial to load data. This stopped working on loadable components

```
....
import { provideHooks } from 'redial';
....

@provideHooks({
  fetch: async ({ store: { dispatch, getState } }) => {
    return Promise.all(some promise);
  }
})
export default class Home extends Component {
  render() {
    return <Component />;
  }
}

```

And next - preload on server

```
      await trigger('inject', components, triggerLocals);
      await trigger('fetch', components, triggerLocals);
```
trigger() does not return promises from provideHooks decorator

**Comment by mpasokolov** [comment]
and second problem - on server side i got error

![Uploading Снимок экрана 2024-02-23 в 11.23.22.png…]()

**Comment by theKashey** [comment]
I dont see any reason for loadable to be affected by redial, as well as I don't see any code to play with and the issue template to be properly filled.
If you want to get your issue to be solved, invest a little of your time.
