### ISSUE TITLE
Duplicate app when hydrate

### ISSUE THREAD

**Issue by AdminRoulette** [gregberge/loadable-components#1012]
I get several copies of a React application and after navigate() it triggers the error _Failed to execute 'removeChild' on 'Node'_

![Безымянный](https://github.com/user-attachments/assets/93221799-c4ec-43b3-a111-3a3f5087b719)

//server
```
const jsx = extractor.collectChunks(
        <React.StrictMode>
            <MyContextProvider ssr_data={data}>
                <StaticRouterProvider
                    key="router"
                    hydrate={false}
                    router={router}
                    context={context}/>
            </MyContextProvider>
        </React.StrictMode>
    )
    const html = ReactDOMServer.renderToString(jsx)

    let indexHTML = fs.readFileSync(path.resolve(__dirname, '../build/index.html'), {
        encoding: 'utf8',
    });
    indexHTML = indexHTML.replace('<div id="root"></div>', `<div id="root">${html}</div>`)
        .replace('<script/>', extractor.getScriptTags().toString())
        .replace('<styles/>', extractor.getStyleTags().toString())

    res.send(indexHTML);
```
//client 
```
loadableReady(() => {
    const container = document.getElementById('root');
    hydrateRoot(container,
        <React.StrictMode>
            <MyContextProvider>
                <RouterProvider key="router" router={routes}/>
            </MyContextProvider>
        </React.StrictMode>
    )
})
```

//routes
```
let Main= loadable(() => import(/* webpackChunkName: "Main" */'@/pages/Main/Main'));
export const publicRoutes = [
    {
        path: `/main`,
        Component: Main
    }
]
```

_if I use the default import the error disappears_

I saw a similar problem but it didn't help me [issues#707](https://github.com/gregberge/loadable-components/issues/707)

**Comment by theKashey** [comment]
This is what could happen in case of hydration mismatch. However it should not happen with React 18+

> Failed to execute 'removeChild' on 'Node'

This error can happen when react wants to update DOM that is not matching it's expectations. This might be caused by direct DOM manipulation (Google Translate can do it), or due to hydration mismatch.

----

Would the same problem occur if you import `pages/Main/Main` statically? It is specific and caused by loadable, or it's just there for any other reason.

**Comment by AdminRoulette** [comment]
It was a hard night =) Debugging at 5 am is not a good idea
**I thought loadableReady do 2 renders**
```
console.log("outside")
loadableReady(() => {
    console.log("inside")
```
But I checked and understand that the entry point is called 2 times

Webpack add to index.html script with main.js and extractor add it when ssr 😭
```
extractor.getScriptTags().toString()
extractor.getStyleTags().toString()
```

**This is my mistake, sorry for this post**

**Comment by theKashey** [comment]
No worries
