### ISSUE TITLE
"cannot find main in stats"

### ISSUE THREAD

**Issue by sinwailam193** [gregberge/loadable-components#178]
I'm getting a "cannot find main in stats" issue. I would like to have more info as to what this error is about. I follow the sever side rendering guide and my current code set up is this
```
    const statsFile = path.resolve("./build/server/loadable-stats.json");
    const extractor = new ChunkExtractor({ statsFile });

    // Declare our React application.
    const app = extractor.collectChunks(
        <JssProvider registry={sheetsRegistry} jss={jss} generateClassName={generateClassName()}>
            <MuiThemeProvider theme={theme} sheetsManager={new Map()}>
                <Provider store={store}>
                    <StaticRouter location={request.url} context={reactRouterContext}>
                        <Application />
                    </StaticRouter>
                </Provider>
            </MuiThemeProvider>
        </JssProvider>
    );
    const appString = renderToString(app);
    const scriptTags = extractor.getScriptTags(); // or extractor.getScriptElements();
    console.log(scriptTags);
```
This is the error screenshot
![image](https://user-images.githubusercontent.com/8454621/49693082-a58ef400-fb1e-11e8-9773-733a3d93a14a.png)

**Comment by neoziro** [comment]
I love happy ends 😁

**Comment by yyynnn** [comment]
But my suffering persist. What are entrypoints should render? Name of entry in webpack config? or what

**Comment by bramvdpluijm** [comment]
Not sure if this is the right thread to ask my question, but gonna give it a try anyway:

It looks like my @loadable/webpack-plugin sometimes skips chunks. On the server side I need the ChunkExtractor({ entrypoints: ["server"] }. When I run a build the server.js chunk does not exist inside the loadable-stats.json.

That said, I tried a few things:
- remove the entrypoints option from the chunkExtractor (this caused the server.js file to appear in loadable-stats.json once)
- ran 5 builds with the exact same configuration (this also caused the server.js file to appear in loadable-stats.json once or twice but very randomly)

What I think might be wrong:
- Async issue? Webpack is not done doing it's magic before @loadable/webpack-plugin kick in ?

Any help is appreciated

**Comment by neoziro** [comment]
@bramvdpluijm you should provide a complete repository example and open a new issue.

**Comment by kelly-tock** [comment]
i'm a bit confused as well, is this the entry point for your server code, or the client code?

**Comment by nikhilgoswami** [comment]
Invariant Violation: loadable: cannot find main in stats
 What does it mean and what changes I have to do here
