### ISSUE TITLE
Webassembly loading ?

### ISSUE THREAD

**Issue by revskill10** [gregberge/loadable-components#249]
## 💬 Questions and Help

Could i use `loadable` to lazy load Webassembly ?

**Comment by neoziro** [comment]
Hello @revskill10, I suppose that it should work, did you try it?

**Comment by revskill10** [comment]
@neoziro I tried it but failed :( A minimal example is useful in this case, i think.

**Comment by neoziro** [comment]
I don't have time to make it right now, maybe someone could help to make this example?

**Comment by theKashey** [comment]
It's more about - `loadable` is created to load `React` component, not `webassembly`. Probably you are looking for `import`.

**Comment by revskill10** [comment]
@theKashey loadable/component could load library, too, not just react component.
Just using `import` even not work.
I have to manually use `fetch('/path/to/wasm').then(working with WebAssembly)` :(

**Comment by theKashey** [comment]
You may use `fetch` instead of `import`. It shall eat anything promise-based.
