### ISSUE TITLE
Document `clearModuleCache` when running in development vs. production mode

### ISSUE THREAD

**Issue by parties** [gregberge/loadable-components#307]
## 💬 Questions and Help

I am working on integrating Loadable into an existing codebase, and we were running load/performance tests locally and found that the Loadable build was much slower; this was until we realized the significant difference when running in `development` vs. `production` modes (duh).

It is all due to this line of code in [`util.js`](https://github.com/smooth-code/loadable-components/blob/948165d5de52086b40a64694c9f300eaf158570e/packages/server/src/util.js#L5):

```js
export const smartRequire = modulePath => {
  if (process.env.NODE_ENV !== 'production') {
    clearModuleCache(modulePath)
  }
// ...
```

Of course, we shouldn't have been running performance tests in development mode, however I would expect to see this documented _somewhere_ and I wasn't able to find anything mentioning it specifically.

Thoughts?

**Comment by theKashey** [comment]
During development, with hot module replacement in place, this file might change. And it is causing a real performance degradation?

**Comment by neoziro** [comment]
Hello @parties, I think I am gonna remove this method, it is confusing for user. The best is to use a webpack plugin for that: https://github.com/smooth-code/smooth.js/blob/master/packages/smooth/src/webpack/plugins/smooth-cache-hot-reloader.js.

I think the strategy is better and less invasive for the user. What do you think?
