### ISSUE TITLE
Support SRI on webpack-plugin

### ISSUE THREAD

**Issue by yayoc** [gregberge/loadable-components#344]
## 🚀 Feature Proposal

Putting an integrity string for [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) into `loadable-stats.json` when building bundles.

## Motivation

To embed `integrity` attribute for each script tag when running SSR application with loadable components, I need to read the file and compute the integrity value on runtime. 
Instead of that, I would like to compute the integrity value at the building phase to reduce overhead on runtime.

## Example

Putting integrity value into `loadable-stats.json` 

```json
{
      "name": "xxx-e63d1f6f130186a006da.js",
      "size": 782370,
      "integrity": "sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC", 
      "chunks": [],
      "chunkNames": [],
      "emitted": false
},
```

Then it could be great if we can access the value on [attrFn for getScriptTags](https://www.smooth-code.com/open-source/loadable-components/docs/api-loadable-server/#chunkextractorgetscripttags)

**Comment by neoziro** [comment]
Hello @yayoc, actually `loadable-stats.json` is just webpack stats, do you know if webpack plans to include it? I do not want to generate it, it is webpack business. If it is available, we would get it for free in SVGR for every script!

**Comment by yayoc** [comment]
@neoziro 
I am not sure if webpack has a plan. Currently, I only know [this plugin](https://www.npmjs.com/package/webpack-subresource-integrity) to generate integrity. 
Do you think if `loadable webpack plugin` can integrate with `webpack-subresource-integrity`?

**Comment by neoziro** [comment]
@yayoc I think it is a great addition! We could add an option and load the plugin on demand if the user needs it. Like an optionalPeerDependency (even if it does not exist) what do you think? We could also make it as default but I don't know if integrity is really useful for your own resources (not pointed on a CDN)?

**Comment by yayoc** [comment]
I agree with loading the plugin as optional for the first step since integrity seems not so high demand. 
@neoziro

**Comment by peeter-tomberg** [comment]
Has there been any progress regarding this?

**Comment by neoziro** [comment]
Hello @peeter-tomberg, no progress. You are welcome to work on it!
