### ISSUE TITLE
Hydration can be incorrect if same component rendered on page in both ssr and non-ssr mode

### ISSUE THREAD

**Issue by jdb8** [gregberge/loadable-components#345]
## 🐛 Bug Report

In a scenario where the same component is made async via loadable, where one copy uses `ssr: true` and another uses `ssr: false`, the client-side hydration of the `ssr: false` component can, in some cases, be incorrect.

### Likely explanation

It seems like this occurs because the existence of the `ssr: true` copy of the component forces the chunk containing the component itself to be included on the page, which is expected. But then, when React tries to hydrate the `ssr: false` copy, the server and client render differently (the server renders the fallback state, while the client attempts to render the actual component - since it's already on the page thanks to the `ssr: true` copy above).

If the `ssr: true` copy was not on the page at all, the first render of the `loadable` component would be the fallback, and then React would be happy and the real client-side followup render would take place as expected with no mismatch.

## To Reproduce

* Create a simple component such as `const A = () => <span className="my-cool-class">A</span>`. Save this as e.g. `letters/A.js`.
* In another file, import this component dynamically using loadable, once using `ssr: false` and once using `ssr: true`, and use both these components in the app. Crucially, **use a fallback with the same DOM tag as the actual component** (in this example, `<span>`): 
```js
const AClient = loadable(() => import('./letters/A'), {
  ssr: false,
  fallback: <span className="loading-state">Loading...</span>,
})
const AServer = loadable(() => import('./letters/A'), {
  ssr: true,
  fallback: <span className="loading-state">Loading...</span>,
})

const App = () => (
  <div>
    <br />
    <AClient />
    <br />
    <AServer />
  </div>
)

export default App
```
* Render the App using the settings used in the [ssr example in the repo](https://github.com/smooth-code/loadable-components/tree/62adb11cc54e012011c01e492bc4d92a8ef0dd65/examples/server-side-rendering)

The resulting DOM contains the wrong class (`loading-state`) for the client-side-rendered component:

![image](https://user-images.githubusercontent.com/643295/58050388-1261dd80-7b04-11e9-9e1e-d12b0bbee20c.png)

There's also a React development warning in the console: `Warning: Prop `className` did not match. Server: "loading-state" Client: "my-cool-class"`.

## Expected behavior

The app should render using SSR, with `AClient` falling back to the loading state before being fully rendered on the client, while `AServer` renders on the server first and simply rehydrates on the client.

The DOM should look like:

![image](https://user-images.githubusercontent.com/643295/58050320-e34b6c00-7b03-11e9-9dce-52c088108119.png)

## Link to repl or repo (highly encouraged)

I added a repro in the updated example as part of my PR (#346). https://github.com/jdb8/loadable-components/blob/fef7aa8a934d548efe730e255b71be23f58aad10/examples/server-side-rendering/src/client/App.js#L15

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

(Ran this on a cloned copy of this repo, in the SSR example folder).

Paste the results here:

```bash
## System:
 - OS: macOS 10.14
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 1.03 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by jdb8** [comment]
Ok, so shortly after posting this we found the line that seems to be causing this. It's this one: https://github.com/smooth-code/loadable-components/blob/62adb11cc54e012011c01e492bc4d92a8ef0dd65/packages/component/src/createLoadable.js#L83

From what I understand, it seems like this was added to deliberately avoid a full re-render in `componentDidMount` if the module is already available: but this is exactly what's causing this bug, since skipping straight to the 'real' render (rather than always rendering the fallback and then the rendering for real in cDM) is what's causing the SSR mismatch.

It seems like to make this more correct, we'd want to only execute this `loadSync` call if `options.ssr` is `true`, since when it's not, we can't rely on the markup matching properly.

Making the change in my node_modules to add that `options.ssr &&` condition to that line does indeed seem to fix the issue. I can make a PR if this seems like a good solution? All tests pass, but it seems like there aren't any integration tests that would necessarily catch this kind of edgecase with SSR (I can definitely add an example to the SSR example though).

**Comment by neoziro** [comment]
Hello @jdb8, I think you are right, we are missing something here. If ssr is false, it makes sense to always display the loading. We are missing some integration test yes, maybe it is time to add it.

I will come back on this, I have to deep dive in your issue to be sure that your solution is the correct one. Anyway there is a bug, so you can submit a PR and implement some test if you have time. It will be required for any solution we choose.
