### ISSUE TITLE
"loadable: cannot find x in stats" with dynamic import and loadable.lib

### ISSUE THREAD

**Issue by bitttttten** [gregberge/loadable-components#382]
## 🐛 Bug Report

When using `loadable.lib`, I get this error:

> loadable: cannot find data-index-nl-md in stats
    at invariant (/node_modules/@loadable/component/dist/loadable.cjs.js:17:15)

I am using loadable.lib since I need the default and named exports from a md file.

## To Reproduce

```js
const Loader = loadable.lib(props => {
    return import(`./data/index.${props.lang}.md`)
})
```

```js
        <Loader lang={lang}>
            {({
                frontMatter,
                default: Main,
            }) => (
                <StaticPageTemplate
                    title={frontMatter.title}
                    heading={frontMatter.heading}
                    main={() => <Main lang={lang} />}
                />
            )}
        </Loader>
```

## Expected behavior

For there not to be an error.

## Link to repl or repo (highly encouraged)

In my output I see:

```js
var Loader=_loadable_component__WEBPACK_IMPORTED_MODULE_1___default.a.lib({
  chunkName:function chunkName(props){return"data-index-".concat(props.lang,"-md").replace(/[^a-zA-Z0-9_!§$()=\-^°]+/g,"-");},
 /* ... */
});
```

and in loadable stats I see:

```json
  "assetsByChunkName": {
    /* .. */
    "data-index-index-en-md-md": "data-index-index-en-md-md.js",
    "data-index-index-nl-md-md": "data-index-index-nl-md-md.js",
    /* .. */
   },
```

So it seems index and md are duplicated?

```bash
## System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 628.05 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.2/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: ^5.7.2 => 5.7.2 
 - @loadable/component: ^5.10.1 => 5.10.1 
 - @loadable/server: ^5.9.0 => 5.9.0 
```

**Comment by bertho-zero** [comment]
I have the same error. The difference is that I have a correct chunkName, but this chunkName is not in a group of the same name. In my opinion it can be ChunkExtractor's getChunkGroup method that does not work well.

https://github.com/smooth-code/loadable-components/blob/2c6bc5156d038a3018330c9c0275adfa07cf47c8/packages/server/src/ChunkExtractor.js#L188-L192

**Comment by Bonjur** [comment]
`"cannot find data-index-nl-md in stats" `
Rename this file without **-** , and try.

**Comment by Bonjur** [comment]
another trick, don't load component before dom finished
