### ISSUE TITLE
Getting warning: Did not expect server HTML to contain a <div> in <div>

### ISSUE THREAD

**Issue by adambisek** [gregberge/loadable-components#423]
Hello there,
thank you for this remarkable library :)

I am using this library with razzle@3.0.0 (React 16.9.0) and I've successfully done all four steps from this guide: https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering/#guide

But, `in dev mode`, I am still getting this warning `Warning: Did not expect server HTML to contain a <div> in <div>.` in browser console (production build seems to be ok, but there might be supressed warning). So SSR HTML does not match HTML 
hydrated on client side.

After isolation of this this issue, the cause is this code: `const Home = loadable(() => import('./Home'))`

Could you give me some hints how to solve it please?

Thank you! 🙏

**Comment by theKashey** [comment]
```
console.log(document.body.innerHTML);
ReactDOM.hydrate();
console.log(document.body.innerHTML);
```
Then - try to find the difference. Plus double check `__LOADABLE_REQUIRED_CHUNKS__` element - it shall be non empty.

**Comment by adambisek** [comment]
Thanks for advice!
The difference makes this space in JSX`{' '}`, which on server is rendered like `<!-- -->`

Full diff between server and client: https://prnt.sc/p12991

I am wondering what could make the difference 😱

**Comment by adambisek** [comment]
WITHOUT code splitting it works without warnings (HTMLs are same):

```
import React from 'react';
import { Route, Switch } from 'react-router-dom'
import loadable from '@loadable/component'
import About from './About';
import './App.css';

//const About = loadable(() => import('./About'))

const App = () => (
  <Switch>
    <Route exact path="/about" component={About} />
  </Switch>
)
```

```
console.log(document.body.innerHTML);

            <div id="root"><div class="Home"><div class="Home-header"><img src="http://localhost:3001/static/media/react.9a28da9f.svg" class="Home-logo" alt="logo"><h2>Hello man</h2></div></div></div>
```
```
hydrate()
```
```
console.log(document.body.innerHTML);

            <div id="root"><div class="Home"><div class="Home-header"><img src="http://localhost:3001/static/media/react.9a28da9f.svg" class="Home-logo" alt="logo"><h2>Hello man</h2></div></div></div>
```

--------------------------------------------------------------------------------

WITH code splitting it works with warnings (but HTMLs are 100% same):

```
import React from 'react';
import { Route, Switch } from 'react-router-dom'
import loadable from '@loadable/component'
//import About from './About';
import './App.css';

const About = loadable(() => import('./About'))

const App = () => (
  <Switch>
    <Route exact path="/about" component={About} />
  </Switch>
)
```

```
console.log(document.body.innerHTML);

            <div id="root"><div class="Home"><div class="Home-header"><img src="http://localhost:3001/static/media/react.9a28da9f.svg" class="Home-logo" alt="logo"><h2>Hello man</h2></div></div></div>
 ```

```
hydrate()
index.js:1 Warning: Did not expect server HTML to contain a <div> in <div>. 
    in Unknown
console.<computed> @ index.js:1
r @ backend.js:1
warningWithoutStack @ react-dom.development.js:545
warnForDeletedHydratableElement @ react-dom.development.js:9444
didNotHydrateContainerInstance @ react-dom.development.js:10278
deleteHydratableInstance @ react-dom.development.js:16363
popHydrationState @ react-dom.development.js:16637
completeWork @ react-dom.development.js:19035
completeUnitOfWork @ react-dom.development.js:22244
performUnitOfWork @ react-dom.development.js:22218
workLoopSync @ react-dom.development.js:22185
renderRoot @ react-dom.development.js:21878
scheduleUpdateOnFiber @ react-dom.development.js:21419
scheduleRootUpdate @ react-dom.development.js:24319
updateContainerAtExpirationTime @ react-dom.development.js:24347
updateContainer @ react-dom.development.js:24436
(anonymous) @ react-dom.development.js:24963
unbatchedUpdates @ react-dom.development.js:21687
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24962
hydrate @ react-dom.development.js:25029
./src/client.js.window.hydrate @ client.js:13
(anonymous) @ VM600:1
```

```
console.log(document.body.innerHTML);
            <div id="root"><div class="Home"><div class="Home-header"><img src="http://localhost:3001/static/media/react.9a28da9f.svg" class="Home-logo" alt="logo"><h2>Hello man</h2></div></div></div>
```

**Comment by adambisek** [comment]
For further readers: Just figured out what's the cause 🎉 

Just define array function as variable to make shallow comparison work correctly.

THIS WORKS:
```
const a = () => import('./About')
const About = loadable(a)
```

**Comment by adambisek** [comment]
Ok, so this solution fails on build in production mode with error: SSR requires @loadable/babel, please install it

So problem described above in https://github.com/smooth-code/loadable-components/issues/423#issuecomment-527372923 persists :(

**Comment by theKashey** [comment]
Could you double-check `__LOADABLE_REQUIRED_CHUNKS__` value (in HTML), or (better) dump html as-as before and after.
"The fix", which worked for you, actually disables loadable logic.

**Comment by adambisek** [comment]
Just before another dive and checks - should loadable work in development mode?
I get this warning only in dev mode.

**Comment by neoziro** [comment]
Yes it should work in dev mode.

**Comment by fivethreeo** [comment]
Works in dev but not with hmr. Limit chunks to 1 in dev or put hot.accept in each module loaded by loadable. And use render in the  client instead of hydrate when client is hot.

**Comment by fivethreeo** [comment]
```javascript
const appRender = Component => {
  const root = document.getElementById('root');
  const renderMethod = !!module.hot ? render : hydrate;
  renderMethod(
    <Component />,
    root);
}

if (module.hot && process.env.RAZZLE_DISABLE_CODESPLIT) {
  appRender(App);
  module.hot.accept();
} else {
  // Load all components needed before rendering
  loadableReady(() => {
    appRender(App);
  });
}
```

**Comment by fuzing** [comment]
I suspect that you might be running into the same problem as me (I haven't yet found a solution).... however, it appears that when code splitting with webpack, webpack's import returns an unresolved Promise even when the imported module/chunk is already downloaded.   The promise resolves a short time later, but not until after the first react render, meaning that your loadable component will render its fallback, or null (which is likely different to what you just rendered on the server).

On the client:
`console.log(yourReactParentNode.innerHTML);`
`hydrate(........);`
`console.log(yourReactParentNode.innerHTML);`

May or may not confirm this (there's a time race, so it may NOT).   Even if webpack were to return a resolved Promise in the event that the module/chunk is already present in the browser, it's unclear whether this would solve the problem because the Promise's "then" method may not be called until some time later (JS implementation dependent).

So, for example, in chrome:
`Promise.resolve().then(() => { console.log("Resolved"); });`
`console.log("After");`
results in:
`After`
`Resolved`

**Comment by joe-schorn** [comment]
For what it's worth, I had the same problem. The reason was the babel loadable plugin wasn't added properly. We had a babelrc in the project, and I originally added it there, but babel loaders were also defined in the webpack config, which was overriding the babelrc (far from ideal). Anyway, I just had to add the loadable babel plugin to the webpack config and that resolved the issue.

**Comment by Ateiri** [comment]
Hello. I have seems like same problem.
`const AsyncIcon = loadable(({ name }: AsyncIconProps) => import(`../../static/svg/${name}.svg`), { ssr: true, fallback: <span>Loading</span> });`
- If `ssr: false` works well, SSR returns fallback, Client renders fallback and then loads chunks and display actual component.
- If `ssr: true`, SSR returns actual component, which is correct, BUT Client is still trying fetch chunks which is incorrect and of course difference that on Client displays Fallback first.

**Comment by AamirAfridi-Which** [comment]
Why is this issue closed?

**Comment by theKashey** [comment]
There was no clear issue actually. It was a "observable behavior", with too many reasons to exists.
@AamirAfridi-Which - if you have some more specific problem feel free to create another one.
