### ISSUE TITLE
CSS doesn't load when I use loadable component in Router

### ISSUE THREAD

**Issue by zverexe** [gregberge/loadable-components#439]
## 🐛 Bug Report

I want to use loadable component in Router so I wrote such a code:

```
// custom-loadable
import loadable from '@loadable/component';

export default fn => loadable(fn, { fallback: 'Loading...' });

```

```
// routes.js
const Home = loadable(() => import('./Home'));
 <Route path="/" exact render={(routeProps) => <Home {...{...routeProps, ...props}} />} />
```

but when I load the page, all css styles doesn't appear and page looks broken. What I missed in configs? I use SSR but it is a part of react-on-rails package
If I paste some code in custom-loadable, code recompile and styles appear but they don;t appear if I don't change anything in loadable component config

**Comment by theKashey** [comment]
You can't use "custom loadable" - dynamic `import` function should be placed inside the _original_ `loadable` or babel plugin would ignore it and nothing happens.

**Comment by zverexe** [comment]
What do you mean by original loadable?

**Comment by theKashey** [comment]
Ok, so using just a right name is enough to handle it. Never tried :)

**Comment by zverexe** [comment]
I use exectely the same code as in the thread but css code do not compile
