### ISSUE TITLE
Compilation issue with new babel version, namely @babel/types 7.6.3

### ISSUE THREAD

**Issue by tsareg** [gregberge/loadable-components#450]
## 🐛 Bug Report

After upgrading to recent babel version, and namely @babel/types 7.6.3 started to get compilation error:
"Number of TemplateLiteral quasis should be exactly one more than the number of expressions.
Expected 2 quasis but got 1"

Change was done here: https://github.com/babel/babel/issues/10486, https://github.com/babel/babel/pull/10492

## To Reproduce

```javascript
const AsyncIcon = loadable(props => import(`./icons/${props.name}.js`));
```

## Expected behavior

No compilation error

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 589.26 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.10.0 - /usr/local/bin/node
 - Yarn: 1.19.0 - /usr/local/bin/yarn
 - npm: 6.11.3 - /usr/local/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.10.3 => 5.10.3
 - @loadable/component: ^5.10.3 => 5.10.3
 - @loadable/server: ^5.10.3 => 5.10.3
 - @loadable/webpack-plugin: ^5.7.1 => 5.7.1
```

**Comment by tsareg** [comment]
this is still an issue

**Comment by gregberge** [comment]
Yep still an issue but it looks like there is no user interested by this fix except you @tsareg. So please submit a PR or it will be close.

**Comment by tsareg** [comment]
OK, will try
