### ISSUE TITLE
Question: "Rendering Modes" / Thunked options argument

### ISSUE THREAD

**Issue by StevenLangbroek** [gregberge/loadable-components#454]
Hey folks!

First off; awesome project! We're happily using it in production on a couple of projects and couldn't be happier with it :).

SEO is a _very_ important consideration for us, but it often conflicts with "user-facing" or "perceived" performance; i.e., the needs of our _real_ users conflict with those of crawlers sometimes. We're investigating rendering in 2 modes based on some indicators of whether a request comes from a bot or a real user: `COMPLETE` for bots, `IMMEDIATE` (defer rendering of an arbitrary subtree) for real users. Before coming up with abstractions for this, I'm looking at leveraging the tools we already use, and I had an idea that might be interesting to evaluate for `@loadable/server`. 

## Current Situation

Generally speaking, within the context of `loadble`, you make a decision whether to SSR a component where you use it:

```tsx
// MyComponent.tsx
export default MyComponent

// In another file, where it's "imported", set `ssr` to false
// in root module scope.
const MyComponent = loadable(() => import('./MyComponent'), { ssr: false });
```

While this is fine; there is 1 limitation to this: the decision whether or not to render on server is tied to module (and thus application) lifecycle. 

## Proposal

Our use-case would be connecting the decision to server-render to not the application or module lifecycle, but "other lifecycles"; in our case, that of the request, but I could imagine this opens loadable up to a whole range of other use-cases:

```tsx
// MyComponent.tsx stays the same
export default MyComponent

// where it's used:
const MyComponent = loadable(() => import('./MyComponent'), ({ req }) => ({ ssr: req.isBot });

// in your render handler:
// WARNING: I have in no way thought through the implementation here,
// it's just here for illustration
function render(req, res, next) {
	const chunkExtractor = new ChunkExtractor();

	const renderStream = renderToNodeStream(
		<ChunkExtractorManager extractor={chunkExtractor} optionsArguments={{ req }}>
			<App />
       	</ChunkExtractorManager>
	)
}
```

So the proposal would be to have a way to "thunk" the options argument. So my question is; am I missing some API that we could already use for this, and if not, what do you think about this proposal?

Would love to hear your input :).

**Comment by theKashey** [comment]
As long as `ssr:false` is literally "dont render me at server" - you can "not render" components using any other mechanic

```js
const ClientSideOnly = ({children}) => (
  <Enviroment.Consumer>{ render => render && children}</Enviroment.Consumer>
)
function render(req, res, next) {
	const chunkExtractor = new ChunkExtractor();

	const renderStream = renderToNodeStream(
		<ChunkExtractorManager extractor={chunkExtractor}>
                   <Enviroment.Provider value={req.isBot}>
			<ClientSideOnly>
                           <App /> // well, it would render nothing
			</ClientSideOnly>
                   </Enviroment.Provider>
       	</ChunkExtractorManager>
	)
}
```

**Comment by StevenLangbroek** [comment]
Yeah that's one of (many) approaches we discussed.
