### ISSUE TITLE
I believe there is a bug in webpack-plugin

### ISSUE THREAD

**Issue by badtant** [gregberge/loadable-components#459]
`const outputFolder =  this.opts.writeToDisk.filename || this.compiler.options.output.path`

shouldn't it be

`const outputFolder =  this.opts.filename || this.compiler.options.output.path`

filename prop shouldn't be under writeToDisk

**Comment by badtant** [comment]
anyone?

**Comment by theKashey** [comment]
It's working exactly as written in the documentation https://loadable-components.com/docs/api-loadable-webpack-plugin/

**Comment by gregberge** [comment]
Yes no problem here.
