### ISSUE TITLE
is it seemly doesn't work in typescript?  code spliting fail

### ISSUE THREAD

**Issue by EvalGitHub** [gregberge/loadable-components#464]
## 💬 Questions and Help

Loadable Components project is young, but please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

**Comment by theKashey** [comment]
Even with TypeScript you have to use __babel plugin__.

**Comment by theKashey** [comment]
See https://github.com/gregberge/loadable-components/issues/458 for TypeScript-only solution.
