### ISSUE TITLE
apollo client local state cannot be collected

### ISSUE THREAD

**Issue by fred8617** [gregberge/loadable-components#465]
## 🐛 Bug Report

hello,thanks for the loadable-components
when i use apollo client like this
![image](https://user-images.githubusercontent.com/35049517/69683608-63c0da00-10f0-11ea-9fb0-cf78d4b687a9.png)
![image](https://user-images.githubusercontent.com/35049517/69683614-6c191500-10f0-11ea-990f-e8ca6ef90f43.png)
and do ssr like this
![image](https://user-images.githubusercontent.com/35049517/69684216-c3b88000-10f2-11ea-89e5-12ed09eb7cb4.png)
the app will render twice (1,extractor 2.apollo)
and the state of client will be undefined like this
![image](https://user-images.githubusercontent.com/35049517/69684275-02e6d100-10f3-11ea-927e-b1f512e08bfc.png)
so i have to use option chain to avoid the undefined problem
![image](https://user-images.githubusercontent.com/35049517/69684332-4ccfb700-10f3-11ea-9180-7dde181300d9.png)
is there any solution for apollo local state?

**Comment by theKashey** [comment]
This does not seem to be related to `loadable-components`. Please refer to Appolo docs about how to get the state from SSR and properly rehydrate it on the client.
