### ISSUE TITLE
pass new props loading

### ISSUE THREAD

**Issue by maystrenkoYurii** [gregberge/loadable-components#469]
Add the ability new props loading into loadable-components for show fallback component when data fetching. And callback example <AsyncComponent loading={true} onLoadComponent={({  component, loading }) => {
} /> loading === passed props loading. onLoadComponent handled => component load or loading chenged

if (loading) {
should be displayed fallback component
}

**Comment by theKashey** [comment]
Just use `Suspense` boundaries.

**Comment by maystrenkoYurii** [comment]
@theKashey i am use ssr

**Comment by theKashey** [comment]
If you are using SSR, then there is no "loading" state possible.
Consider using a "custom" Suspense boundaries, which are Suspense on the client, and nothing on the server, like [here](https://github.com/theKashey/react-imported-component/blob/master/src/LazyBoundary.tsx).
