### ISSUE TITLE
chunkNames in Server Stats file different from Client stats file

### ISSUE THREAD

**Issue by kvnam** [gregberge/loadable-components#479]
Hello,

I have read the issues and Readme, and I've been struggling with this for a few days now. I am trying to set up loadable for a un-ejected CRA app. I'm using `Craco` to override webpack config and it seems to be working, as the client side `loadable-stats.json` is being generated. When I run the build command, the chunks are named based on `id`. So for my server config, I decided to name the chunks by `id` too. But unfortunately the chunkNames seem to be the path to the modules in the server stats file, rather than id. The actual chunks are named by 'id` though.

Due to this, when I run the `nodeExtractor (which is reading from the server stats file)` to `collectChunks` and then `webExtractor (which is using the client stats file)` to `getScriptElements` I get an empty array of loadable chunks. If I only use the `webExtractor` it throws an error that `chunkNameFromServerStatsFile not found`. 

If this is a duplicate issue I'm sorry I'll remove it, but I'm at my wits end trying to solve this.

My webpack config for the server is using the `server.js` file which contains the Express code as the entry point, whereas the webpack config for the client has the `index` file for the app as the entry. I get an empty `{}` as the server `requireEntrypoint` result. I'm not really sure what is supposed to happen here, the actual documentation is not very clear. I am following the SSR example on Github to set this up.

```
    const nodeStatsFile = path.resolve(__dirname, 'node-stats.json');
    const nodeExtractor = new ChunkExtractor({ statsFile: nodeStatsFile, entrypoints: ["server"] });
    const nodeEntryPointResult = nodeExtractor.requireEntrypoint("server");  // ==> {}
    const webStatsFile = path.resolve(__dirname, '../web-stats.json');
    const extractor = new ChunkExtractor({ statsFile: webStatsFile });
    const client = generateApolloClient();
    const app = (<ApolloProvider client={client}>
        <HelmetProvider context={helmetContext}>
          <Router location={req.url} context={staticContext}>
            <CookiesProvider cookies={req.universalCookies}>
                <App />
            </CookiesProvider>
          </Router>
        </HelmetProvider>
      </ApolloProvider>);
    getDataFromTree(app).then(() => {
      const jsx = nodeExtractor.collectChunks(app);
      const content = ReactDOMServer.renderToString(jsx);
      const state = client.extract();
      const { helmet } = helmetContext;

      const html = ReactDOMServer.renderToString(
        <Html content={content} helmet={helmet} assets={assets} extractor={extractor} />,
      );
      res.status(staticContext.status || 200);
      res.send(`<!doctype html>${html}`);
      res.end();
    })
```
In the Webpack config for both client and server I have set `chunkFilename: '[id].js',` and I can see that even on the server the actual chunk files are named by ID. the `node-stats.json` has the whole path as the chunkName though.

Any help here would be appreciated and again if this is not a valid question please let me know I'll remove it. Thanks!

```
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 632.42 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
 - Yarn: 1.16.0 - ~/.nvm/versions/node/v8.16.0/bin/yarn
 - npm: 6.13.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.10.0 => 5.11.0 
 - @loadable/component: ^5.9.0 => 5.11.0 
 - @loadable/server: ^5.9.0 => 5.11.0 
 - @loadable/webpack-plugin: ^5.7.1 => 5.7.1 
```

**Comment by theKashey** [comment]
You have to use the same `loadable-stats` generated for the client for both the server and the client.

**Comment by kvnam** [comment]
@theKashey Thanks! I'll give that a try, but just to confirm, should I be running the `@loadable/webpack-plugin` in the server Webpack build as well? If it's not being used, perhaps I'm making a mistake by including it there as well.

**Comment by kvnam** [comment]
Update: This was happening because I forgot to include the `@loadable/babel-plugin` into the Client side Webpack override, in my craco config. Closing the issue as everything works great now, thanks!
