### ISSUE TITLE
Issue with filenames of chunks

### ISSUE THREAD

**Issue by ghbakhtiari** [gregberge/loadable-components#481]
So the problem I have is with the filenames of chunks that are produced by loadable.
For example, the component that i want to lazy-load, is in a folder like this: `src/components/MyComponent/MyComponent.jsx`
Then I add an `index.js` file just besides that `jsx` file, with this content:
```js
import loadable from '@loadable/component';
const LazyMyComponent = loadable(() => import('./MyComponent'));
export default LazyMyComponent;
```
So i can use the new lazy component in other places without having to know whether or not this component is lazy or...

### The Problem(s):
The filenames that are generated for these chunks, look like this (check the webpack config below):
`MyComponent.SOME_HASH.js`
and the problem with that, is:

1. It's using the filename of my source code, which I don't want to be exposed in production. 

2. The `[name]` inside webpack config is exactly copied from the path which i passed to `loadable(() => import('THE_PATH'))` . And when I used something like `loadable(() => import('src/components/MyComponent'))`, I got `src-components-MyComponent.SOME_HASH.js` as the filename! (how can I modify this name?)

3. Because of the problem above, if I have two different components in different directories but with the same name, they are both bundled in the same file. (for example `src/components/MyComponent/MyComponent.jsx` and `src/views/SomeView/MyComponent/MyComponent.jsx` bothe have an `index.js` file beside them which exports a loadable component like: `loadable(() => import('./MyComponent'))`. As a result, i get one `MyComponent.SOME_HASH.js` which contains both components!!)

4. I can't use `[id]` instead of `[name]` for `chunkFilename` in webpack, because then my other chunks (like `vendors` and `common` and ...) will be affected by this, and I'd prefer their names to be explicit (for debugging purposes).

So, am I missing something in webpack configs or using the loadable library here? :/

### My webpack configs:

```js
// ...
  output: {
    path:  'SOME_PATH',
    filename: '[name].[contenthash:8].js',
    chunkFilename: '[name].[contenthash:8].js',
  },
// ...
  optimization: {
    runtimeChunk: 'single',
    splitChunks: {
      cacheGroups: {
        commons: {
          name: 'commons',
          chunks: 'all',
          reuseExistingChunk: true,
          minChunks: 2,
          minSize: 0,
        },
        polyfills: {
          test: /[\\/]node_modules[\\/](core-js|regenerator-runtime)[\\/]/,
          chunks: 'all',
          name: 'polyfills',
          priority: 20,
          enforce: true,
        },
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          chunks: 'all',
          name: 'vendors',
          enforce: true,
        },
      },
    },
  },
// ...
  plugins: [
    new LoadablePlugin({
      writeToDisk: {
        filename: 'SOME_PATH',
      },
    }),
// ...
  ],
// ...
```

### Expected behavior

I just want to be able to generate chunk files with names that don't expose my source's filenames and directory structure (even some numeric id for these chunks would be nice)...
Also, I'd like to be able to freely import/export loadable components without being concerned about whether or not this import name is already taken... (problem No.3 from above)

```bash
## Binaries:
 - Node: 8.11.3 - /usr/local/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.10.3 => 5.10.3 
 - @loadable/component: ^5.10.3 => 5.10.3 
 - @loadable/server: ^5.10.3 => 5.10.3 
 - @loadable/webpack-plugin: ^5.7.1 => 5.7.1 
```

**Comment by theKashey** [comment]
The `[id]` should be unique, as well as `[contenthash]` - it's a hash of a whole chunk file. `[name]`, without _magic comment_ also should be more or less unique, so I 100% sure you are importing the same `index` in your code.

In any case - please refer to `webpack` documentation, only it is responsible for the chunk creation. Loadable has no power over it.

I am personally using `[chunkhash]_[id]` could ensure you - that's working correctly.

**Comment by ghbakhtiari** [comment]
> The `[id]` should be unique, as well as `[contenthash]` - it's a hash of a whole chunk file. `[name]`, without magic comment also should be more or less unique, so I 100% sure you are importing the same index in your code.

I'm also using `contenthash` and have tested both `[name]` and `[id]`.

So to reproduce the problem, you can have two components with the same filename, but in different directories.
(in my case, `src/views/SomeView/SomeComponent/SomeComponent.jsx` and `src/shared-components/SomeComponent/SomeComponent.jsx`)

Now, if you have two separate `index.js` files besides each component's file, and import them with `@loadable/component` like `loadable(() => import( './SomeComponent'))`, and export the result and use them in separate files (anywhere in project), both of them will be bundled inside the same chunk file.
(in my case, the file name while using `[id]` is: `SOME_ID.SOME_HASH.js`. And using `[name]` is: `SomeComponent.SOME_HASH.js`)

I can see that by using webpack's _magic comments_ it's possible to change the names of one of these components and thus, generate two different bundles, but don't you think this is a hacky solution? because a developer should always be aware of the fact that whether or not there is another lazy component with the same name somewhere inside the project tree...

**Comment by theKashey** [comment]
It's more about - loadable really has no control over it. There is nothing we could do - the "problem" is on webpack's side.

However it might be not the problem - for example webpack might not generate a new chunk, reusing existing, if it's too small. Try simplifying `splitChunks` to `splitChunks: "all"`
