### ISSUE TITLE
Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`, please install it

### ISSUE THREAD

**Issue by lovewinders** [gregberge/loadable-components#484]
## my example

App.tsx
```
import React from 'react';
import {Route,Redirect,withRouter,Switch} from 'react-router-dom';
import loadable from '@loadable/component'
const Loading = () => {
	return <div>loading</div>
}

const LoadableTab = loadable(() => import('./A'), {
	fallback: Loading
});
const LoadableUser = loadable(() => import('./B'), {
	fallback: Loading
});;

class App extends React.Component{
	render(){
		return(
			<React.Fragment>
				<Switch>
					<Route path="/login"  component={LoadableTab}/>
					<Route path="/join"  component={LoadableUser}/>
					<Route path="/"  component={LoadableUser}/>
				</Switch>
				<LoadableUser />
			</React.Fragment>
			)
	}
};

export default App;
```
A.tsx
```
import React from 'react';

export default function() {
    return (
        <div>AAAAA</div>
    )
}
```
B.tsx
```
import React from 'react';

export default function() {
    return (
        <div>BBBBB</div>
    )
}
```
tsconfig.server.json

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "allowJs": true,
    "module": "commonjs",// esnext commonjs
    "alwaysStrict": true,
    "target": "esnext",
    "sourceMap": true,
    "jsx": "react",
    "jsxFactory": "React.createElement",
    "baseUrl": ".",
    "paths":{
        "app/*": ["app/*"],
        "*": ["types/*"]
    },
    "lib": [
      "es6",
      "dom"
    ],
    "noImplicitAny": false,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "typeRoots": ["Models", "typings", "node_modules/@types"]
  },
  "include": [
    "app",
    "server"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
.babelrc
```
{
  "presets": [
    [
      "@babel/preset-env",
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-object-rest-spread",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }],
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-modules-commonjs",
    "@loadable/babel-plugin",
    "@babel/plugin-transform-typescript",
    "@babel/plugin-syntax-typescript",
    [
      "import",
      {
        "libraryName": "antd",
        // "style": "css",
        "style": true
        /*"libraryDirectory": "es",
        "style": "css"*/
      }
    ],
  ]
}
```
server/index.js
```
import App from "./App.tsx";
...
const rootString = renderToString(
        chunkExtractor.collectChunks(
            <Provider store={store} context={ReactReduxContext}>
                <ConnectedRouter history={history} context={ReactReduxContext}>
                    <StaticRouter location={ctx.req.url} context={context}>
                        <App  />
                    </StaticRouter>
                </ConnectedRouter>
            </Provider>
        )
    );
...
```
package.json
``
...
"devDependencies": {
    "@babel/cli": "^7.7.5",
    "@babel/core": "^7.7.5",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@babel/plugin-proposal-decorators": "^7.7.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.7.4",
    "@babel/plugin-syntax-dynamic-import": "^7.7.4",
    "@babel/plugin-syntax-typescript": "^7.7.4",
    "@babel/plugin-transform-modules-commonjs": "^7.7.5",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/plugin-transform-typescript": "^7.7.4",
    "@babel/preset-env": "^7.7.6",
    "@babel/preset-react": "^7.7.4",
    "@babel/preset-stage-0": "^7.0.0",
    "@babel/register": "^7.7.4",
    "@loadable/babel-plugin": "^5.11.0",
    "@loadable/webpack-plugin": "^5.7.1",
    "@typescript-eslint/eslint-plugin": "^2.10.0",
    "@typescript-eslint/parser": "^2.10.0",
    ...
}`
...
scripts: {
    "start:ssr": "nodemon --exec node_modules/.bin/ts-node --project tsconfig.server.json -r tsconfig-paths/register ./build/server/index.js --inspect --watch config --watch ./build/server"
}
...
```
#### And then report an error
```
    $ npm run start:ssr // Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`, please install it
```
I read other issues and said that it is to modify the module in tsconfig.server.json: "commonjs"-> "esnext"，But does not recognize es6 import。

How should I do? Thank you

**Comment by theKashey** [comment]
I am not 100% sure how `babel-ts` works, but `"module": "commonjs",` might affect how loadable works. Try `"module": "es2015",`.

Generally speaking - `loadable` is a bit picky about imports, try adding [this magic comments](https://loadable-components.com/docs/babel-plugin/#magic-comments) to the imports.

**Comment by lovewinders** [comment]
> 我不确定100％如何`babel-ts`工作，但`"module": "commonjs",`可能会影响可加载的工作方式。尝试`"module": "es2015",`。
> 
> 一般来说，`loadable`对导入有些挑剔，请尝试在导入中添加[此魔术注释](https://loadable-components.com/docs/babel-plugin/#magic-comments)。
step1：App.tsx
const LoadableTab = loadable(/* #__LOADABLE__ */() => import('./A'), {
	fallback: Loading
});
const LoadableUser = loadable(/* #__LOADABLE__ */() => import('./B'), {
	fallback: Loading
});;
step2：.babelrc
"module": "esnext"

#### Then error
import React from 'react';
           ^^^^^

**Comment by theKashey** [comment]
Try just remove `module` completely. Refer to https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options
