### ISSUE TITLE
bag getLinkTags

### ISSUE THREAD

**Issue by maystrenkoYurii** [gregberge/loadable-components#489]
My custom vendors chunks return in link tags from getLinkTags, but mobile browsers very bad worked. After removing the links and leaving only the scripts it starts working fine
![Снимок1](https://user-images.githubusercontent.com/23016311/71326507-9c43b000-2504-11ea-9a37-fd29f553b42e.PNG)
![Снимок2](https://user-images.githubusercontent.com/23016311/71326508-9cdc4680-2504-11ea-83e8-64494a5ae740.PNG)

**Comment by theKashey** [comment]
Not sure what happened - link removal solved the problem, or you had to replace links by scripts?
`link preload` could not affect how `scripts` are executed - that's a network-level resource hint, nothing more.
