### ISSUE TITLE
Loading placeholder 

### ISSUE THREAD

**Issue by hadiranjbar25** [gregberge/loadable-components#491]
Is there any loading placeholder support?
I know react-loadable has a loading option like this:
loading: ()=><div>Please wait...</div>
But I couldn't find anything here.

**Comment by theKashey** [comment]
`Suspense` 😉

**Comment by hadiranjbar25** [comment]
I have SSR. Is it OK if I use Suspense?

**Comment by theKashey** [comment]
In this case there a, well, already standard trick - create your own Suspense, which will be a plain `Fragment` for SSR.
```
import React from 'react';
import isNode from 'detect-node';

const LazyBoundary = ({children}) => <React.Fragment>{children}</React.Fragment>;
export default isBackend ? LazyBoundary : React.Suspense;
```

**Comment by hadiranjbar25** [comment]
What I exactly looked for was fallback. Thank you
