### ISSUE TITLE
multiple import calls inside `loadable()` function are not supported

### ISSUE THREAD

**Issue by zorgick** [gregberge/loadable-components#492]
I am trying to build fullstack React-Redux app. 

My goal is to support code-splitting and to be able to dynamically add reducers to the store. So I'm connecting redux reducers to dynamically loaded components like so

`
const NewComp = loadable(() =>
  import(
    /*  webpackChunkName: "my-comp" */ 'shared/containers/MyComp/reducer'
  ).then(module => {
    injectReducer('my', module.default)

    return import(
      /*  webpackChunkName: "my-comp" */
      'shared/containers/MyComp'
    )
  })
)
`

While I was using @loadable for client-side code, everything worked fine. But after I had added @loadable/babel-plugin, webpack failed to bundle the code and crushed with the following error

> loadable: multiple import calls inside `loadable()` function are not supported

I peeked inside the source code of this plugin, and saw that it is an expected behavior

`
// Multiple imports call is not supported
    if (callPaths.length > 1) {
      throw new Error(
        'loadable: multiple import calls inside `loadable()` function are not supported.',
      )
    }
`

Do you know how to inject redux reducers for ssr build? Please, help)

The full stub is accessible [here](https://github.com/zorgick/Initial_setup) on the branch **ssr**

**Comment by zorgick** [comment]
```
const NewComp = loadable(() =>
import(
/* webpackChunkName: "my-comp" */ 'shared/containers/MyComp/reducer'
).then(module => {
injectReducer('my', module.default)

return import(
  /*  webpackChunkName: "my-comp" */
  'shared/containers/MyComp'
)
})
)
```

Ooops, I didn't checked the markup. 

So here is the [link](https://github.com/gregberge/loadable-components/blob/cee89920d37c13e8c6ca435e72cccd42d2366059/packages/babel-plugin/src/index.js#L80) to the source code of the plugin

**Comment by theKashey** [comment]
That is not possible, refer to https://github.com/gregberge/loadable-components/pull/483
In short - no other code, except just `import` is supported with SSR.

However, what you  CAN do - create another file, `importer.js`, put this code inside
```js
const NewComp =import( 'shared/containers/MyComp/reducer')
.then(module => {
   injectReducer('my', module.default)
  return import(
  /*  webpackChunkName: "my-comp" */
  'shared/containers/MyComp'
  )
});

export default NewComp
```

Then import it using loadable. As long as this module returns promise by itself - you will "await" for it, and loadable would display NewComp after the initialization finishes.

**Comment by vassalloandrea** [comment]
I'm trying to make this work without success.

This is the error:
![image](https://user-images.githubusercontent.com/9986708/172113804-78d762f6-be96-44e3-933d-265281a468c3.png)

and here there is the implementation:

```
const MainContainerLoader = loadable(
  () => import('components/MainContainer/MainContainerLoader'),
  {
    fallback: LoadingFallback()
  }
);
```

`MainContainerLoader.js`

```
import { getStore } from 'store/store';

const JournalContainerLoader = import('redux-chunks/reducers').then(
  (module) => {
    const store = getStore();

    store.injectReducer('reducer1', module.default.reducer1);
    store.injectReducer('reducer2', module.default.reducer2);
    store.injectReducer('reducer3', module.default.reducer3);
    store.injectReducer('reducer4', module.default.reducer4);

    return import(
      /* webpackChunkName: "my-comp" */ 'components/mycomp/MyComp'
    );
  }
);

export default MainContainerLoader;
```

Do you have any suggestion here?
