### ISSUE TITLE
Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.

### ISSUE THREAD

**Issue by joetidee** [gregberge/loadable-components#493]
The above warning is being displayed using it like this:

```
const LoginPageLoader = loadable(() => import(
    /* webpackChunkName: 'login' */
    /* webpackPreload: true */
    '../pages/login/login-page.jsx'));

<Switch>
  <Route exact path={urls.pages.pathLogin()} component={LoginPageLoader} />
</ Switch>
```

Any ideas how I can get rid of this warning? Is it because the default export from `login-page.jsx` is wrapped in a function?

```
export default injectIntl(withRouter(LoginPage));
```

**Comment by theKashey** [comment]
Because `loadable` returns `React.forwardRef(Component)`, which is an "object".
The problem is on React-Router side, but just try to update it - probably you are using a bit old version.
