### ISSUE TITLE
Server did not response and remains loading while using chunkExtractor

### ISSUE THREAD

**Issue by hadiranjbar25** [gregberge/loadable-components#495]
When I am using chunk extractor (or chunkExtractorManager), server response remains pending. I don't what is the the reason for this, because there is nothing logged in the node server console.
```
    content = ReactDOMServer.renderToString(
      <ChunkExtractorManager extractor={extractor}>
        <Provider store={store}>
          <LanguageProvider>
            <ThemeProvider theme={Theme}>
              <StaticRouter location={req.url} context={context}>
                {sheet.collectStyles(<App />)}
              </StaticRouter>
            </ThemeProvider>
          </LanguageProvider>
        </Provider>
      </ChunkExtractorManager>
    );
```

and this is my loadable component:

```
import React from "react";
import loadable from "@loadable/component";

const MyComponent = loadable(() => import("../../views/MyComponent"), {
  fallback: <div />
});

const App = (props ) => (
  <MyComponent />
);
```
export default App;

**Comment by hadiranjbar25** [comment]
Can anyone help me with this issue? It's really a problem and I have no idea how to solve it!

**Comment by theKashey** [comment]
Could you provide a bit more code? I reckon your problem is hidden in some other place.
For example server request might be "pending" in case of uncaught, but suspended run time error...

**Comment by hadiranjbar25** [comment]
@theKashey The code is exactly what I have provided here. The things is it works when I comment ChunkExtractorManager. I means loadable works properly. But, it flicks in client side because not adding of chunks.

**Comment by theKashey** [comment]
So problem is on the server side, or on the client?

**Comment by hadiranjbar25** [comment]
It's on server side. renderToString doesn't work while I use ChunkExtractorManager, and in client side request status remains pending.

**Comment by theKashey** [comment]
Sorry, it might sounds a bit rude, but as a "experienced developer" you should understand that `renderToString` could not `not work`.
It is or working. Or failing with exception. Or, let's imagine third option, returning some crap.

Let's triage your situation:
- it is NOT "working"
- it is NOT "returning some crap"
- look like it's not doing anything, and also not letting your function to finish the job, and call `res.end`, to close a socket.
- so there is only one option left  - it's throwing an exception.  __And we are looking for that exception__.

Try to wrap this block with `try/catch` to figure our what is happening.

**Comment by hadiranjbar25** [comment]
You right. Sorry for the ambiguities. The third one is my problem that means:
look like it's not doing anything, and also not letting the function to finish the job, and call res.end, to close a socket with ERR_EMPTY_RESPONSE. The try/catch block doesn't catch any error.

**Comment by theKashey** [comment]
In this case I could not help without an example to reproduce. It's expected to work, and usually is doing it out of the box.

**Comment by hadiranjbar25** [comment]
I tracked the problem and I finally I found this:

in loadable.cjs.js, line 126 we have:
`invariant(!props.__chunkExtractor || ctor.requireSync, 'SSR requires `@loadable/babel-plugin`, please install it'); // Server-side`

the ctor's value comes from line 79:

`var ctor = resolveConstructor(loadableConstructor);
`
and resolveConstructor is: 

```
function resolveConstructor(ctor) {
  if (typeof ctor === 'function') {
    return {
      requireAsync: ctor
    };
  }
```

  return ctor;
}

there is juct requireAsync function defined and there is no requireSync function. I have no idea what is problem!

**Comment by theKashey** [comment]
Try updating loadable - probably was fixed 4 days ago - https://github.com/gregberge/loadable-components/issues/466
