### ISSUE TITLE
Jest babel plugin

### ISSUE THREAD

**Issue by JakeGinnivan** [gregberge/loadable-components#498]
## 🚀 Feature Proposal

Create a `@loadable/babel-plugin-jest` which makes requireAsync and requireSync both set a flag which makes `isReady return true.

## Motivation

It would be great to be able to make testing easier with @loadable/components without having to use webpack in your tests.

## Example

```
beforeAll(() => LazyMyComponent.load())

it('loads synchronously', () => {
   const mounted= mount(<LazyMyComponent />)

   expect(mounted.exists(MyComponent)).toBe(true)
})
```
## Pitch

Often you don't want the lazy nature of components inside tests, this would make it really easy for users who use jest without webpack to easily write tests which have loadable components in them.

**Comment by theKashey** [comment]
I was thinking about this idea so hard, that I've forgot to answer.

So the core idea is to __use just Jest__, or as you said - __use Jest without Webpack__. And the only missing part is no force `isReady` so `loadable` would just `require` stuff.

- should it be done via special version of  `babel plugin`, or some `configuration`, `environment variable` or just work out of the box for `node`?
- will you have to "configure" your tests, or it should just works? If second - that could be a breaking change :(
- what else did I miss?

**Comment by JakeGinnivan** [comment]
Yep, that's the gist of it. Thinking more about it, I think a babel plugin may not give the flexibility needed?

If the constructor could be accessed somehow that would alloy a helper function of some sort.

``` js
function createLoadable({ resolve = identity, render, onLoad }) {
  function loadable(loadableConstructor, options = {}) {
    const ctor = resolveConstructor(loadableConstructor)

    // ...

    Loadable.__loadableCtor = ctor
    return Loadable
  }
}
```

This would give the access to be able to do this if needed, it's just the constructor is trapped inside the closure so nothing outside can interact with it, could even be config which allows it to be on there but documenting should be enough.

``` js
function preload(Loadable) {
  Loadable.__loadableCtor.isReady = true
}
```

Then usage would just be something like this

```js
import { preload } from '@loadable/testing'

preload(Loadable)
```

**Comment by theKashey** [comment]
`@loadable/testing` sounds interesting, no matter what it exactly would be.

**Comment by hugotox** [comment]
So, what's the recommended way to test loadable components?

**Comment by theKashey** [comment]
You don't have to test them - we got you covered.
The best way to test components is just to run them in a "normal" SSR environment.
