### ISSUE TITLE
The path that is created by webpack can't be found when the program is started.

### ISSUE THREAD

**Issue by JiannanLv** [gregberge/loadable-components#499]
## 🐛 Bug Report

The path that is created by webpack can't be found when the program is started.

## To Reproduce

When i use the configs like this:
```
const output = {
    path: dist,
    filename: `[name].[chunkhash:5].js`,
    chunkFilename: `[name].[chunkhash:5].chunk.js`,
    libraryTarget: target === 'node' ? 'commonjs2' : undefined
  };
```

The program works well.but when i use the configs like this:
```
const output = {
    path: dist,
    filename: `js/[name].[chunkhash:5].js`,
    chunkFilename: `js/[name].[chunkhash:5].chunk.js`,
    libraryTarget: target === 'node' ? 'commonjs2' : undefined
};
```

The program can't work, the js in the configs is a variable which is a path.

## Expected behavior
I want to realize the feature that can support the configs with variables which can be configed in the filename.

**Comment by lovewinders** [comment]
I have similar trouble

**Comment by theKashey** [comment]
Is it `loadable` bug, or related to `webpack` itself?

**Comment by JiannanLv** [comment]
> Is it `loadable` bug, or related to `webpack` itself?

it is `loadable` bug

**Comment by richpet9** [comment]
I also have this problem. Loadable works perfectly, works well with Router v4, but as soon as I navigate outside of root `/` I get network resource errors, and the bundle can't be located. If I uninstall loadable and all references, it works fine.

**Comment by mankinchi** [comment]
@richpet9 I'm facing this issues. Can you elaborate on your solution?
