### ISSUE TITLE
Context.provider in ssr html, but in loadable component, this context could not be found

### ISSUE THREAD

**Issue by Heyxuxiaoting** [gregberge/loadable-components#500]
## 💬 Questions and Help

I got the snippet like this in my server-side code:
```js
// server.js
<Context.Provider value={{ a: 'hello' }}>
                <App />
</Context.Provider>
```

and a SubComp that needs to be render in server-side:
```js
// client.js
const SubComp = loadable(() => import('./SubComp.jsx'));
// SubComp.jsx
<Context.Consumer>
          {
                 context => {
                            console.log(context);
                            return (
                                <div>something...</div>
                            );
                }
         }
</Context.Consumer>
```

the result is **context** turns out to be the default context value, but not my { a: 'hello' }, is there anything I can do to solve this problem?

**Comment by gregberge** [comment]
Hey @Heyxuxiaoting  👋,
Thank you for opening an issue. We'll get back to you as soon as we can.
Please, consider supporting us on Open Collective. We give a special attention to issues opened by backers.
If you use Loadable at work, you can also ask your company to sponsor us ❤️.

**Comment by theKashey** [comment]
>  is there anything I can do to solve this problem?

That's not possible. I mean - you should not have any problem. There is also no way `loadable` could `cause` or `fix` this - this is how React works, and who are we to interfere with it.

Please check your code. Please check that `Context` is pointing to the same thing in both cases. And you can double check that removal of the loadable would not fix anything.

**Comment by Heyxuxiaoting** [comment]
I've found the problem, my own project settings cause this problem, thank you for your reply.
