### ISSUE TITLE
Safari does not show the fallback component

### ISSUE THREAD

**Issue by hkhere** [gregberge/loadable-components#509]
The fallback component will not be shown untill the dynamically imported component is completely loaded on desktop and mobile Safari. 

Assuming  we have an app that dynamically load the home page,  when safari loads the app first time it will not show the fallback component when it is loading the async chunks containing the home page.

**Comment by hkhere** [comment]
@gregberge Here is a reproducible test repo. The app will show a loading component for ten seconds before it serves the request of the async chunk containing the home component which is dynamically imported.

**Comment by theKashey** [comment]
Upd: so this issue was related to _webpack-css-stuff_, and not directly related to loadable components.
