### ISSUE TITLE
How to avoid blinking when switching between pages using react-router?

### ISSUE THREAD

**Issue by ashgaliyev** [gregberge/loadable-components#512]
## 💬 Questions and Help

Hi,

Here is the problem:
![Screen Recording 2020-01-14 at 03 39 PM](https://user-images.githubusercontent.com/818556/72337339-3651df00-36e4-11ea-96ec-35068e99d4db.gif)
When the page just loads, it causes blinks (or flashes) while navigating the pages. But after visiting the page for the first time it works smoothly.
How to make it work smooth always?
I tried to add `webpackPrefetch: true` but this doesn't help. 
Here is the repo for reproduce https://github.com/ashgaliyev/react-router-loadable-components-flashing-problem

**Comment by oreqizer** [comment]
you can `Component.preload()` on hover of those links

**Comment by ashgaliyev** [comment]
@oreqizer Awesome! That's helped! Thank you! Is there a way to call `preload` for each component when the browser is idle?

**Comment by oreqizer** [comment]
> Is there a way to call preload for each component when the browser is idle?

Don't know personally, you will probably have to implement some logic yourself. Maybe someone else will be of more help here

**Comment by theKashey** [comment]
Preloading everything is quite opposite to the idea of code splitting.

`React`(experimental) itself recommends using `useTransition` and `Suspense` to deffer page change until "the new page" is ready. Refer to docs.

**Comment by olso** [comment]
@oreqizer any ideas for touch devices? 🤔

**Comment by theKashey** [comment]
@oreqizer - you can use `touchstart`, which will give you an extra 300ms to load the stuff.

**Comment by olso** [comment]
@theKashey I tried at, but still got blinking, I'll try with prod build actually

**Comment by theKashey** [comment]
Well, the "real" fix would be to use `useTransition` and `Suspense` from the experimental branch of React, so you will be able to "block" transition until the new page is ready.

But that's "experimental" today, and there is not much you can do.

However, you can try preventing navigation event manually and replaying it once page is ready to accept transition. Probably react-router would be not a best choice in this case.

**Comment by hjoelh** [comment]
The way I solved this is by not using [loadable-components](https://github.com/gregberge/loadable-components) but rather React.lazy and [dynamic imports](https://reactjs.org/docs/code-splitting.html#import)

While your routes are React.lazy'd
 
Link to a page: 

```
    <a
      href='/dashboard'
      onMouseEnter={() => import('pages/dashboard')} // this is like a prefetch
      onClick={(e) => {
        e.preventDefault();
        import("pages/dashboard").then(() => { // waits for import before navigating (no spinners/fallback)
          navigate("/dashboard");
        });
      }}
    />
```

Hope this helps
