### ISSUE TITLE
Dynamically imported components does not render in SSR

### ISSUE THREAD

**Issue by hadiranjbar25** [gregberge/loadable-components#515]
I have implemented a SSR application. the problem is that imported components using loadable function are not rendered in server. I am importing my components like this:

`const Layout = loadable(() => import("./layouts/layout/Layout"))`

I remeber that I had the same problem with react-loadable and the solution was using preloadAll

```javascript
Loadable.preloadAll().then(data => {
  app.listen(_PORT, function() {
    console.log(`Server is listening on port: ${_PORT}`);
  });
});
```
But I could not find any solution to preload all components on the server side. What is the solution for this?

**Comment by theKashey** [comment]
> What is the solution for this?

`loadable` babel plugin, which makes possible to import components __synchronously__. It should work out of the box, and should complain in case of improper installation - please check your setup.

**Comment by hadiranjbar25** [comment]
I am using this plugin. I am using babel-register and this is my config:

```
require("@babel/register")({
  presets: [
"@babel/preset-env", "@babel/preset-flow", "@babel/preset-react"],
  plugins: [
    "@loadable/babel-plugin",
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-class-properties",
    "babel-plugin-dynamic-import-node",
    "@babel/plugin-transform-modules-commonjs",
    [
      "module-resolver",
      {
        root: ["./src"]
      }
    ]
  ]
});

require("ignore-styles");
require("asset-require-hook")({
  extensions: ["png", "jpg", "svg"],
  name: "/static/media/[name].[hash:8].[ext]",
  limit: 10000,
});

module.exports = require("./server.js");
```
