### ISSUE TITLE
Need help for my unit test with load

### ISSUE THREAD

**Issue by yanv1991** [gregberge/loadable-components#518]
## 💬 Questions and Help

I have a wrapped loadableComponent inside another stateless component, I want to check if the loadable it's already rendered, previously with `react-loadable`, we didn't need to worry about this since with the help of `preloadAll()` we achieved it, but not sure how to force the load of the component before my assertion happen.

```
const wrapper = mount(<Wrapper name="test" `/>);

expect(wrapper.find('svg')).toHaveLength(1); // not loaded yet
```

```
const Wrapper = (props) => {
   const MyLoadable = loadable(() => import('./MyOtherComp');

   return (<Errors><MyLoadable /></Errors>);
}
```

**Comment by gregberge** [comment]
`preloadAll` does not exist. You have to wait for the element to be present, like you do in real.

**Comment by yanv1991** [comment]
@gregberge that's my goal, but not sure how to achieve that with loadable-component, any suggestions ? I can do that if I have access to my loadable component directly in my test using `load` but in this case my component is wrapped inside another stateless . Thank you in advance .

**Comment by gregberge** [comment]
With react-testing-library you should be able to wait for the component to be ready.
