### ISSUE TITLE
how to load json file through loadable component ?

### ISSUE THREAD

**Issue by cullsin** [gregberge/loadable-components#522]
## 💬 Questions and Help

I have a list of json files and I would like to load only required or called. I did not get a plain response from loadable component. Please suggest.

    `import loadable from 'loadable-components'
     import variantA from './variantA.json';
     import variantB from './variantB.json';
     import variantC from './variantC.json';
     import variantD from './variantD.json'; 
     import variantE from './variantE.json';
     import variantF from './variantF.json';
     import variantG from './variantG.json';
     import variantH from './variantH.json';
     import variantI from './variantI.json';
     import variantJ from './variantJ.json';
     import variantK from './variantK.json';
    const noVariant = loadable(() => import('./default.json')) /* not return json file */
    const variant = {
       default: noVariant,
       a: variantA,
       b: variantB,
       c: variantC,
      d: variantD,
      e: variantE,
      f: variantF,
      g: variantG,
      h: variantH,
      i: variantI,
      j: variantJ,
      k: variantK
     };
     export default variant;`

**Comment by gregberge** [comment]
Loadable Components is design to load Components, and nothing else. You have to use `loadable.lib` or a direct dynamic import.
