### ISSUE TITLE
Handle of Loading chunk failure

### ISSUE THREAD

**Issue by idangozlan** [gregberge/loadable-components#525]
## 🚀 Feature Proposal

Handle a failure loading of a chunk (internet reconnection, cdn hickup, etc)
`ChunkLoadError`

## Motivation

Better UX

## Example

Before loading the next chunk, make browser offline

**Comment by gregberge** [comment]
This is the business of webpack, not loadable components.

**Comment by theKashey** [comment]
This should be manager by the ErrorBoundary/component recreation. There is a little issue with it right now, but it's going to be fixed - #521
