### ISSUE TITLE
SSR is not work when adding vendor split chunks

### ISSUE THREAD

**Issue by idangozlan** [gregberge/loadable-components#527]
## 🐛 Bug Report

When using the SSR example of this repo, and adding vendor split chunks

## To Reproduce

Run this project
https://github.com/gregberge/loadable-components/blob/master/examples/server-side-rendering/

with the following addon to the webpack config:
```
  optimization: {
    splitChunks: {
      cacheGroups: {
        vendor: {
          test: /node_modules/,
          chunks: 'initial',
          name: 'vendor',
          enforce: true
        },
      }
    },
    runtimeChunk: true
  },
```

## Expected behavior

Split vendor modules

Results:
```
Server started http://localhost:9000



// Performing request




Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a.b.render (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:48:37)
    at a.b.read (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at app.get (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/lib/server/main.js:57:43)
    at Layer.handle [as handle_request] (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/express/lib/router/layer.js:95:5)
    at /Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/express/lib/router/index.js:281:22
    at param (/Users/idangozlan/tovia/tests/loadable-components/examples/server-side-rendering/node_modules/express/lib/router/index.js:354:14)
```

**Comment by theKashey** [comment]
Sorry, but there are not enough details.

**Comment by idangozlan** [comment]
What other details do you need? All the info + how to reproduce is here

**Comment by theKashey** [comment]
Sorry, missed the point that you've used a standard example.

**Comment by hasandogu** [comment]
Hello!

Thanks for all the great work with this library. We were wondering if there are any updates on this as we are trying to make split vendor modules work with SSR and seeing similar problems on our side.

**Comment by Ephem** [comment]
Anecdotally, we have vendor chunks as well and have not had any problems with this in Webpack 4. I'm upgrading to Webpack 5 now and it does seem to work correctly there as well for us, so this issue is probably dependent on specific config and circumstances.

**Comment by eliseumds** [comment]
@Ephem would you share you config with us, please? I could only get it to work with NodeJS v15 by using `LimitChunksPlugin { maxChunks: 1 }`

**Comment by Ephem** [comment]
@eliseumds I don't think I can share entire configs (our entire setup is pretty complex too), but I can try to outline how we do things. We are still on Node v12 though if that makes a difference.

We have two builds, a client and a server build. The server build actually uses `LimitChunkCountPlugin` in prod (replaced by `eager-imports-webpack-plugin` in dev for speed), but I did try it with split chunking and got that to work as well with just the default config.

In dev, we generate stats-files in memory and feed those into the `ChunkExtractor` manually, in prod we generate actual stats-files and feed those into the `ChunkExtractor`. The takeaway here is that we generate our own stats and turn off generating the Loadable stats like this: `new LoadablePlugin({ writeToDisk: false, outputAsset: false })`.

```js
  const nodeExtractor = new ChunkExtractor({ statsFile: nodeStats })
  const { default: App } = nodeExtractor.requireEntrypoint()
  ```
  
We don't use the above part at all. We bundle the Express server and app together, so we can just import the App directly instead of `requireEntrypoint()`, meaning we don't need the `nodeExtractor` either. The error message in the first post here seems to point to these lines in the stack trace, so maybe this is the difference that makes it work?

Actually, looking at these lines now, I wonder what happens in the demo if you do `const App = nodeExtractor.requireEntrypoint()` instead of `default: App`? Don't have time to check myself right now.

**Comment by adbutterfield** [comment]
I ran into this same issue yesterday, and looked into it. The offending line is this here:
https://github.com/gregberge/loadable-components/blob/8f10896058cdfd542c2aca1a982c2e14b1d9707a/packages/server/src/ChunkExtractor.js#L383
```
const mainAsset = assets.find(asset => asset.scriptType === 'script')
```
`find` in my case was finding `runtime-main.js` which was the first item in the array, and of course does not have a default export of my App component to render (that would be main.js, which was the only other item in my array). 
Probably not the best fix, but I got it to work by changing to:
```
return asset.scriptType === 'script' && !asset.filename.includes('runtime')
```
But that would then assume that you don't change the default name of the runtime chunk.

**Comment by adbutterfield** [comment]
I guess I should add that by "working" I mean not getting this exact error, but I still couldn't get a project working based on the SSR example (meaning with the webpack multi config and using nodeExtractor.requireEntrypoint()).

I have an example here of something that does work, without the multi config, and not using requireEntrypoint:
https://github.com/adbutterfield/fast-refresh-express

(If interested, not working version is on the `not-working` branch here:https://github.com/adbutterfield/fast-refresh-express/tree/not-working)

**Comment by kildevaeld** [comment]
Hello. As a quickfix reversing the assets array before finding the first asset matching the scriptType, seems to fix the problem. I'm able to get both runtimeChunk and splitChunks to work.

**Comment by kdevan** [comment]
Do we need to fork this project to get single runtimeChunk working? That's ok if so, just want to make sure there's no way outside of forking to possibly adjust the files in the way that ChunkExtractor expects?
