### ISSUE TITLE
Page gets broken with SSR + client side mode

### ISSUE THREAD

**Issue by Romcol** [gregberge/loadable-components#528]
Hi,

I've played around with this lib and tried to implement server side rendering (such as here https://github.com/gregberge/loadable-components/tree/master/examples/server-side-rendering).

When the server side is loaded along with the client side I get this error

https://ibb.co/m85Cj18

I render my page a first time and I extract the chunks this way `
  const statsFile = path.resolve('var/webpack/loadable-stats.json');

  const extractor = new ChunkExtractor({ statsFile, entrypoints: ['app'] });

  const sheets = new ServerStyleSheets();

  const html = ReactDOMServer.renderToString(
    sheets.collect(extractor.collectChunks(reactElement)),
  );`

Components are imported according to routes such as this `const Privacy = loadable(() =>
  import('./views/profile/private/myProfile/privacy/Privacy'),
);.`. 

I have `@loadable/babel-plugin` and `syntax-dynamic-import` in my babel config.

In both webpack (SSR and client) `LoadablePlugin()` is successfully imported.

I use this on the client `  loadableReady(() => {
    ReactDOM.hydrate(reactElement, document.getElementById(domNodeId));
  });`

I have a few questions that can help solve the issue 

- Why do we need to generate two stats files (SSR + client) as show here (https://github.com/gregberge/loadable-components/blob/master/examples/server-side-rendering/src/server/main.js)? Is this a compulsory step?

- Do I need to use `extractor.getLinkTags()` or is it not useful?

I seems it's a importation problem.

Thank you and thanks for the lib !

Have a good day,

**Comment by theKashey** [comment]
Your error is about trying to `require` a module, which is not yet ready (the problem was within `isReady` check). Actually it shall be fixed already, so please try to update package version.

> Why do we need to generate two stats files?

No, you  have to generate and use only one file - the client side one, so the server would be able to send chunks which were created for the client.

> Do I need to use extractor.getLinkTags()

Only if you use CSS-in-CSS, ie you have those link tags.
