### ISSUE TITLE
Add SWC Plugin

### ISSUE THREAD

**Issue by heygrady** [gregberge/loadable-components#529]
https://swc-project.github.io/docs/usage-plugin

**Proposal:** create an `@loadable/swc-plugin` that is similar to `@loadable/babel-plugin`

[SWC](https://github.com/swc-project/swc) is increasing in popularity. It is aiming to be a drop-in replacement for babel with some significant [speed improvements](https://swc-project.github.io/blog/2020/02/16/why-is-swc-fast). It already has a [webpack loader](https://swc-project.github.io/docs/usage-swc-loader).

There is some early interest in how it might integrate with create-react-app (https://github.com/facebook/create-react-app/issues/8060). Looking at [which babel plugins create-react-app uses](https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/package.json#L25-L38) it seems like most of those things are [supported by swc](https://swc-project.github.io/docs/comparison-babel) (with only a few exceptions).

Looking at my own projects, I see only a few things that are blocking me from switching to SWC.

1. No support for [`babel-plugin-macros`](https://github.com/kentcdodds/babel-plugin-macros) (which I could live without)
2. No support for `@loadable/babel-plugin`

Generally everything else babel does for me is handled by [swc preset-env](https://swc-project.github.io/docs/preset-env) (or isn't particularly vital to my projects).

**Comment by heygrady** [comment]
Cross linking: https://github.com/kentcdodds/babel-plugin-macros/issues/144

**Comment by gregberge** [comment]
It looks great, any PR is welcome!

**Comment by theKashey** [comment]
Look like here is the documentation - https://swc-project.github.io/docs/usage-plugin
`SWC` is written in `rust`, however, plugin system exposed in JS... so eventually `swc` would become a ~dragon~ babel it was created to kill.

**Comment by paul-vd** [comment]
Did anyone have a chance to look at this yet?

**Comment by marwan38** [comment]
We're in the same boat over here. I was looking at what would be needed to do this, but, I don't have enough knowledge with AST or the time available (unless I get granted time during work) to do this.

This is (AFAIK) the only thing that's stopping us from migrating over to SWC as well.

**Comment by Perni1984** [comment]
> This is (AFAIK) the only thing that's stopping us from migrating over to SWC as well.

same here - updated links to Next.js implementation https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/core/src/next_dynamic.rs

**Comment by aplassen** [comment]
Perhaps a workaround could be to use **babel** only on the files containing **@lodable()** statements?  For example by naming them something like `MyComponent.loadable.tsx` (to make it easy to differenciate the babel-loader & swc-loader).

**Comment by theKashey** [comment]
That is a good option and actually can lead to a better visibility over bundle structure.

**Comment by ashsearle** [comment]
See https://github.com/swc-project/plugins/pull/76

**Comment by theKashey** [comment]
And https://github.com/gregberge/loadable-components/issues/909
