### ISSUE TITLE
Loadable components not rendering on server

### ISSUE THREAD

**Issue by mohantorrez** [gregberge/loadable-components#530]
Loadable component on ssr not rendering on server but works fine on client side.
In my main container header and footer is rendering on server only component with loadable is not loading on server

react version 

`
"react": "^16.12.0"
"react-router-config": "^1.0.0-beta.4",
"react-router-dom": "^4.3.0",
"react-router-redux": "^5.0.0-alpha.9"`

server.js

`<ChunkExtractorManager extractor={extractor}>
        <Provider store={store}>
            <StaticRouter location={location} context={context}>
                 <ReduxAsyncConnect routes={routes} />
             </StaticRouter>
          </Provider>
 </ChunkExtractorManager>`

Client.js
`loadableReady(() => {
	hydrate(
	    	<Provider store={store}>
	    	<ConnectedRouter history={history}>
	    		<ReduxAsyncConnect routes={routes} />
	    		</ConnectedRouter>
	      </Provider>,
	    document.getElementById('app')
	);
})`

Webpack plugin also added. stats.json file is created with chunk hash values.
What am i doing wrong here? Please help

**Comment by gregberge** [comment]
If chunks are not correctly extracted, it is likely because you don't run the code that calls `loadable()` on server. It is probably because data are not ready when you try to render it server-side. It is complicated to know what is exactly the problem without the complete code.

**Comment by mohantorrez** [comment]
Am using react-router-config. Please find the sample code where ssr s not loading
App.js
```
import React, { Suspense } from 'react';
import { renderRoutes } from 'react-router-config';

class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            settings: '',
            loginStatus: false,
            adminStatus: false,
            modal: false,
            modalTitle: '',
            modalContent: '',
            gifting:{
                spend: false,
                gift: false
            },
            ...props.serverData
        };
       
    }
    getRoutes = () => {
        console.log('gettings routes')
        return renderRoutes(
                this.props.route.routes,
                {
                    settings: 'getsettings'
                }
            )
    }
   
    render() {
        return(
            <React.Fragment>
                <div>hello app</div>
                {this.getRoutes()}
            </React.Fragment>
        )
    };


export default (App);
```

Login.js
```
import React from 'react';
class Login extends React.Component {
    constructor(props) {
        super(props);
        console.log('(((((((((((((((((((((((((((')
        this._isMounted = false;
    }

    render() {
        return(
            <div>
               hello login
            </div>
        )
    }
}

export default (Login);
```

index.js
```
loadableReady(() => {
	hydrate(
	    <GoogleReCaptchaProvider reCaptchaKey={"initialState.appReducer.googleCaptchaSiteKey"}>      
		    	<BrowserRouter history={history}>
	    		{renderRoutes(routes)}
	    	</BrowserRouter>
	    </GoogleReCaptchaProvider>,
	    document.getElementById('app')
	);
})
```

Routes.js

```
import React from 'react';
import App from './components/App';
import loadable from '@loadable/component';

const Login = loadable(() => import('./components/Login'));

const routes = [{
    component: App,
    routes:[{
			path: '/login',
			exact: true,
			component: Login
}]
}];

export default routes;

```

**Comment by mohantorrez** [comment]
@gregberge Able to track it till <script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[]</script>. Always return loadable chunk as empty value.

What can be the reason ?

**Comment by damassi** [comment]
ChunkExtractor takes an `entrypoints` array, make sure you're passing in the correct path.

**Comment by kri7217** [comment]
*******scripttags <script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[]</script><script id="__LOADABLE_REQUIRED_CHUNKS___ext" type="application/json">{"namedChunks":[]}</script>

https://gist.github.com/kri7217/c1843f5f47e1440e7ed7bc310bde4918

@damassi  I have passed the entrypoints, but still getting empty []

**Comment by damassi** [comment]
@kri7217 - be sure to run `extractor.collectChunks`, I think that's the problem:

https://github.com/artsy/force/blob/master/src/v2/Artsy/Router/buildServerApp.tsx#L157-L164

**Comment by rahulsharma-popshop** [comment]
@kri7217 Did you get the solution?

**Comment by kri7217** [comment]
Yes fixed the problem

**Comment by rahulsharma-popshop** [comment]
@kri7217  How did you fix it?

**Comment by kri7217** [comment]
> @kri7217 How did you fix it?

How did you export the components ?
And how you are dynamically importing for creating chunks ?

export will always be default for loadable
I corrected above two areas and it worked.

**Comment by rahulsharma-popshop** [comment]
Thanks, I'll try

**Comment by damassi** [comment]
> export will always be default for loadable

Note that in a recent update this is now [configurable](https://github.com/artsy/force/pull/6690).
