### ISSUE TITLE
Loadable Components work with Preact?

### ISSUE THREAD

**Issue by valse** [gregberge/loadable-components#533]
Hi, I'm using Loadable Components in a Gatsby project with the `gatsby-plugin-loadable-components-ssr` plugin and it works as expected... but if I add the Preact support adding aliases to React libraries in my webpack config, some features stopped working... so I can't understand if it's a compatibility issue with Preact or something else.

Thanks
valse
`

**Comment by theKashey** [comment]
I never tried it by myself, but technically there are no restrictions; loadable is not using any internals; probably should work out of the box.

**Comment by valse** [comment]
> I never tried it by myself, but technically there are no restrictions; loadable is not using any internals; probably should work out of the box.

Ok thanks... I'm checking the `gatsby-plugin-loadable-components-ssr` plugin if there is something there that can cause this issue.
