### ISSUE TITLE
component loading twice

### ISSUE THREAD

**Issue by erwinbooky** [gregberge/loadable-components#534]
the webpage is loading twice, first, it's initial without the loadable-component after a few seconds the fallback will show then load the fully-functioning page. this is after I added SSR

**Comment by theKashey** [comment]
That's not gonna work without an example. And with a small example it would just work. 110% sure. Just try to create a small reproduction of a problem, and it would help you solve the problem.

**Comment by erwinbooky** [comment]
actually found the issue, it was blinking, I'm using apollo, redux and react-router-dom with it, 
This is basically how I implement it 

index.js
`const store = ssrStore(window.__STATE__);
const client = createApolloClient(window.__APOLLO__, fragmentTypes);
delete window.__STATE__;
delete window.__APOLLO__;

loadableReady(() => {
  hydrate(
    <ApolloProvider client={client}>
      <Provider store={store}>
        <Router>
          <App />
        </Router>
      </Provider>
    </ApolloProvider>,
    document.querySelector('#app'),
  );
});`

Server.js
`const statsFile = path.resolve('./assets/stats.json');
    const extractor = new ChunkExtractor({ statsFile, entrypoints: ['client'] });
    jsx = extractor.collectChunks(
      <ApolloProvider client={client}>
        <Provider store={reduxStore}>
          <Router location={req.path} context={context}>
            <App />
          </Router>
        </Provider>
      </ApolloProvider>
    );
    scriptTags = extractor.getScriptTags();
  }
  let content = null;
  try {

    await getDataFromTree(jsx);
    // content = await renderToStringWithData(jsx);
  } `

**Comment by theKashey** [comment]
` scriptTags = extractor.getScriptTags();`
should be placed after
`await getDataFromTree(jsx);`

**Comment by erwinbooky** [comment]
OMG that works! Thanks! I've been racking my brain for days about this issue. Thank you so much
