### ISSUE TITLE
Server without webpack

### ISSUE THREAD

**Issue by masterpuppet** [gregberge/loadable-components#535]
Hi everyone, in my current setup i have webpack + babel for the client side code and babel for the server side code(no webpack), so, i would like to know if loadable-components would work on such setup.

Thanks in advance.

**Comment by gregberge** [comment]
@masterpuppet, yeah it could work but it is not recommended. You should build a server-side version of your client-side code with webpack. You will avoid many problems (css import, image import, etc...) that are not natively supported by Node.js.

**Comment by theKashey** [comment]
> You will avoid many problems (css import, image import, etc...)

There are different `css` and `assets` __node__ loaders, so that's, of course, possible, but you will have to duplicate configuration, and possibly break something from time to time.

So `loadable` would work on that setup. It's more about your own app.
