### ISSUE TITLE
loadable: SSR requires `@loadable/babel-plugin`, please install it

### ISSUE THREAD

**Issue by WinmezzZ** [gregberge/loadable-components#536]
## 🐛 Bug Report

SSR code-splite doesn't work with typescript

## To Reproduce

Using dynamic import will be error: 'loadable: SSR requires `@loadable/babel-plugin`, please install it', and I'm sure that I had installed `@loadable/babel-plugin.

By the way, I didn't use ts-loader to compire but babel-presets-typescript, and anything is ok if without typescript.

**Comment by theKashey** [comment]
See https://github.com/gregberge/loadable-components/issues/458 as a solution.
