### ISSUE TITLE
@loadable/babel-plugin not support webpack magic comments

### ISSUE THREAD

**Issue by kaysonwu** [gregberge/loadable-components#538]
## 🐛 Bug Report
`@loadable/babel-plugin`、`Module not found`

As long as I remove `@loadable/babel-plugin`  from` babel.config.json`  it compiles correctly.  

```bash
ERROR in ./src/components/router/index.tsx
Module not found: Error: Can't resolve '@/pages/' in 'D:\htdocs\react\react-app\src\components\router'
 @ ./src/components/router/index.tsx 54:13-44 26:11-30:15
 @ ./src/components/application/index.tsx
 @ ./src/server.tsx
```

The code reporting the error is:

```typescript
const Page = loadable((props: any) => import(/* webpackChunkName: "pages/[request]" */`@/pages/${props.path}`), {
  cacheKey: props => props.path
});
```
 I configured `resolve.alias`  in `webpack`,  The error persists even though I use relative path.

## To Reproduce

 [react-app](https://github.com/kaysonwu/react-app/tree/3.x).

```bash
git clone -b 3.x https://github.com/kaysonwu/react-app.git

yarn install && yarn build:server
```

## Expected behavior

Compile correctly

## Link to repl or repo (highly encouraged)

 [react-app](https://github.com/kaysonwu/react-app/tree/3.x).

```bash
## System:
 - OS: Windows 10 10.0.18363
 - CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
 - Memory: 1.74 GB / 7.89 GB
## Binaries:
 - Node: 12.13.1
 - Yarn: 1.21.1
 - npm: 6.13.4
## npmPackages:
 - @loadable/babel-plugin: ^5.12.0 => 5.12.0 
 - @loadable/component: ^5.12.0 => 5.12.0
 - @loadable/server: ^5.12.0 => 5.12.0
 - @loadable/webpack-plugin: ^5.12.0 => 5.12.0
```

**Comment by kaysonwu** [comment]
@gregberge

**Comment by theKashey** [comment]
For now - just don't use module aliases.
Plus could you explain how you configured them.

**Comment by kaysonwu** [comment]
@theKashey  I have provided the project, you can download it and try it. Unfortunately, even with relative paths, errors are reported.

**Comment by theKashey** [comment]
out of curiosity (sorry, I cannot download and try your example right now) - try `'@/pages/'+props.path`, ie a bit simpler construction.
The problem is not at the loadable side, the problem is in `webpack`, which does not like the code generated by the babel plugin.
Thus we have to find something webpack will like, and then might be amend babel plugin  somehow.

> Meanwhile I would personally not recommend to use full dynamic import for named chunks/pages. It's cool, but you don't need it.

**Comment by kaysonwu** [comment]
Thank you for your advice, but let me write repetitive code. I prefer simplicity.  One thing is for sure, the problem must be with `@loadable/babel-plugin`.  Maybe I should research its source code

**Comment by theKashey** [comment]
`/* webpackChunkName: "pages/[request]" */ ` is the issue. Remove it and it would be ok.
Probably this is what babel plugin is breaking by a some reason.
>PS:  add `modules:false` to your babel config.

**Comment by kaysonwu** [comment]
@theKashey Thank you for finding out the source of the problem.  @gregberge  It seems you need to update `@loadable/babel-plugin` to support webpack magic comments.

**Comment by kaysonwu** [comment]
@theKashey @gregberge I need your help because it can't use the `[request]` placeholder

**Comment by kaysonwu** [comment]
I found that something seemed to be deleted in this line of [code](https://github.com/gregberge/loadable-components/blob/master/packages/babel-plugin/src/properties/chunkName.js#L110), so webpack could not find the module

**Comment by kaysonwu** [comment]
```javascript
 loadable(() => import(/* webpackChunkName: "pages/exception-404" */'@/pages/exception/404'))
[
  NodePath {
    parent: Node {
      type: 'StringLiteral',
      start: 222,
      end: 245,
      loc: [SourceLocation],
      extra: [Object],
      value: '@/pages/exception/404',
      leadingComments: [Array],
      innerComments: undefined,
      trailingComments: undefined
    },
    hub: {
      file: [File],
      getCode: [Function: getCode],
      getScope: [Function: getScope],
      addHelper: [Function: bound addHelper],
      buildError: [Function: bound buildCodeFrameError]
    },
    contexts: [],
    data: null,
    _traverseFlags: 0,
    state: null,
    opts: null,
    skipKeys: null,
    parentPath: NodePath {
      parent: [Node],
      hub: [Object],
      contexts: [],
      data: null,
      _traverseFlags: 0,
      state: [Object],
      opts: [Object],
      skipKeys: null,
      parentPath: [NodePath],
      context: [TraversalContext],
      container: [Array],
      listKey: 'arguments',
      key: 0,
      node: [Node],
      scope: [Scope],
      type: 'StringLiteral'
    },
    context: null,
    container: [ [Object] ],
    listKey: 'leadingComments',
    key: 0,
    node: {
      type: 'CommentBlock',
      value: ' webpackChunkName: "pages/exception-404" ',
      start: 176,
      end: 221,
      loc: [SourceLocation]
    },
    scope: Scope {
      uid: 123,
      block: [Node],
      path: [NodePath],
      labels: Map {},
      references: [Object: null prototype] {},
      bindings: [Object: null prototype] {},
      globals: [Object: null prototype] {},
      uids: [Object: null prototype] {},
      data: [Object: null prototype] {}
    },
    type: 'CommentBlock'
  }
]
```
Importing multiple possible targets will report errors， As follows：

```javascript
loadable((props: any) => import(/* webpackChunkName: "pages/[request]" */ `@/pages/${props.path}`))

[
  NodePath {
    parent: Node {
      type: 'BinaryExpression',
      start: 358,
      end: 381,
      loc: [SourceLocation],
      left: [Node],
      operator: '+',
      right: [Node],
      leadingComments: [Array],
      innerComments: undefined,
      trailingComments: undefined
    },
    hub: {
      file: [File],
      getCode: [Function: getCode],
      getScope: [Function: getScope],
      addHelper: [Function: bound addHelper],
      buildError: [Function: bound buildCodeFrameError]
    },
    contexts: [],
    data: null,
    _traverseFlags: 0,
    state: null,
    opts: null,
    skipKeys: null,
    parentPath: NodePath {
      parent: [Node],
      hub: [Object],
      contexts: [],
      data: null,
      _traverseFlags: 0,
      state: undefined,
      opts: [Object],
      skipKeys: null,
      parentPath: [NodePath],
      context: [TraversalContext],
      container: [Array],
      listKey: 'arguments',
      key: 0,
      node: [Node],
      scope: [Scope],
      type: 'BinaryExpression'
    },
    context: null,
    container: [ [Object] ],
    listKey: 'leadingComments',
    key: 0,
    node: {
      type: 'CommentBlock',
      value: ' webpackChunkName: "pages/[request]" ',
      start: 316,
      end: 357,
      loc: [SourceLocation]
    },
    scope: Scope {
      uid: 125,
      block: [Node],
      path: [NodePath],
      labels: Map {},
      references: [Object: null prototype] {},
      bindings: [Object: null prototype],
      globals: [Object: null prototype] {},
      uids: [Object: null prototype] {},
      data: [Object: null prototype] {}
    },
    type: 'CommentBlock'
  }
]
```

`@loadable/babel-plugin` The resulting module cannot be found error, only occurs under webpack compilation.

**Comment by kaysonwu** [comment]
I don't quite understand. For the import with `webpackChunkName` already set,` @loadable/babel-plugin` still deletes and adds it, isn't it redundant? see [code](https://github.com/gregberge/loadable-components/blob/master/packages/babel-plugin/src/properties/chunkName.js#L135)

**Comment by kaysonwu** [comment]
After testing, I have clearly identified the source of the problem. Please refer to my minimal reproduction [loadable-babel-plugin](https://github.com/kaysonwu/minimal-reproduction/tree/master/loadable-babel-plugin)

If you just compile with Babel, `Page` is an aggressive import. Unfortunately, when compiled with `ts-loader` in` webpack`, `Page` becomes` BinaryExpression` type.

Personally, the responsibility of the `chunkName` property is to supplement the` webpackChunkName` annotation for import. So if you set `webpackChunkName` yourself, it should not do any work. Therefore, I deleted this line of [code](https://github.com/gregberge/loadable-components/blob/master/packages/babel-plugin/src/properties/chunkName.js#L135)

**Comment by kaysonwu** [comment]
@gregberge @theKashey Who can evaluate it? Thank you!
