### ISSUE TITLE
Adding react-hot-loader to the SSR example

### ISSUE THREAD

**Issue by gabenrevard** [gregberge/loadable-components#540]
I've been playing out with the SSR example and it works like a charm! However I ran into a problem when trying to get it working with react-hot-loader. I get the server the reload on file-changes but I'm not sure how to properly handle the loadable-stats.json files and getting the client to refresh.

I'd love to see this being added to the current SSR example 👍

**Comment by theKashey** [comment]
Hey. But a coincidence I'm maintaining react-hot-loader as well, and... `loadable-components` are not quite compatible with it.
So we cannot add an example you are looking for, as long as it would not work.

**Comment by gabenrevard** [comment]
Ah, alright! Are there any plans for making it compatible? I feel like hot reloading is the only missing piece right now

**Comment by theKashey** [comment]
There is a simple way how to make it more or less compatible - rewrite it to `hooks`. However it will also mean a complete rewrite and we would have to cancel all ongoing PRs and so on.
So I am not sure that's possible right now, but that's our future in any way.
