### ISSUE TITLE
SSR supports multiple imports

### ISSUE THREAD

**Issue by kaysonwu** [gregberge/loadable-components#543]
## 🚀 Feature Proposal

SSR supports multiple imports,

## Motivation

This is a fully controlled import.

## Example

```tsx
const Language = loadable.lib(
  async (props: any) => {
    const messages = {};
    for (const path of props.paths) {
      try {
        const { default: _ } = await import(/* webpackChunkName: "locales/[request]" */ `@/locales/${path}`);
        Object.assign(messages, _);
      } catch (e) {
        console.error(e);
      }
    }
    return messages;
  },
  { 
    cacheKey: (props: any) => `Locales-${props.paths.reduce((p: string, c: string) => p + c) }`
  }
);

// Usage

<Language paths={['zh-CN', 'zh-CN/home']}>
      { (messages) => {
          console.log(messages)
        }}
</Language>
```

## Pitch

Client side rendering is supported, but server-side rendering is not supported due to `@loadable/babel-plugin` compilation problem

**Comment by kaysonwu** [comment]
I am preparing PR for this. Welcome to discuss!

**Comment by theKashey** [comment]
Server side rendering would be not supported due to custom logic in the import. Please check #483

**Comment by kaysonwu** [comment]
This writing is very flexible, but it needs to be combined with a powerful babel plugin

**Comment by kaysonwu** [comment]
Hi, @theKashey !  I want to ask you, @ loadable/components does not support typescript? There are always some strange mistakes in SSR

**Comment by kaysonwu** [comment]
Strange compilation results, seem to be disturbed by `ts-loader`
![Strange compilation](https://user-images.githubusercontent.com/14865584/77442956-b5bb0780-6e25-11ea-9957-3d276b3e14c9.png)
