### ISSUE TITLE
How to handle error on the server？

### ISSUE THREAD

**Issue by kaysonwu** [gregberge/loadable-components#545]
## 💬 Questions and Help

Error Boundaries not support ssr

**Comment by theKashey** [comment]
How `loadable` is bound to `ErrorBoundaries`?
On the server side, where you cannot fail to load statically available file, there is no error possible. Except you are trying to load some unexisting files, which is a major security breach. So don't allow it.

**Comment by kaysonwu** [comment]
I split the language files into public and page types. Page level is optional. Since I can't catch the error the whole page is crashing
