### ISSUE TITLE
loading handler while loading component

### ISSUE THREAD

**Issue by sayjeyhi** [gregberge/loadable-components#546]
Could we use some `loading` component to show while loading components?
like what `react-loadable` has:
```javascript
import Loading from './loading';

Loadable({
  loader: () => import(/* webpackChunkName: 'campaigns' */ './index'),
  loading: () => <Loading />,
});
```

**Comment by theKashey** [comment]
There are two ways:
- "Suspense" way
- "fallback"(not "loading") prop - https://loadable-components.com/docs/api-loadable-component/
