### ISSUE TITLE
Uncaught Error: Cannot find module

### ISSUE THREAD

**Issue by iamdcj** [gregberge/loadable-components#547]
## 💬 Questions and Help

First off, thanks for the great library. 

I am currently building a server-side rendered application, using Loadable Components `5.12.0` for 'component-level' code-splitting. The application contains a `componentSwitch` component which consumes an array of objects provided by a CMS - the component iterates over this array and returns a `<Component />` for each object using an `id` key from a designated directory;
```
const Component: LoadableComponent<any> = loadable(() =>
  import(`../presentation/${id}`)
)

return (
  <ErrorBoundary key={guid}>
    <Component {...data} />
  </ErrorBoundary>
)
```
This works just fine when the IDs returned from the server match-up to components in the application, but if the CMS returns an ID which doesn't have a matching component present in the application I get the following error;

`Uncaught Error: Cannot find module './SomeComponent'`

Initially I wrapped the Loadable import in a `try/catch`, but Loadable doesn't throw an error if the imported module cannot be found;

```
// console.log(SomeComponent) 
$$typeof: Symbol(react.forward_ref)
render: ƒ (props, ref)
preload: ƒ (props)
load: ƒ (props)
```
I attempted to hack around this by running the `load` method on the returned Loadable before returning the `<Component />` from the switcher:

``` 
try {
  Component.load();
} catch (error) {
  return null;
}
```

This hack gets shut of the original error(s), but results in a server/client mismatch warning; 

`Warning: Expected server HTML to contain a matching <main> in <div>`

Right now I am building an array[str] of IDs for each component present in the directory, e.g. `['Hero', 'Statement']` - I then check if the incoming `ID` is present in the array, if so create a Loadable, else return `null`. I am satisfied with this approach, however I would much prefer to check if the module exists in a more 'dynamic' fashion.

Any guidance will be very much appreciated.

**Comment by chuikoffru** [comment]
I faced with a similar case, and I don't know how I can fix it.

**Comment by iamdcj** [comment]
Please can this be re-opened.

**Comment by theKashey** [comment]
use `import { lazy } from '@loadable/component'` and `loadable` will throw an error __to a nearest Error boundary__, where you can react on it.

See https://loadable-components.com/docs/suspense/

**Comment by iamdcj** [comment]
> I am currently building a server-side rendered application.

**Comment by theKashey** [comment]
I see. Right now in case of "module not found" during SSR loadable would _think_ - "oh, that is client-side, let's call `import`!"

So what is expected behaviour - be able to "try" file first (like `Component.load();`) or fallback to ErrorComponent?

**Comment by iamdcj** [comment]
I appreciate the reopening of the ticket, but it feels like the opening comment has been lost/ignored.

> fallback to ErrorComponent?
I'm not sure if 'ErrorComponent' refers to a boundary, but boundaries do not catch on the server-side. If it was a client-side only solution this report wouldn't exist.

> be able to "try" file first (like Component.load();) 

So the opening comment documents the issue, and the above scenario clearly;

> Initially I wrapped the Loadable import in a try/catch, but Loadable doesn't throw an error if the imported module cannot be found;

> I attempted to hack around this by running the load method on the returned Loadable before returning the <Component /> from the switcher:

`
try {
  Component.load();
} catch (error) {
  return null;
}
`
> This hack gets shut of the original error(s), but results in a server/client mismatch warning;

`Warning: Expected server HTML to contain a matching <main> in <div>`

I liked this approached, it allowed me to dynamically check a component existed in the codebase without maintain an array of component IDs, however the server/client mismatch could not be ignored.

I am no longer engineering the application which prompted me to issue this ticket, but others seem to be having similar issues. I can only really comment on what I wanted at the time, and that is the ability to have a component switch which loads a component using an API provided key, for example;

`const someComponent = loadable(() =>
  import(`../presentation/${id}`)
`

If the API provided key attempts to load a component from a directory which does not exist, then it is caught on the server and we simply `return null`.

Again, It wasn't a hardship to maintain an array of known components, e.g. ['Hero', 'Statement']` - this approached allowed me to check the incoming ID from the API existed in the application, and thus prevent any of the reported issues.

I didn't have the time to fork and figure out a solution back when I reported the issue, and I don't see me using loadable-components on the server any time soon. I will close this again, and let others report their specific issue.
