### ISSUE TITLE
Error of "Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`" is hard to get rid of

### ISSUE THREAD

**Issue by williamku** [gregberge/loadable-components#548]
I am working on a React project with Server-Side-Rendering capability.   I noticed that this issue were mentioned by several bug reports and all of them were "closed".  First of all I followed all the listed "solutions" from those threads and basically with no success.    I have struggled with this issue for many weeks.   The worst of it is its "unpredictability" aspect of it.  It would suddenly show up - then when I backtracked or removed previous code change, the error would remain.  Then I 
 would tried backtracking even more steps of previous changes.  At some point, the error would disappear. Naturally I would make a note in my code commit so I can go back to.  Then when the next time the error happened and I went back to that specific code commit, the error would still remain!   This drove me completely nuts.  I cannot make any significant code progress because erratic and sudden appearance of it as well as there isn't a sure way to prevent it.    I am very surprised (and disappointed) that the owner of this library cannot completely resolve this issue.  Or provide some useful clues as to how or what someone has done to cause it and indicated that specific reason through the error message.

**Comment by gregberge** [comment]
Hello @williamku I agree we should be more specific and explain what is exactly the problem.
