### ISSUE TITLE
Changes not working on Server Side.

### ISSUE THREAD

**Issue by AlaguSelvan** [gregberge/loadable-components#550]
I'm using `@loadable/component` and `@loadable/server`, Whenever My Client-side code is changed, It Works fine on the client-side, But if I Hard Reload the page It returns to its old state, Then after the client is loaded it shows new Code.

![Issue](https://user-images.githubusercontent.com/34230909/78959514-cd261000-7b08-11ea-927d-4a437d216a51.gif)

[My Boilerplate](https://github.com/AlaguSelvan/typescript-react-ssr)

Steps to Reproduce:-
- yarn start 

Please let me know if you can help clarify this in any way.
Thank You!

**Comment by theKashey** [comment]
Usually hot module replacement is not working on the server side out of the box - you have to configure it one way or another.
In other words - you are changing you code, client bundle is update, but server is still in the past.

**Comment by AlaguSelvan** [comment]
@theKashey Do you have any examples or implementations with that, If so can you share me that.

Thank you.

**Comment by theKashey** [comment]
🤷‍♂️ https://github.com/gregberge/loadable-components/tree/master/examples/razzle

**Comment by AlaguSelvan** [comment]
@theKashey any other way to use without Razzle.

**Comment by theKashey** [comment]
Sure, but you have to do what Razzle does - run two dev servers, one for server, and one for the client. That's the easiest way to do it.
You can just copy Razzle scripts and modify them a bit, or read Rezzle's readme to get idea how it works.

**Comment by mikestopcontinues** [comment]
@theKashey Why is this Razzle example different from the one they provide? I see that theirs uses an older API, but there seems to be more going on: 
https://github.com/jaredpalmer/razzle/tree/master/examples/with-loadable-components

**Comment by mikestopcontinues** [comment]
Scratch that, it's not that different and just more complete. :)

**Comment by AlaguSelvan** [comment]
@theKashey Is there any other way without using razzle, like using Webpack or flush-chunks, I want to avoid integrating more tools for my codebase.

**Comment by theKashey** [comment]
There is no difference between "frontend hot reloading", and "server-side hot reloading", however you don't have "webpack-dev-server" for a server.
Running two webpack build and "merging" them via express server for example (basically what razzle does), is the only solution I know.

**Comment by 7rulnik** [comment]
@AlaguSelvan https://github.com/60frames/webpack-hot-server-middleware
