### ISSUE TITLE
Warning: Did not expect server HTML to contain a <div> in <div>.

### ISSUE THREAD

**Issue by Yanchenyu** [gregberge/loadable-components#557]
## 💬 Questions and Help

Hi, thank you for this remarkable library :)

here is my question:

It doesn't happen every time，just sometimes

![image](https://user-images.githubusercontent.com/17396502/79713675-13495380-8301-11ea-954f-180b252b950d.png)

I found out there was a similar problem before

https://github.com/gregberge/loadable-components/issues/423

and i print console.log

![image](https://user-images.githubusercontent.com/17396502/79713711-35db6c80-8301-11ea-8a70-97fc9070aa81.png)

![image](https://user-images.githubusercontent.com/17396502/79713723-425fc500-8301-11ea-8337-6b709fcb58ac.png)

and you can see there's nothing in the root tag, so the warning show .

however , this is not normal, because most of the time like this:

![image](https://user-images.githubusercontent.com/17396502/79713878-a6828900-8301-11ea-877b-49d551378f01.png)

and there is no warning, correct

i notice the componentdidmount console time is different

so i don't know why it is happen, please help me to resolve it ! thank you so much !!

by the way, I found a strange phenomenon:

I switch network to slow 3G, the warning will never arise

![image](https://user-images.githubusercontent.com/17396502/79714051-3a545500-8302-11ea-9f7f-a6e4a8f2ebf2.png)

and this warning usually appears when the load is very fast,

I hope this detail can help you find the problem more easily, 

thank you so much !!!

**Comment by Yanchenyu** [comment]
I submitted an issue three days ago,

https://github.com/gregberge/loadable-components/issues/555

I found that the problem is the same as the one submitted today, because when this warning appears, the page will automatically add resources to the head tag.

![image](https://user-images.githubusercontent.com/17396502/79714347-12b1bc80-8303-11ea-9823-f63c32c17c3e.png)

![image](https://user-images.githubusercontent.com/17396502/79714372-1e9d7e80-8303-11ea-83d6-7370ba9a73c7.png)

I guess it is because there is no content under the root tag, so the resources of the current page are loaded automatically.

please help me !!! thank you so much !!!

**Comment by Yanchenyu** [comment]
I changed the code

![image](https://user-images.githubusercontent.com/17396502/79722100-0e42cf00-8316-11ea-847f-9fb3ca73eb73.png)

and the warning never show again

so i guess the loadableReady didn't wait for the JS resource of the current page to load and parse, so it ran it directly, so sometimes ReactDOM.hydrate just null, no content

**Comment by theKashey** [comment]
> loadableReady didn't wait for the JS resource of the current page to load and parse

`loadableReady` waits only for the chunks, the rest if on you. However, it is not waiting for anything because there is nothing to wait for
![image](https://user-images.githubusercontent.com/582410/79812270-c8404680-83bb-11ea-9a3c-5e55fb79d771.png)
And it's empty on all examples provided, probably it is a root cause.

**Comment by Yanchenyu** [comment]
@theKashey Thank you for your answer！How to configure this script tag's value ?
![image](https://user-images.githubusercontent.com/17396502/80078188-22d6cf80-8581-11ea-9945-7c158621b708.png)

**Comment by theKashey** [comment]
Something is wrong with your server settings.
This scripts is added by `.getScriptTags`, so something wrong is with `extractor.collectChunks`

**Comment by Yanchenyu** [comment]
@theKashey HI
I checked the source code and debug,
![image](https://user-images.githubusercontent.com/17396502/80339694-cb42a780-8891-11ea-9308-7ada3bb9b125.png)

i console log ```this.chunks```
It's an empty array []

The only way to assign a value is ```addChunk```

![image](https://user-images.githubusercontent.com/17396502/80339842-12c93380-8892-11ea-8a1e-e2e37fefe374.png)

however when i console log here ```chunk```
it console log ```test1```,   ( It is the current SSR first screen page )

and then, I found out it was the order of code execution,

the getRequiredChunksScriptContent function execution takes precedence over the addChunk function execution,

so i dont know why ? 
I hope you can provide more help, thank you !

**Comment by theKashey** [comment]
So I need to see your server side code. What if you are using `renderToNodeStream` and not waiting for that stream properly?
So you "render", you "extract", but the real rendering has not been even started yet.

**Comment by Yanchenyu** [comment]
hi, here is server side code

```
const path = require('path');
const React = require('react');
const Controller = require('../core/baseController');
const { StaticRouter } = require('react-router-dom');
const ReactDOMServer = require('react-dom/server');
const { ChunkExtractor } = require('@loadable/server');

const nodeStats = path.resolve(__dirname, '../../dist/server/loadable-stats.json');
const webStats = path.resolve(__dirname, '../../dist/client/loadable-stats.json');

class TestController extends Controller {
    async index() {

        const arr = this.ctx.url.split('/m/flights/');
        let location;
        if (arr.length > 1) {
            location = arr[1].split('/')[0];
        }

        const nodeExtractor = new ChunkExtractor({ 
            statsFile: nodeStats,
            entrypoints: ["index", location],
            publicPath: 'https://webresource.english.c-ctrip.com/ares2/ibu/booking-flight-h5/1.0.1/default/'
        });
        const { default: App } = nodeExtractor.requireEntrypoint();
    
        const webExtractor = new ChunkExtractor({ 
            statsFile: webStats,
            entrypoints: ["index", location],
            publicPath: 'https://webresource.english.c-ctrip.com/ares2/ibu/booking-flight-h5/1.0.1/default/'
        });

        const staticRouterComponent = React.createElement(
            StaticRouter,
            {
                location: this.ctx.url,
                context: this.ctx.context || {}
            },
            React.createElement(App)
        );
        
        const jsx = webExtractor.collectChunks(staticRouterComponent);

        const resources = {
            scripts: webExtractor.getScriptTags(),
            styles: webExtractor.getStyleTags(),
            links: webExtractor.getLinkTags()
        };

        await this.ctx.render(location, {
            locale: 'zh',
            context: this.ctx.context || {},
            resources,
            renderHtml: ReactDOMServer.renderToString(jsx)
        });
    }

}

module.exports = TestController;

```

I mentioned an issue a few days ago. It has a lot of codes

https://github.com/gregberge/loadable-components/issues/555

**Comment by theKashey** [comment]
```js
        const resources = {
            scripts: webExtractor.getScriptTags(),
            styles: webExtractor.getStyleTags(),
            links: webExtractor.getLinkTags()
        };

        await this.ctx.render(location, {
            locale: 'zh',
            context: this.ctx.context || {},
            resources,
            renderHtml: ReactDOMServer.renderToString(jsx)
        });
```
Probably the most common mistake - first get scripts, and then render App.
That's not gonna work. You have to render your app first, and then you can get information about what was needed to do it.
Once again - move `ReactDOMServer.renderToString(jsx)` above `resources`

**Comment by Yanchenyu** [comment]
Thank you very much. The problem has been solved. Thank you ！！ @theKashey
