### ISSUE TITLE
Question What is the difference between `lazy` and `loadable`

### ISSUE THREAD

**Issue by kije** [gregberge/loadable-components#559]
Hi

I'm wondering what the difference between [`lazy()`](https://loadable-components.com/docs/suspense/) and [`loadable()`](https://loadable-components.com/docs/component-splitting/) is.

In other words, what is the difference in behaviour between these two code snippets:
### `loadable()`
```es6
import loadable from '@loadable/component'
const OtherComponent = loadable(() => import('./OtherComponent'))
function MyComponent() {
  return (
    <div>
      <OtherComponent />
    </div>
  )
}
```

### `lazy()`
```es6
import React, { Suspense } from 'react'
import { lazy } from '@loadable/component'
const OtherComponent = lazy(() => import('./OtherComponent'))
function MyComponent() {
  return (
    <div>
      <Suspense fallback={<div>Loading...</div>}>
        <OtherComponent />
      </Suspense>
    </div>
  )
}
```

The documentation doesn't seem to explain this clearly

**Comment by theKashey** [comment]
SSR and full dynamic import - https://loadable-components.com/docs/loadable-vs-react-lazy/
