### ISSUE TITLE
What is __LOADABLE_REQUIRED_CHUNKS__ script tag is for? Is it important?

### ISSUE THREAD

**Issue by vietsonhs** [gregberge/loadable-components#561]
Hello, I am trying to use loadable-component for SSR and I realized that one of the script tag in `extractor.getScriptTags()` is `<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[0,2,1,5]</script>`.  When I include this tag in the HTML, it seems to break my css.

I am wondering what is the usage for this script tag? Is it important to be injected into the HTML for rendering?

**Comment by theKashey** [comment]
This tag hold information about which `chunks` has to be loaded before application might considered "ready", and you can hydrate your tree.
So it is VERY important.

**Comment by vietsonhs** [comment]
@theKashey Thank you for the prompt reply. I will try to figure out the reason why my Material UI CSS break with this tag included. I will close the question.
