### ISSUE TITLE
without any Router, dynamic loading the component base address not start from '/' will cause errors

### ISSUE THREAD

**Issue by X-neuron** [gregberge/loadable-components#564]
## 🐛 Bug Report

       without any Router, dynamic loading the component seems using the last base URL, it cause the address errors to link the code splitting component 
       

## To Reproduce

    using a gif to explain it : two component, if we navigate the path start from '/'
   component: form1    path: '/test1'  
   component: form2    path:'/test2'
   .... then  it work fine.
   but if we navigate the path start from '/ab'
  then: 
  component: form1    path: '/ab/test1'  
  component: form2    path:'/ab/test2'
  then: when start from web base address.  the first loading component work fine. the second loading error.   because it start from 'website/ab/test1/codesplit address
 
 we using this way to dynamic load component without Routes
 
```
import React from 'react';
import _ from 'lodash';
import memoized from 'nano-memoize';
import MicroApp from '@/components/MicroApp'
import Pageloading from '@/components/PageLoading'
import loadable from '@loadable/component';

const Dashboard = loadable(() => import('../pages/dashboard'), {
  fallback: <Pageloading tip="组件加载中..." />,
});
const Test1 = loadable(() => import('../pages/test1'), {
  fallback: <Pageloading tip="组件加载中..." />,
});
const Test2 = loadable(() => import('../pages/test2'), {
  fallback: <Pageloading tip="组件加载中..." />,
});
const Test3 = loadable(() => import('../pages/test3'), {
  fallback: <Pageloading tip="组件加载中..." />,
});

const getPage = memoized((apageStr) => {
  const pageStr = _.upperFirst(apageStr);
  switch (pageStr) {
    case 'Test3':
      return <Test3 />
    case 'Test2':
      return <Test2 />
    case 'Dashboard':
      return <Dashboard />
    case 'Test1':
      return <Test1 />
    // 默认没有，则用微端的方式加载试试。
    default:
      return <MicroApp entry={apageStr} />
  }
});
export default getPage;
```
<a href="https://sm.ms/image/E7ZPMCN4mVyoBqb" target="_blank"><img src="https://i.loli.net/2020/04/29/E7ZPMCN4mVyoBqb.gif" ></a>

**Comment by theKashey** [comment]
Check your `publicPath` configuration. It is webpack who loads the script chunk on request, and this is webpack setting.

**Comment by X-neuron** [comment]
> Check your `publicPath` configuration. It is webpack who loads the script chunk on request, and this is webpack setting.

no config with this; i'm checking now,thanks a lot！soon feedback

**Comment by X-neuron** [comment]
> Check your `publicPath` configuration. It is webpack who loads the script chunk on request, and this is webpack setting.

it works perfect now. thanks a lot!
