### ISSUE TITLE
SVGR

### ISSUE THREAD

**Issue by trumbitta** [gregberge/loadable-components#569]
Any chance of getting loadable-components work with icons imported via SVGR?

**Comment by trumbitta** [comment]
Aaaand yes sir it works.

```tsx
import React from 'react';

import loadable from '@loadable/component';

const IconDownload = loadable.lib(() => import('./icon-download.svg'));

export const App: React.FC = () => (
  <main>
    Hellooo
    <IconDownload>{({ ReactComponent }) => <ReactComponent />}</IconDownload>
  </main>
);
```

**Comment by theKashey** [comment]
Why not keep it `svg` in this case?

**Comment by trumbitta** [comment]
> Why not keep it `svg` in this case?

Care to elaborate with a code example?

Also my final goal is to pass the path or icon name to a factory. So far no luck with that, albeit it works with “normal” components that aren’t SVG files loaded by svgr.

**Comment by theKashey** [comment]
I mean in majority of cases `svg` could be kept as a external "raw" `.svg` file, and displayed via `img`/`background`

**Comment by trumbitta** [comment]
> I mean in majority of cases `svg` could be kept as a external "raw" `.svg` file, and displayed via `img`/`background`

True, but I’m building a showcase for icons that are used via svgr and I want to stay as close to that situation as possible if I can.

**Comment by InsOpDe** [comment]
This is important for us, too
