### ISSUE TITLE
Creating reusable vendor chunks with loadable across projects

### ISSUE THREAD

**Issue by domtronn** [gregberge/loadable-components#570]
## 💬 Questions and Help

I am looking into making a common vendor bundle for a micro front end project, where all projects use the same versions of React & ReactDOM. I am using Webpack's `splitChunks.cacheGroups`  feature to pick these modules out for their own chunk, i.e.

```js
module.exports = {
  optimization: {
    moduleIds: 'hashed',
    minimize: false,
    minimizer: [],
    splitChunks: {
      cacheGroups: {
        ufReactCore: {
          priority: 50,
          test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
          chunks: 'all',
          name: `vendor~core`
        },
      },
    },
  }
}
```

Is present in both projects.

However, when I build both projects I end up with different hashes for the `vendor~core.[contenthash].js` output file name. When I diff the two built bundles, the difference looks like this

```diff
-(window["__LOADABLE_LOADED_CHUNKS__"] = window["__LOADABLE_LOADED_CHUNKS__"] || []).push([[2],{
+(window["__LOADABLE_LOADED_CHUNKS__"] = window["__LOADABLE_LOADED_CHUNKS__"] || []).push([[8],{
```

Where the only difference is the `push([[8],` vs. `push([[2],`.

I couldn't find any documentation that explains how loadable decides these magic numbers, but my intuition suggests it's for the SSR `stats.json` or order load?

---

I was wondering if you could please,

1. Explain what these two different numbers do?
2. Provide any guidance or support to achieve the same reusable hashes across projects?
3. Suggest how I could ensure these numbers are the same across builds?

If there is any other context you need, please let me know :) 

Thanks in advance!

**Comment by theKashey** [comment]
This is not up to loadable to decide - that's `modulesId` of webpack.
You need `named` or `hashed` -> `optimization.moduleIds: "hashed"` to make these "numbers" stable from build to build.
Default settings are not cache friendly.

**Comment by domtronn** [comment]
I have the `moduleIds: ‘hashed’` Option set in the cache groups which produces cache friendly predictable builds with something like React lazy & suspense. However, it’s only when using `@loadable/webpack-plugin` (For SSRing) that the content hashes seem to change and the loaded chunk ids are different.

It does look like those ids are related to the module ids as you say, as they seem linked to the number of modules produced by the web pack build (one project generates 3, the other 8). Is there a setting I’m missing that tells the loadable we pack plugin to use the hashed ids? And would I see something like `5b03ea5f` in place of the `8` & `2`?

**Comment by theKashey** [comment]
Yes - it should be like a hash(`5b03ea5f`), not a number. So please check your settings.
