### ISSUE TITLE
getStyleTags() seems to work fine with renderToNodeStream when using prepass

### ISSUE THREAD

**Issue by 675r** [gregberge/loadable-components#572]
I'm building an application using loadable-components and server side rendering. The server render is making use `renderToNodeStream` to stream the response to the client.

According to the docs [here](https://loadable-components.com/docs/server-side-rendering/#streaming-rendering), you cannot use `getStyleTags()` when streaming the response.

However, i notice when using prepass ([react-ssr-prepass](https://github.com/FormidableLabs/react-ssr-prepass)) to fetch my data i'm then able to use the chunk extractor to get my styletags via `.getStyleTags()` and append them onto the end of the head.

Simplified example. This appears to function correctly:

```javascript
const streamRequest = async (req, res) => {

    const serverModule = new ChunkExtractor({
        statsFile: path.resolve('stats-server.json')
    }).requireEntrypoint();

    res.write(`<!doctype html><html><head>`);

    const clientExtractor = new ChunkExtractor({
        statsFile: path.resolve('stats-client.json'),
    });

    const urqlClient = getClient(true);

    const jsx = serverModule.render(
        urqlClient
    );

    const chunks = clientExtractor.collectChunks(jsx);

    // fetch data
    await prepass(chunks);

    res.write(`${clientExtractor.getStyleTags()}</head><body><div id="root">`);

    // stream
    const nodeStream = renderToNodeStream(chunks);

    nodeStream.pipe(res, {end: false});
    nodeStream.on("end", () => {
        res.write(
            `</div>
             	<!-- populate data etc here -->
                ${clientExtractor.getScriptTags()}
            </body>
            </html>`
        );
        res.end();
    });
};
```

So my question becomes, is this valid and are there any issues with doing this? it seems to work just fine.

I appreciate this is linked to react-ssr-prepass too, but thought it make more sense here.

**Comment by theKashey** [comment]
Yes, with prepass you should be more or less safe to include styles in the head.
However, with prepass there is not much sense to use `renderToNodeStream` - it's an optimisation technique and `prepass` already consumed any time you can "optimize" that way.

**Comment by 675r** [comment]
> Yes, with prepass you should be more or less safe to include styles in the head.
> However, with prepass there is not much sense to use `renderToNodeStream` - it's an optimisation technique and `prepass` already consumed any time you can "optimize" that way.

Thank you for clarifying, that was roughly my understanding. There is still the benefit in terms of lowering the TTFB, by at least sending something straight away (head with meta info etc).

**Comment by theKashey** [comment]
Yep. And all other optimisation must be picked based on how fast or slow prepass is.
