### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by hieusmiths** [gregberge/loadable-components#574]
import React from 'react';
import { Radio } from 'antd';

const SelectMortgage = () => (
	<Radio.Group>
		<Radio value={1}>Có</Radio>
		<Radio value={0}>Không</Radio>
	</Radio.Group>
);

export default SelectMortgage;

When you import will have a bug Object(...) is not a function.

Or when export with syntax export default { Option, Select };

Import X from 'above';

const { Option } = x;

Same the error.

I fixed it by don't using it.

I hope team can check it.
Thank so much Team.

**Comment by hieusmiths** [comment]
Yes, thank for team.

import { useEffect, useRef } from 'react';
const usePrevious = (value) => {
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  });
  return ref.current;
};

export default usePrevious;

This above example will throw same the error.

**Comment by theKashey** [comment]
I do not see any error here, especially nothing related to loadable.

**Comment by hieusmiths** [comment]
> I do not see any error here, especially nothing related to loadable.

**Comment by hieusmiths** [comment]
> I do not see any error here, especially nothing related to loadable.

Okay, i will spend free time for create demo with codesanbox
Thank you.
