### ISSUE TITLE
Loadable Components with react-redux connect error

### ISSUE THREAD

**Issue by zxf4399** [gregberge/loadable-components#577]
## 💬 Questions and Help

if i loadable(() => import("pages/redux/Count"), options),
and in Count.tsx
i use connect(mapStateToProps)(Count)
typescript submit error such as 
Type 'Promise<typeof import("/Users/zhengxianfeng/zxf4399/github/learn-react/src/pages/redux/Count")>' is not assignable to type 'Promise<DefaultComponent<{}>>'.

**Comment by theKashey** [comment]
The issue is on the next line.
```
Type 'Promise<typeof import("/Users/zhengxianfeng/zxf4399/github/learn-react/src/pages/redux/Count")>' is not assignable to type 'Promise<DefaultComponent<{}>>
>> HERE IS WHY
```
Probably you have to export default something, and so on. And that's a normal TypeScript case, which has nothing with Redux or Loadable.
If you want help please provide enough information for us to understand the whole picture. Please value our time over your time.
