### ISSUE TITLE
How to use @loadable/component with classes which do not have defaut exports

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [gregberge/loadable-components#579]
sample.js
` export const test1 => <h2>Hello World</h2>
  export const test2 => <h2>Hello World2</h2>
`
If I wish to use sample.js in App.js & wish to do code splitting using loadable components then what should be the proper approach.

**Comment by theKashey** [comment]
That's not so easy - please refer to one of the attempts to resolve it - https://github.com/gregberge/loadable-components/pull/483

But yes - look for "named imports".
