### ISSUE TITLE
Giving me Invalid character, SCTIPT1014 when loading in IE(10 and 11) in lodable/component while in chrome working fine

### ISSUE THREAD

**Issue by jainamit9928** [gregberge/loadable-components#580]
## 👉 [Please follow one of these issue templates](https://github.com/gregberge/loadable-components/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by theKashey** [comment]
This is not properly created issue. Please provide more detail.
