### ISSUE TITLE
 loadable/component  is not Working on IE(10 and 11)

### ISSUE THREAD

**Issue by dineshgurumoorthy** [gregberge/loadable-components#581]
## 🐛 Bug Report

**Invalid character SCTIPT1014 is thrown when loading in IE(10 and 11) in loadable/component while in chrome it is working fine.

## To Reproduce
**Please find the below link to reproduce
** https://github.com/dineshgurumoorthy/reactcodesplitting
**Run the localhost in IE

**modulechunk component is rendered initially in root/
**routechunk component is rendered when hitting /lazy

## Expected behavior
**The website should open without issues

## Link to repl or repo (highly encouraged)
** https://github.com/dineshgurumoorthy/reactcodesplitting

Attached Image is the console 
![image](https://user-images.githubusercontent.com/61574483/83864726-c69bc980-a742-11ea-85f5-3aa7368fbec2.png)

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

We ain't see any results since we see the site is not initiating..
```bash

```

**Comment by OZZlE** [comment]
@dineshgurumoorthy We seem to have the same issue now, however it was working fine before we 1) updated from webpack 3 to 4 (probably unrelated?) and 2) Followed this https://web.dev/codelab-serve-modern-code/ to only transpile modules for older browsers.

It seems like after following above guide only the main bundle is transpiled but the chunks/lazy loaded components aren't transpiled at all and that's probably why IE11 and below doesn't work?

**Comment by theKashey** [comment]
CRA ("react-scripts") are compiling everything down to IE9, and produced code should work.
As well as `loadable-component` are not quite CRA friendly - there is no reasons to use them without SSR or at least custom babel configuration.
Consider using `React.lazy`, but it would not resolve your IE issue.

However, I am really not able to help you with this issue. Bundle generation is not something we control.

**Comment by OZZlE** [comment]
We don't use Create React App (CRA) if that's what you mean?

> there is no reasons to use them without SSR

We only load required js for the entry page and then if you switch to another page (SPA) that requires other js we lazy load it using this lib. So I think it is very useful.. Also I would do SSR if it was an easy step in our current setup but currently it's a lot of work and also some risk that stakeholders would have to agree upon.

> or at least custom babel configuration.

Would be super grateful for any support but I understand that this falls outside this lib's responsibility perhaps. But maybe the community can come together and help :)

**Comment by theKashey** [comment]
> We don't use Create React App (CRA) if that's what you mean?

The repo in the issue - https://github.com/dineshgurumoorthy/reactcodesplitting is CRA based.

> lazy load it using this lib. So I think it is very useful

It was somewhere in a readme that "if you don't need all extra stuff provided my loadable-components, you probably need React.lazy".

> But maybe the community can come together and help :)

CRA "officially" does not support SSR. And other platforms (Next, Gatsby) might enforce you to use their own code splitting solutions.
There is a good way to "support" loadable on CRA - expose a babel macro, but no one ever asked for it 🤷‍♂️

**Comment by OZZlE** [comment]
I'm not the reporter of this case, just experiencing the same :) I could try React.lazy but as you already mentioned it probably won't help :/ 

We do not use Create React App (CRA?) but the author of this case does :)

**Comment by dineshgurumoorthy** [comment]
Hi Anton,

This App was just created to convey the message, however we have configured
our project with webpack

**Comment by tomtom94** [comment]
Hello I have a React SSR boilerplate ready for you https://github.com/tomtom94/react-easy-ssr give me a star guys :)

But I confirm, in `targets` from babel.config.js right here https://github.com/tomtom94/react-easy-ssr/blob/master/babel.config.js#L12

When I put `{ ie: '11' }`

```
targets: web ? { ie: '11' } : { node: process.versions.node }, // https://babeljs.io/docs/en/options#targets
```

Arrow functions in bundles js are yet present, probably coming from loadable-component.
