### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by kaysonwu** [gregberge/loadable-components#584]
## 💬 Questions and Help

It's more than 3 months since the last version, waiting for a new release

**Comment by gregberge** [comment]
Hello, I am dad now, it means no time in week-end. And the project don’t have sufficient sponsor to be able to work on it during the week.

@theKashey are you up to take the lead completely?

**Comment by theKashey** [comment]
I am a dad for 13 years already, so my weekends are more or less free. I could cover you @gregberge while you onboarding to a new chapter.

**Comment by gregberge** [comment]
I will give you rights to publish.

**Comment by kaysonwu** [comment]
That's good news!

**Comment by gregberge** [comment]
@theKashey thanks for covering me! I sent you the invitation to publish. Feel free to take decision for the project. I could eventually come back one day!

I don't have notifications except for mentioning, I have time to give my opinion about some critical subject, so feel free to @ me.

**Comment by kaysonwu** [comment]
@theKashey Are you ready to release?

**Comment by theKashey** [comment]
Planned for tomorrow.

**Comment by themre** [comment]
Thanks for publishing new version! This can be closed now.
