### ISSUE TITLE
SSR with wrapped import

### ISSUE THREAD

**Issue by vaseker** [gregberge/loadable-components#585]
## 💬 Questions and Help

Hello!
Im trying to add SSR support for existing project with async components. Our components should be loaded with some delays like described in https://loadable-components.com/docs/delay/: delay before starting network request (delayed import execution) and minimal time for `fallback` show.

While it works fine in CSR, SSR breaks with error `loadable: SSR requires @loadable/babel-plugin, please install it` despite `@loadable/babel-plugin` usage.

To avoid this problem we introduce env param which doesn't wrap loadFn with delay logic for SSR but it looks dirty.

Complete example of our work-in-progress loader is

```ts
// lazy.ts
import baseLoadable, { DefaultComponent, LoadableComponent, Options } from '@loadable/component';

const LAZY_DEFERRED_SLEEP = 50;
const LAZY_DEFERRED_DELAY = 500;

type LazyOptions = {
    sleep?: number;
    delay?: number;
};

declare function loadableFunc<T>(
    loadFn: (props: T) => Promise<DefaultComponent<T>>,
    options?: Options<T> & LazyOptions
): LoadableComponent<T>;

type LoadableFunction = typeof loadableFunc;

const isSSR = process.env.REACT_APP_TYPE === 'ssr';

export const loadable: LoadableFunction = isSSR ? baseLoadable : (loadFn, options = {}) => {
    const { sleep = LAZY_DEFERRED_SLEEP, delay = LAZY_DEFERRED_DELAY } = options;

    type LoadFn = typeof loadFn;

    let loader = loadFn;

    if (sleep) {
        let sleepCallback = loader;

        loader = props => new Promise(resolve =>
            setTimeout(() => resolve(sleepCallback(props)), sleep));
    }

    if (delay) {
        let delayCallback = loader;

        loader = props => Promise.all<ReturnType<LoadFn>, void>([
            delayCallback(props),
            new Promise<void>(resolve => setTimeout(resolve, delay))
        ]).then(([module]) => module);
    }

    return baseLoadable(loader, options);
};
```

And usage is 
```ts
// Component.tsx
import { loadable } from '../../helpers/lazy';

const Component = loadable(() => import(
    /* webpackChunkName: "details-screen", webpackPrefetch: true */
    './Component'
));

```

If no `process.env.REACT_APP_TYPE=ssr` set we getting error `loadable: SSR requires @loadable/babel-plugin, please install it` in SSR execution.

So the question is: how to correct wrap `import` statement for `@loadable/component` in SSR environment?

Sorry for my English.

Have a nice day!

**Comment by theKashey** [comment]
Hello Dmitry, long time no see. The wind map is just 👍 
- `sleep` and `delay` in your case are doing the same thing - delaying promise resolution. While `sleep` can defer script loading, `delay` will not defer spinner display. If you need to defer it(especially if you use Suspense) - move that "delay" to the Spinner itself.

> loadable: SSR requires @loadable/babel-plugin, please install it

Is a very common issue. And the simple - https://github.com/gregberge/loadable-components/blob/6ea00c4c2bdaaf6c603def69ea45c57a6a0d01c9/packages/component/src/createLoadable.js#L59 - basically babel-plugin didn't do the job.

In short - it transforms any `loadable`, as [explained here](https://loadable-components.com/docs/babel-plugin/#loadable-detection), and the code is straight forward - if you call `loadable` - [transform](https://github.com/gregberge/loadable-components/blob/6ea00c4c2bdaaf6c603def69ea45c57a6a0d01c9/packages/babel-plugin/src/index.js#L39)!
Something got broken in a few lines.

### What could go wrong
- it's not "loadable" (babel rewrote imports to CJS)
- there is no import inside (babel did node-import)
- that's all

And everything should never happen, as long as `babel-plugin` is set to perform transformation before any other operation, especially node-import.

However, try to (edit it directly in node_modules) add some debug [here](https://github.com/gregberge/loadable-components/blob/6ea00c4c2bdaaf6c603def69ea45c57a6a0d01c9/packages/babel-plugin/src/index.js#L78) and come back with the results.

**Comment by vaseker** [comment]
Hello Anton, nice to see you again! Thanks but its time to make remaster of these maps :)

In our tests mentioned `sleep` and `delay` options do expected job. Maybe I just broke the code with ssr edits, its fine at this stage)

Yep Im currently see the problem in code transform stage too and trying to modify my code to match [test cases](https://github.com/gregberge/loadable-components/blob/master/packages/babel-plugin/src/index.test.js) but not tried to deep dive into plugin logic yet. Also it looks like our CreateReactApp-based webpack config made incompatible work before `babel-plugin` come into.

Thanks for the detailed answer!
