### ISSUE TITLE
Hydration of app in 5.13.0

### ISSUE THREAD

**Issue by yashok111** [gregberge/loadable-components#587]
## 🐛 Bug Report

I just updated to the latest version of loadable-components in my project. On server app renders exactly as expected. When hydration is complete it looks like the app rendered two times. Issues happen only with ReactDOM.hydrate, if I just ReactDOM.render the app everything works as expected. On 5.12.0 hydrate works perfectly.

## To Reproduce

I have tried to create a small repo but everything seems to work fine in it

## Expected behavior

Same HTML on the server and on the client.

## Link to repl or repo (highly encouraged)

See "To Reproduce".

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 4.53 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 13.12.0 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.4 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: 5.13.0 => 5.13.0
 - @loadable/component: 5.13.0 => 5.13.0
 - @loadable/server: 5.13.0 => 5.13.0
 - @loadable/webpack-plugin: 5.13.0 => 5.13.0
```

**Comment by theKashey** [comment]
> it looks like the app rendered two times

Why do you think it renders twice?

**Comment by yashok111** [comment]
It's how HTML looks like on server:
<img width="589" alt="Screenshot 2020-07-01 at 12 02 06" src="https://user-images.githubusercontent.com/19926392/86219205-edf38400-bb92-11ea-9882-27d7c15256a5.png">
It's after hydration:
<img width="589" alt="Screenshot 2020-07-01 at 12 02 45" src="https://user-images.githubusercontent.com/19926392/86219321-12e7f700-bb93-11ea-9198-335848539f16.png">

**Comment by clgeoio** [comment]
I can confirm this is occurring in my app too (with `server`, `component` and `babel-plugin` all at `5.13`. I only observe the issue when my bundle is built with `NODE_ENV=production`, I do not see this otherwise.

 If `loadable/component` and `loadable/server` are updated to `5.13` but `loadable/babel-plugin` remains at `5.12`, then this issue disappears. I am not sure if this is a red-herring, but worth checking in your environment @yashok111. 

I have seen such double ups in DOM elements when hydrate() has an SSR mismatch. Usually an error is shown, but with the production env these comments are stripped out.

**Comment by yashok111** [comment]
@clgeoio thank you for your suggestion. I have downgraded the `loadable/babel-plugin` to 5.12.0 and the issue is disappeared. I have checked `NODE_ENV=development` and there are no hydrate errors reported in the console.

**Comment by clgeoio** [comment]
Good to hear. 
I cannot be certain that downgrading `loadable/babel-plugin` with the others at `5.13` won't produce undesirable effects though.

**Comment by theKashey** [comment]
That's very interesting. Sounds like some problems with hydration resulting a broken state - that's possible if generated HTML does not match. 
However you are saying that no error with hydration are reported.

The other problem is that not matching babel version should not work as expected - some logic there got completely reversed.

**Comment by theKashey** [comment]
Actually babel-plugin could be downgraded without any consequences, however that will nullify a few fixes made in between.

Anyway - look like everything is about this line - https://github.com/gregberge/loadable-components/blob/master/packages/component/src/createLoadable.js#L108

Could you try to find it in your own code and add some logging around - I am interested in difference between 12 and 13 version in terms of what it will `loadSync`

**Comment by yashok111** [comment]
There are no hydrate errors with `loadable/babel-plugin` at `5.12` and others at `5.13`. If `loadable/babel-plugin` on `5.13` there are warnings in the console. 
<img width="606" alt="Screenshot 2020-07-01 at 13 38 58" src="https://user-images.githubusercontent.com/19926392/86229122-4ed58900-bba0-11ea-963f-9ae9f7b699ed.png">

**Comment by yashok111** [comment]
**5.13**:
```javascript
console.log('test');
        console.log('options.ssr !== false ===> ', options.ssr !== false);
        console.log('ctor.isReady && ctor.isReady(props) ===> ', ctor.isReady, ctor.isReady(props));
        console.log('ctor.chunkName && LOADABLE_SHARED.initialChunks[ctor.chunkName(props)]) ===> ', ctor.chunkName, LOADABLE_SHARED.initialChunks[ctor.chunkName(props)])
        console.log(options.ssr !== false && ( // is ready - was loaded in this session
          ctor.isReady && ctor.isReady(props) || // is ready - was loaded during SSR process
          ctor.chunkName && LOADABLE_SHARED.initialChunks[ctor.chunkName(props)]))
        if (options.ssr !== false && ( // is ready - was loaded in this session
        ctor.isReady && ctor.isReady(props) || // is ready - was loaded during SSR process
        ctor.chunkName && LOADABLE_SHARED.initialChunks[ctor.chunkName(props)])) {
          console.log('loadSync');
          _this.loadSync();
        }

        return _this;
```
<img width="940" alt="Screenshot 2020-07-01 at 14 31 19" src="https://user-images.githubusercontent.com/19926392/86234166-94498480-bba7-11ea-8155-e77b8a869b14.png">

looks like condition is always `false`.

**5.12**:

```javascript
console.log('test');
         console.log('options.ssr !== false ===> ', options.ssr !== false);
          console.log('ctor.isReady ===> ', ctor.isReady);
          console.log('ctor.isReady(props) ===> ', ctor.isReady(props));
          if (options.ssr !== false && ctor.isReady && ctor.isReady(props)) {
            console.log('loadSync')
            _this.loadSync();
          }

          return _this;
```

<img width="953" alt="Screenshot 2020-07-01 at 14 38 16" src="https://user-images.githubusercontent.com/19926392/86234839-94964f80-bba8-11ea-8cf0-64ddc395dbd3.png">

**Comment by theKashey** [comment]
Ok. In this case please try to find the difference between server output and result of `render` (not `hydrate`)
That is the difference? What should be three instead of `header`?

**Comment by theKashey** [comment]
@yashok111 yep, it all should be `false`, except the last condition. So what is `LOADABLE_SHARED.initialChunks` then?

**Comment by theKashey** [comment]
oof... `<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[0,1,2,6,7,8,9,12]</script>`, that's all internal numbers...

**Comment by theKashey** [comment]
Recovery plan:
- (server) expose used chunks names to fix the condition
- (loadable) allow unsafe loadSync if extra information is not known.

**Comment by yashok111** [comment]
**LOADABLE_SHARED.initialChunks:**

<img width="934" alt="Screenshot 2020-07-01 at 18 22 08" src="https://user-images.githubusercontent.com/19926392/86255409-1f3a7700-bbc8-11ea-8a5a-37d1daf87df8.png">

**Comment by Systerr** [comment]
Same problem for sample app https://github.com/gregberge/loadable-components/tree/master/examples/server-side-rendering
works well with "@loadable/babel-plugin": "5.12.0"

**Comment by theKashey** [comment]
client+server 5.13.1 should fix the problem.

**Comment by theKashey** [comment]
It would be awesome if someone will confirm that the issue got resolved.

**Comment by yashok111** [comment]
The issue is resolved. Thank you @theKashey for fast hotfix!
