### ISSUE TITLE
Option to exclude components from chunk-extraction

### ISSUE THREAD

**Issue by zeemawn** [gregberge/loadable-components#588]
## 🚀 Feature Proposal

Add possibility to exclude certain chunks from chunk extraction.

## Motivation

I'm currently implementing a simple partial hydration functionality in my SSRed app. Basically I check if we're in the browser-environment and if so, I just use `dangerouslySetInnerHTML={{ __html: '' }}` to keep the SSRed HTML element with its content instead of hydrating it.
This might save a bit of execution time, but the problem is that the whole JS for creating the component is still downloaded and parsed on the client.
Ideally there would be a flag you could set in your loadable-component that excludes it from chunk-extraction so that the chunk never gets added as script tags and therefore never gets downloaded.
Of course when using this flag, you'd need to make sure that the component will actually never (tried to be) imported in your browser environment.

## Example

See my commit: https://github.com/gregberge/loadable-components/commit/5b3614004e213b6b72d7f2f4867e0a4615c9dcb6

## Pitch

Partial hydration is coming and there's nothing we can do about it 😄

**Comment by theKashey** [comment]
> I just use dangerouslySetInnerHTML={{ __html: '' }} to keep the SSRed HTML element with its content instead of hydrating it.

👉 Wrap "partial hydrated" components with __another__ `ChunkExtractorManager`, to suppress any information coming from them.
This is basically the best, and the only correct way to handle the problem - attack it from the "I don't need js code for this block" angle.
