### ISSUE TITLE
There was an error: Invariant Violation: loadable: cannot find pages-Home in stats

### ISSUE THREAD

**Issue by andreyradkevich** [gregberge/loadable-components#590]
## 💬 Questions and Help

https://stackoverflow.com/questions/62720623/there-was-an-error-invariant-violation-loadable-cannot-find-pages-home-in-sta

Could you pls check this issue and why does it happens ? It will be great if you will add in documentation correct way to configure webpack.config for this case

**Comment by paullaffitte** [comment]
I have the same issue using react-app-rewired with the default webpack config.
