### ISSUE TITLE
Using of ChunkExtractorManager

### ISSUE THREAD

**Issue by sanpanthera** [gregberge/loadable-components#591]
My app is SSR based and I am using ChunkExtractorManager to inject the ChunkExtractor in the server side. I am not using any functions like getscripttags or getscriptelements . My app works fine. But getting warnings on console 

_loadableready() requires state please use getscripttags or getscriptelements server-side_.

Why I am getting this warning?

**Comment by theKashey** [comment]
It mean then `loadable` could not see the result of your job and __not__ working -  `https://github.com/gregberge/loadable-components/blob/master/packages/component/src/loadableReady.js#L42`

Please use `getScriptElements ` or `getScriptTags` - since version 5.13 (current) they are __mandatory__.

**Comment by sanpanthera** [comment]
@theKashey Thanks for the clarification :)

**Comment by sanpanthera** [comment]
@theKashey One more doubt

When I use entrypoints:['server']. it adds the below two script tags. Entrypoint here means clientside or server side? If server side? once the below script is added it loads server side code in the browser which is weird. 

<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[]</script>

<script async data-chunk="server" src="/assets/server.js"></script>

**Comment by sanpanthera** [comment]
@theKashey Please help me in this issue. After I added getScriptElements in my code. The warning disappeared. However I ran into another problem. Not able to resolve the issue. 

Below is the build directory structure.
![image](https://user-images.githubusercontent.com/24603729/87227575-9d153400-c3b9-11ea-9b4d-3bddeb2375a5.png)

Localhost serves from the public directory. I’m getting 404 errors in network tab for the files in chunks folder. In browser it’s loading the .chunk.js files. Why it’s not considering the files under chunk folders. How I can resolve this issue.

**Comment by theKashey** [comment]
So the question is how you managed to store chunks in separate place. The rule of thumb - delete __anything__ you are not 100% sure about from your webpack config.
Like __anything__ you might not need.
