### ISSUE TITLE
`chunkExtractor.getScriptElements` returns nested array in 5.13.1

### ISSUE THREAD

**Issue by bendvc** [gregberge/loadable-components#592]
## 🐛 Bug Report

Public API for `chunkExtractor.getScriptElements` is described as being an Array of React <script> Elements. As of version `5.13.1` it returns an array who's first element is also an array.

## To Reproduce

Unfortunately I cannot share my private repo. But the recent change to this function was the cause of this error. https://github.com/gregberge/loadable-components/blob/8cf392d124100763921226bdfcac10d350b64b34/packages/server/src/ChunkExtractor.js#L300 

Previously it returned a single element, but is now returning an array that isn't getting spread in this function 

https://github.com/gregberge/loadable-components/blob/8cf392d124100763921226bdfcac10d350b64b34/packages/server/src/ChunkExtractor.js#L384

## Expected behavior

`chunkExtractor.getScriptElements` returns an array of react script elements.

```bash

```

**Comment by theKashey** [comment]
Yep, it could flatten scripts before returning.

**Comment by markwoodward23** [comment]
@theKashey happy to pick this up if you're busy.

**Comment by theKashey** [comment]
@markwoodward23 - that would be very good. It's like a few lines to change, but I don't have any time to work on this.

**Comment by markwoodward23** [comment]
@theKashey - tried forking and install but I keep seeing this error: 
```
FAIL  packages/server/src/ChunkExtractor.test.js
  ● Test suite failed to run

    Cannot find module '@loadable/component' from 'sharedInternals.js'

    However, Jest was able to find:
    	'./sharedInternals.js'
```

Any ideas?

**Comment by theKashey** [comment]
@markwoodward23 sounds like you need `lerna bootstrap` or `yarn build` made at the top level.

**Comment by markwoodward23** [comment]
@bendvc / @theKashey https://github.com/gregberge/loadable-components/pull/607
