### ISSUE TITLE
SSR does not wait for react-router@2.0.0 enterHook callback

### ISSUE THREAD

**Issue by breeny** [gregberge/loadable-components#593]
https://github.com/ReactTraining/react-router/blob/v2.0.0/docs/Glossary.md#enterhook

I know this is an old dependency, so very understandable if this behaviour is not intended to be supported, but was wondering if there's any additional config/setup I can do to minimise needing to refactor this.

As linked above, react router used to support an enter hook that would actually block the render of a route until a callback was invoked. In my situation, this is where I load API data for a specific endpoint, which then allows it to be rendered on the server as the redux store would be populated with data on loading the route.

Without using loadable-components, this behaviour still works as intended on modern react (currently running 16.9.0).

However, once a component that uses this pattern (say a top level component for a route) is made into a loadable, this behaviour no longer works - the render method/cycle occurs without waiting for the enterhook to resolve, meaning my top level route components do not render on the server, or render without expected data.

```js
//onEnter middleware for router
const onEnter = routeName => createRouterMiddleware(
  //other middleware,
fetchDataMiddleware
)(store);
//attach onEnter as per documentation above

// fetchDataMiddleware
// will return when callback is invoked
const { getState, dispatch } = store;
// Gets components to be rendered and checks for a fetchData method
// If available, it invokes this method, and returns any promises from these
const dataPromises = components
    .filter(component => component && component.fetchData)
    .map(component => component.fetchData(getState, dispatch, location, params))
    .filter(promise => promise);

Promise.all(dataPromises).then(() => { callback() });
```

Using this above pattern, a component that implements a fetchData method, without using loadable-components, will execute in the following order:
1. Route resolved
2. fetchData invoked
3. fetchData result retrieved
4. Render called

When plugged into loadable-components, the following is observed:
1. Route resolved
2. Render called
_fetchData never invoked or result retrieved_

Hopefully can shed some light on if theres anything additional I can do to have this feature supported without needing to upgrade/re-architect the route and data loading strategy.

Thank you!

**Comment by theKashey** [comment]
loadable is not "transparent", and could not be as long as the actual component logic does not exists until it is loaded.
As a result `component.fetchData` does not exists if `component` is wrapped with `loadable`. 

There is no way we could fix it, but you can:
- option 1 - move `fetchData` elsewhere. It should not be on component. For example you can add it to `loadable` manually. `const lcomponent = loadable(() => import('./component'); lcomponent.fetchData = ....`

- option 2 - move `loadable` inside `Component`, so it something with `.fetchData` would be "above" it.

**Comment by breeny** [comment]
Ah of course, a bit of "duh" moment.

Going to implement it as the component for the loadable implements that call. Once you broke it down that all made sense.

Cheers for the rubber duck validation 😅.

**Comment by theKashey** [comment]
You are welcome :)
