### ISSUE TITLE
SSR and Express without webpack-dev-middleware

### ISSUE THREAD

**Issue by moritz91** [gregberge/loadable-components#594]
## 💬 Questions and Help

First off, thank you for this awesome library! 🚀 A quick question regarding SSR and express, because I have not found any information around this in the documentation.

Attempting to set up SSR with this library while omitting the webpack-dev-middleware that is utilized in your examples causes a mismatch (?) of the client and server bundle. I am not sure about the exact reason, but it is not working. All I did was omit the following piece of code. 

https://github.com/gregberge/loadable-components/blob/d5eea1db0903991bc369f78a74b1ad9fcf6f1709/examples/server-side-rendering/src/server/main.js#L20-L27

Any idea what that magic is that webpack-dev-middleware is doing under the hood?

**Comment by theKashey** [comment]
nothing more than a compilation, and recompilation on demand.

**Comment by moritz91** [comment]
Thanks for the quick response. Turns out it was not an issue related to that middleware. I build for separate targets (node and web) like in your SSR example, but wanted to pipe the response. Looks like that doesn't work. Do you know why?

Replacing renderToString in your example with renderToNodeStream would cause the same issue, I believe.

https://github.com/gregberge/loadable-components/blob/d5eea1db0903991bc369f78a74b1ad9fcf6f1709/examples/server-side-rendering/src/server/main.js#L48
