### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by SiarheiLazakovich** [gregberge/loadable-components#595]
https://github.com/gregberge/loadable-components/blob/cd5113cc34e23fb1379d81d8ba970f410c4acee2/packages/component/src/loadableReady.js#L35

loa**B**able

**Comment by prateekr1** [comment]
I am not sure if it is the root cause for below

![Screenshot from 2020-07-10 21-07-43](https://user-images.githubusercontent.com/22632975/87172302-a63ace00-c2f1-11ea-9de3-b91e1f0556f3.png)

because of the above error, I am not able to do
```
npm install --save-dev @loadable/babel-plugin @loadable/webpack-plugin
```

after
```
npm install npm install @loadable/component @loadable/server
``` 

even with an empty `package.json`

**Comment by theKashey** [comment]
😅 classic

**Comment by prateekr1** [comment]
> @theKashey
> 
> I am not sure if it is the root cause for below
> 
> ![Screenshot from 2020-07-10 21-07-43](https://user-images.githubusercontent.com/22632975/87172302-a63ace00-c2f1-11ea-9de3-b91e1f0556f3.png)
> 
> because of the above error, I am not able to do
> 
> ```
> npm install --save-dev @loadable/babel-plugin @loadable/webpack-plugin
> ```
> 
> after
> 
> ```
> npm install @loadable/component @loadable/server
> ```
> 
> even with an empty `package.json`

This got resolved with the help of `npm cache clean --force`

**Comment by theKashey** [comment]
This issue is only about a typo. String constant could not cause anything more that that.

**Comment by theKashey** [comment]
actually fixed
