### ISSUE TITLE
Option to embed JavaScript inline (similar to `chunkExtractor.getCssString`) 

### ISSUE THREAD

**Issue by suhanw** [gregberge/loadable-components#596]
Hi, just wanted to say that I love this library! 

My app uses server-side rendering, and I'm trying to improve the PageSpeed performance. One of the ways I would like to explore is to embed critical JavaScript code into the server-side HTML. I was able to do it with CSS via `chunkExtractor.getCssString`, but is there a similar feature for JavaScript?

Appreciate any insight. Thank you!

**Comment by theKashey** [comment]
You can try inline a whole webpack chunks, and that should work just out of the box.

Actually that might be a pretty good idea, and I do have a few good use cases for it 👍

**Comment by suhanw** [comment]
Do you have any repo to refer to as an example?

**Comment by theKashey** [comment]
With some inlined js - yes, easy.
But with whole chunks inlined, especially via loadable - it has not existed before you created this issue.
