### ISSUE TITLE
Cannot read property 'call' of undefined (5.13.1)

### ISSUE THREAD

**Issue by CareLuLu-Gabriel** [gregberge/loadable-components#599]
## 🐛 Bug Report

First of all, thank you for the awesome library! We've been using in production and it has been a blessing!

===

My app crashes throwing "Cannot read property 'call' of undefined" when hydrating a server-side rendered page. Sometimes it works and sometimes it doesn't. The error started happening after the upgrade:

`@loadable/babel-plugin`: 5.12.0 => 5.13.0
`@loadable/webpack-plugin`: 5.12.0 => 5.13.0
`@loadable/server`: 5.12.0 => 5.13.1
`@loadable/component`: 5.12.0 => 5.13.1

I'd really appreciate help figuring out if the issue is something with `loadable` or something that can be fixed on my end.

## To Reproduce

1. Access https://www.carelulu.com/react-native-web-example/login
2. Click on the URL bar and press enter (you may need to do this more than once until the error appears). 

```javascript
// b(20878:1377) is __webpack_require__
// modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

react-dom.production.min.js:209 TypeError: Cannot read property 'call' of undefined
    at i (login:1)
    at Object.e [as requireSync] (screens.web.js:3)
    at n.o.loadSync (loadable.esm.js:205)
    at new n (loadable.esm.js:155)
    at ba (react-dom.production.min.js:134)
    at Li (react-dom.production.min.js:176)
    at ys (react-dom.production.min.js:263)
    at cu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Js (react-dom.production.min.js:239)
```

The repo for the website above is https://github.com/CareLuLu/react-native-web-skeleton.

If you access https://www.carelulu.com/login you will notice that the problem doesn't happen. The code structure is the same as the example above, except that the version used is `5.12.0`.

## Expected behavior

The app should load the components without errors.

## Link to repl or repo (highly encouraged)

https://github.com/CareLuLu/react-native-web-skeleton.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

```bash
## System:
 - OS: macOS 10.15.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
 - Memory: 204.48 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: 5.13.0 => 5.13.0 
 - @loadable/component: 5.13.1 => 5.13.1 
 - @loadable/server: 5.13.1 => 5.13.1 
 - @loadable/webpack-plugin: 5.13.0 => 5.13.0 
```

**Comment by theKashey** [comment]
Super strange, but you might be affected by #592 due to https://github.com/CareLuLu/react-native-web-skeleton/blob/master/server/middleware/renderer.js#L222-L224

Please check (console.log 🤷‍♂️) that `extraChunk` contains roughly the same data before and after transformation.

**Comment by CareLuLu-Gabriel** [comment]
Thank you for your comment @theKashey!

It's pretty much the same thing, so I don't think it's related to https://github.com/gregberge/loadable-components/issues/592.

5.12.0, https://github.com/CareLuLu/react-native-web-skeleton/blob/master/server/middleware/renderer.js#L222-L224
```html
<!-- before transformation -->
<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[0,14,8,1,4]</script>
<script async data-chunk="main" src="/static/js/runtime-main.989798a2.js"></script>
<script async data-chunk="main" src="/static/js/13.1b793a38.chunk.js"></script>
<script async data-chunk="main" src="/static/js/main.96c0ef7c.chunk.js"></script>
<script async data-chunk="Root" src="/static/js/0.0c595881.chunk.js"></script>
<script async data-chunk="Root" src="/static/js/14.1608a77a.chunk.js"></script>
<script async data-chunk="Root" src="/static/js/Root.3030307d.chunk.js"></script>
<script async data-chunk="Login" src="/static/js/1.6177321f.chunk.js"></script>
<script async data-chunk="Login" src="/static/js/Login.ed68b23c.chunk.js"></script>

<!-- after -->
<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[0,14,8,1,4]</script><script async data-chunk="main" src="/static/js/13.1b793a38.chunk.js"></script><script async data-chunk="main" src="/static/js/main.96c0ef7c.chunk.js"></script><script async data-chunk="Root" src="/static/js/0.0c595881.chunk.js"></script><script async data-chunk="Root" src="/static/js/14.1608a77a.chunk.js"></script><script async data-chunk="Root" src="/static/js/Root.3030307d.chunk.js"></script><script async data-chunk="Login" src="/static/js/1.6177321f.chunk.js"></script><script async data-chunk="Login" src="/static/js/Login.ed68b23c.chunk.js"></script>
```

5.13.1, https://github.com/CareLuLu/react-native-web-skeleton/blob/master/server/middleware/renderer.js#L222-L224
```html
<!-- before -->
<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[0,14,8,1,4]</script><script id="__LOADABLE_REQUIRED_CHUNKS___ext" type="application/json">{"namedChunks":["Root","Login"]}</script>
<script async data-chunk="main" src="/static/js/runtime-main.0bcb6b4c.js"></script>
<script async data-chunk="main" src="/static/js/13.58b9bf36.chunk.js"></script>
<script async data-chunk="main" src="/static/js/main.77aa3628.chunk.js"></script>
<script async data-chunk="Root" src="/static/js/0.fca44dd1.chunk.js"></script>
<script async data-chunk="Root" src="/static/js/14.4bb32f75.chunk.js"></script>
<script async data-chunk="Root" src="/static/js/Root.472df0ae.chunk.js"></script>
<script async data-chunk="Login" src="/static/js/1.7d1cd407.chunk.js"></script>
<script async data-chunk="Login" src="/static/js/Login.cc2238b8.chunk.js"></script>

<!-- after -->
<script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[0,14,8,1,4]</script><script id="__LOADABLE_REQUIRED_CHUNKS___ext" type="application/json">{"namedChunks":["Root","Login"]}</script><script async data-chunk="main" src="/static/js/13.58b9bf36.chunk.js"></script><script async data-chunk="main" src="/static/js/main.77aa3628.chunk.js"></script><script async data-chunk="Root" src="/static/js/0.fca44dd1.chunk.js"></script><script async data-chunk="Root" src="/static/js/14.4bb32f75.chunk.js"></script><script async data-chunk="Root" src="/static/js/Root.472df0ae.chunk.js"></script><script async data-chunk="Login" src="/static/js/1.7d1cd407.chunk.js"></script><script async data-chunk="Login" src="/static/js/Login.cc2238b8.chunk.js"></script>
``` 

Your comment did point me to the right direction!

It seems to be a racing condition caused by the following:
- We preload all scripts (https://github.com/CareLuLu/react-native-web-skeleton/blob/master/server/middleware/renderer.js#L235-L239)
- We remove the `runtime-main.hash.js` from `extraChunks` (https://github.com/CareLuLu/react-native-web-skeleton/blob/master/server/middleware/renderer.js#L222-L224), we do that because it's already part of `index.html`.
- We insert `extraChunks` right before `<div id="root">` (https://github.com/CareLuLu/react-native-web-skeleton/blob/b141370c895545bf037bf95def8ee71b71d4fbf2/server/middleware/renderer.js#L226-L232)

In `5.12.0`, it seems that somehow the scripts wait for `runtime-main` be loaded while `5.13.1` may not have that same guard. Because of the `preload`, sometimes some chunks are executed prior to the `runtime-main` that is embedded in `index.html`. 

The following change fixed the app using `5.13.1`. That makes sure that the `<script>` for all chunks come after `runtime-main`.

https://github.com/CareLuLu/react-native-web-skeleton/blob/b141370c895545bf037bf95def8ee71b71d4fbf2/server/middleware/renderer.js#L231
```javascript
// Changing
html = html.replace('<div id="root">', `${extraScripts}<div id="root">`);

// To
html = html.replace('</body>', `${extraScripts}</body>`);
```

Since `<script async ...>`s don't wait for each other, if the problem is indeed what I mentioned above, what is preventing `5.13.1` from breaking for others is that `runtime-main` is embedded in the `index.html` generated by the build (webpack + loadable) and most likely executed first.

**Comment by theKashey** [comment]
> There were no special logic in 5.12. Nothing was changed in the loading process except `__LOADABLE_REQUIRED_CHUNKS___ext`

The rule is simple - `__LOADABLE_REQUIRED_CHUNKS__` block should be __defined before__ a chunk with `loadable` bootstrap logic inside (runtime or main?), as long as loadable is reading the information inside that block and starting _waiting_ for the "now known" chunks to load.

`script async` dont wait for each other, but `webpack` does.

However, if something is going wrong it shall warn you - https://github.com/gregberge/loadable-components/blob/master/packages/component/src/loadableReady.js#L42

**Comment by CareLuLu-Gabriel** [comment]
> There were no special logic in 5.12. Nothing was changed in the loading process except __LOADABLE_REQUIRED_CHUNKS___ext

In both cases `__LOADABLE_REQUIRED_CHUNKS__` was defined before any main script and no warn was printed. The problem happens here https://github.com/gregberge/loadable-components/blob/master/packages/component/src/createLoadable.js#L159 for some reason.

Anyways, it seems that my problem is solved. Thank you for your help, I really appreciate!
