### ISSUE TITLE
In the server environment, the Consumer in loadable/component always cannot get the extractor

### ISSUE THREAD

**Issue by jtaox** [gregberge/loadable-components#604]
When the server is running, the context in loadable/server/ChunkExtractorManager and the context in loadable/component/loadable are not the same.

As a result, the Consumer cannot obtain the [extractor](https://github.com/gregberge/loadable-components/blob/664cfa148a26325d5f631895aa7855295683151e/packages/component/src/createLoadable.js#L19) provided by the Provider

debug screenshot:
![Snipaste_2020-07-28_00-20-33.png](https://i.loli.net/2020/07/28/4v2QZIuP5AHsxCU.png)
![Snipaste_2020-07-28_00-21-00.png](https://i.loli.net/2020/07/28/UhZ9wguLkYiVEs1.png)
![Snipaste_2020-07-28_00-19-54.png](https://i.loli.net/2020/07/28/wiJQH8LUaxFfPEM.png)

**Comment by theKashey** [comment]
`server` is reading `context` from the `loadable`. Probably from a different loadable - please check `node_modules` nested inside it's directory.
(just inspect `./sharedInternals.js`)

**Comment by jtaox** [comment]
thank you, I reinstalled node_modules and solved the problem
