### ISSUE TITLE
How to measure component height?

### ISSUE THREAD

**Issue by kaysonwu** [gregberge/loadable-components#606]
## 💬 Questions and Help

For components loaded with `loadable`, the measured height is always `0`. I think this should be related to lazy loading, so is there a way to measure it?

**Comment by theKashey** [comment]
You have to wait to load, and measure only after.

I would also point on in that you cannot measure it before the load, as long as __there is nothing to measure__ - please _forward ref_ to loadable and measure "it", not a "parent" you probably working with right now.

You might need to know when loadable would fill your ref, so consider using callback (`useState`) base ref, not `useRef`. If you need to use ref - try [use-callback-ref](https://github.com/theKashey/use-callback-ref)

**Comment by kaysonwu** [comment]
I extracted the hook according to the document, but it has no effect. It should be caused by not loading.

```tsx
import { RefCallback, useState, useCallback } from 'react';

export default function useClientRect(): [DOMRect | undefined, RefCallback<HTMLElement>] {
  const [rect, setRect] = useState<DOMRect>();
  const ref = useCallback<RefCallback<HTMLElement>>(
    node => node && setRect(node.getBoundingClientRect()),
    [],
  );

  return [rect, ref];
}
```

**Comment by theKashey** [comment]
👍 the code is absolutely correct
