### ISSUE TITLE
Unused component being loaded

### ISSUE THREAD

**Issue by wagnerjsilva** [gregberge/loadable-components#608]
## 🐛 Bug Report

I have a code split import which is never used on the page, yet, the chunk loads as if it was. 

## To Reproduce

We can see the chunk in a unrelated page, where a HomePage chunk is visible: 
https://www.drewberryinsurance.co.uk/knowledge/pensions/what-is-the-best-private-pension

## Expected behavior

I would expect not to see that chunk until it was used.

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

```
const HomePage = loadable(() => timeout(import('../HomePage/HomePage'), COMPONENT_IMPORT_TIMEOUT));
const Team = loadable(() => timeout(import('../Content/Team/Team'), COMPONENT_IMPORT_TIMEOUT));
const TeamDetailsWrapper = loadable(() =>
    timeout(import('../Content/Team/TeamDetailsWrapper/TeamDetailsWrapper'), COMPONENT_IMPORT_TIMEOUT)
);
const Accordion = loadable(() => timeout(import('../UI/Accordion/Accordion'), COMPONENT_IMPORT_TIMEOUT));
const LeadForm = loadable(() => timeout(import('../Form/LeadForm/LeadForm'), COMPONENT_IMPORT_TIMEOUT));
const ArchivesContainer = loadable(() => timeout(import('./ArchivesContainer/ArchivesContainer'), COMPONENT_IMPORT_TIMEOUT));
```

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```
## System:
 - OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (2) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
 - Memory: 925.24 MB / 7.68 GB
 - Container: Yes
 - Shell: 4.4.20 - /bin/bash
## Binaries:
 - Node: 10.16.3 - /usr/local/bin/node
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.0 => 5.13.0 
 - @loadable/component: ^5.13.1 => 5.13.1 
 - @loadable/server: ^5.13.1 => 5.13.1 
 - @loadable/webpack-plugin: ^5.13.0 => 5.13.0 


```

**Comment by theKashey** [comment]
There is no way I could help you trace this problem. The chunk can be included if some other code import something "from it".
Please try [whybundled](https://github.com/d4rkr00t/whybundled) to understand why some specific file was bundled.
Alternatively - WebStorm has a cool tool "Find usages", which is also very helpful here.

**Comment by wagnerjsilva** [comment]
Hello,

I have since managed to resolve the issue by changing the order the component was included, but obviously this doesn't answer why it would be happening anyway.

Thanks for suggesting the analysis tools, might be probably what I need here.
