### ISSUE TITLE
publicPath not working for me + SSR errors

### ISSUE THREAD

**Issue by lucasaides** [gregberge/loadable-components#613]
Hey, first time trying to implement loadable-components,
I added to my project the packages, imported two different packages with loadable,
stats file and vendors file are being generated correctly,
when trying to SSR my page with a loadable component I get "Cannot find module './vendors~<packagename>.js'"
when the page loads the http requests from the vendors bundles are trying to fetch from a different url than the publicPath I passed to the ChunkExtractor

**Comment by theKashey** [comment]
It's not possible to know why your example is not working. There is no example using `publicPath`, but it shall just work.
There are two ways to configure it:
- via webpack configuration (which should work just out of the box)
- and via option for `ChunkExtractor`
