### ISSUE TITLE
Support for multi-config compilation

### ISSUE THREAD

**Issue by IIIristraM** [gregberge/loadable-components#615]
## 💬 Questions and Help

I'm using a monorepo approach, where client consists of multiple packages with their own webpack configurations, but all bundles dynamically extends single application, which is hosted on nodejs server.

So each package produce its own loadable-stats.json, and for dev build I'm using webpack-dev-middleware with multicompiler.

I found no clues in documentation on whether any conventional way to extract chunks in such configuration, so I would appreciate any advice on how to make loadable-components work for multiple stats files.

**Comment by theKashey** [comment]
I can not provide and solution as well. There is an attempt to use loadable-components with __module federation__ - https://github.com/gregberge/loadable-components/pull/575, but it's actually NOT working

May be @7rulnik knows more about it.

**Comment by kdevan** [comment]
This example project helped me: https://github.com/gregberge/loadable-components/blob/master/examples/server-side-rendering/src/server/main.js

**Comment by IIIristraM** [comment]
As far as I understand, now the only possible solution is to create ChunkExtractor for each stats file, which means that for N files application has to be rendered N times to collect chunks from all builds.

**Comment by theKashey** [comment]
You can create multiple chunk extractors on the server side but it might not work that way on the client side, where any code is executed inside some particular webpack "instance".

If you want to "mix" different builds/apps together - you need module federation.

**Comment by 7rulnik** [comment]
@theKashey it works with node target, but currently it's [impossible to predict](https://github.com/module-federation/module-federation-examples/pull/19#issuecomment-626704241) some assets on the client-side. Not a big issue but still annoying.
