### ISSUE TITLE
Feature request: Handle non-standard file extensions in @loadable/server 

### ISSUE THREAD

**Issue by dr3** [gregberge/loadable-components#616]
## 🚀 Feature Proposal

There is a hardcoded list of extensions that files can have to be outputted by `getScriptTags` here 
https://github.com/gregberge/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L12-L15

This can likely be handled by a new option to ChunkExtractor, expanding the hardcoded list

## Motivation

In our application we use `.js` and `.mjs` extensions, the later being `es6` with no polyfills. We are unable to progress due to there being no way to get them outputted by the `getScriptTags` function

## Example

When having js bundles with an extention different to `.mjs`

## Pitch

To be more adaptable.

**Comment by dr3** [comment]
I guess 3 options would be

1) add `.mjs` to hardcoded object
2) pass an option to `ChunkExtractor` which extends object
3) pass an option to `ChunkExtractor` which overrides object

If any of these seem suitable let me know and ide be happy to open a PR

**Comment by theKashey** [comment]
- there is PR adding proper support for "native modules" - https://github.com/gregberge/loadable-components/pull/573
- you don't need, and never needed `.mjs`. You need `module` attribute on a script. And actually you might not need it. "Native" modules are not "bundled", and loadable has a very minimal power here.
- `polyfills` are perpendicular to `mjs`. You can just bundle your stuff twice, pick the right `stats` basing on the user agent, and use the right ChunkExtractor to manage the right version.

---

Could you clarify what exactly you want to have at the end? As I understand "double bundling".
If yes - then skip the rest, and focus on it. It's about how you will create two bundles, how(when) you gonna pick the right and how it gonna be served (I prefer publicPath based separation).

**Comment by dr3** [comment]
Hey, yeah you're right we don't need the `.mjs` extension technically, we use currently use it to differentiate in a webpack output file, and its a nice to have when debugging changes and its instantly clear which files are aimed at older browsers.

I didn't mean to imply `module` specifically, more just the freedom to not use `.js` if you're application requires it

**Comment by theKashey** [comment]
> add .mjs to hardcoded object

😎

https://github.com/gregberge/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L14

**Comment by dr3** [comment]
Oh brilliant! thanks @theKashey, i had to do that in a fork internally, can return back to `@loadable/server` now :D
