### ISSUE TITLE
How does loadableReady.js work?

### ISSUE THREAD

**Issue by justin808** [gregberge/loadable-components#623]
From https://github.com/gregberge/loadable-components/blob/master/packages/component/src/loadableReady.js

The function loadableReady is documented to allow running a function once all required chunks have loaded.

Where is the behavior of returning a new promise at the top level of a file documented?

This promise is returned:

https://github.com/gregberge/loadable-components/blob/master/packages/component/src/loadableReady.js#L51-L76

```js
return new Promise(resolve => {
  window.__LOADABLE_LOADED_CHUNKS__ = window.__LOADABLE_LOADED_CHUNKS__ || []
  const loadedChunks = window.__LOADABLE_LOADED_CHUNKS__
  const originalPush = loadedChunks.push.bind(loadedChunks)

  function checkReadyState() {
    if (
      requiredChunks.every(chunk =>
        loadedChunks.some(([chunks]) => chunks.indexOf(chunk) > -1),
      )
    ) {
      if (!resolved) {
        resolved = true
        resolve()
        done()
      }
    }
  }

  loadedChunks.push = (...args) => {
    originalPush(...args)
    checkReadyState()
  }

  checkReadyState()
})
```

But the example code shows this being executed at the top level.

So the return value is not used, seemingly. 

Does it even need to be returned?

Or is the simple fact of a new promise being created leading to some webpack or browser code calling resolve on all those promises?

Can you provide some explanation regarding how this function works?

Is there some browser spec or Webpack detail that explains what creating a new promise does when a script is loaded async?

**Comment by justin808** [comment]
OK -- I see a few things...

Array.push is monkey patched on the global `window.__LOADABLE_LOADED_CHUNKS__` to call `checkReadyState()`

Then webpack has some magic that runs this code of push on the global, and that can resolve the promise and eventually run the `done()` function.

https://github.com/gregberge/loadable-components/blob/master/packages/webpack-plugin/src/index.js#L76

```js
  apply(compiler) {
    this.compiler = compiler

    // Add a custom output.jsonpFunction: __LOADABLE_LOADED_CHUNKS__
    compiler.options.output.jsonpFunction = '__LOADABLE_LOADED_CHUNKS__'

    if (this.opts.outputAsset || this.opts.writeToDisk) {
      compiler.hooks.emit.tapAsync('@loadable/webpack-plugin', this.handleEmit)
    }
  }
```

**Comment by theKashey** [comment]
webpack-plugin
- loadable replaces `jsonp_callback` to "know" when one or another webpack `chunk` is loaded

/server
- server collects used `modules`, maps them via `stat.json` to `chunks`
- prepends result HTML with `script` tag containing required chunks

/client
- client provides `jsonp_callback` for callback
- once all chunks, collected by server, has been loaded - __you are "ready"__

**Comment by justin808** [comment]
> webpack-plugin loadable replaces jsonp_callback to "know" when one or another webpack chunk is loaded

What's the original behavior?

**Comment by theKashey** [comment]
Original behavior of what? Loadable just _wraps_ the original webpack callback with own reporter to know when something got loaded.

**Comment by justin808** [comment]
@theKashey 
> Original behavior of what?

You wrote **replaces jsonp_callback**.

@gregberge I'm curious as to the Promise return. I'm guessing that while that's not used in the API, it _could_ be used to run something after the `done()` is eventually run.

**Comment by theKashey** [comment]
Can we start from the beginning? What it the question?

"Promise return" is a return value of `loadableReady`. There is absolutely nothing special about it.

```js
 function checkReadyState() {
    if (
      // if every required chunk
      requiredChunks.every(chunk =>
        // is loaded
        loadedChunks.some(([chunks]) => chunks.indexOf(chunk) > -1),
      )
    ) {
      if (!resolved) {
        resolved = true
        resolve()  // <---- then resolve the promise
        done()
      }
    }
  }
```
