### ISSUE TITLE
Error "undefined is not an object (evaluating 'e[c].call')" When runtime chunk is slow to load

### ISSUE THREAD

**Issue by dr3** [gregberge/loadable-components#634]
## 🐛 Bug Report

When the runtime chunk is slow to load, `loadableReady` will run regardless.
This causes some errors (depending on the browser)
  
`undefined is not an object (evaluating 'e[c].call')` - Safari & Chrome
`Cannot read property 'call' of undefined` - All browsers
`can't access property "call", e[c] is undefined` - Firefox

Related to https://github.com/gregberge/loadable-components/issues/558

## To Reproduce

To replicate this I used express to serve JS bundles, allowing me to simulate it being slow to load

1) Slow down the bundle. I used this in my express routing
```
app.use('*/runtime~app.*.js', async (req, res, next) => {
  await new Promise(resolve => setTimeout(resolve, 5000));
  next();
});
``` 
2) Load the page in Safari 13 or 14 (seems to be the easiest browser to replicate)
3) See error
![image](https://user-images.githubusercontent.com/11341355/94242074-6efdb580-ff0d-11ea-9c75-8d96f9ee3a65.png)

Note, the error *only* happens after `loadableReady` has completed and the hydration begins. This doesn't happen if you don't use `loadableReady`.

## Expected behavior

`loadableReady` continues to wait for the runtime chunk to avoid the error

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.5
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 4.76 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
 - Yarn: 1.21.1 - ~/.yarn/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
## npmPackages:
 - @loadable/babel-plugin: 5.13.0
 - @loadable/component: 5.13.2
 - @loadable/server: 5.13.1
 - @loadable/webpack-plugin: 5.13.0
```

**Comment by theKashey** [comment]
> This doesn't happen if you don't use loadableReady.

What else you can use?

> See error

So the error you can see is the real error - not `undefined is not an object...`, but `...expected to be available`. And the question is "why"

**Comment by prateekr1** [comment]
A similar situation I tried to explain in the below comment

https://github.com/gregberge/loadable-components/issues/558#issuecomment-631219189

I think this bug is related to the order of runtime chunk.

Currently, I am using the following config in webpack

```js
optimization: {
    runtimeChunk: false,
  },
```
and is working fine for me.

**Comment by yukiyang0729** [comment]
@prateekr1 In issue 558, the problem is not completely solved, is it?

**Comment by dr3** [comment]
Yeah disabling the runtime chunk meerly avoids the issue. There is still a larger issue. I still wanted to use the runtime chunk. 

In my project I had to fork `@loadable/server` to make the runtime chunk not `async` (the rest still are), doing something similar to https://github.com/gregberge/loadable-components/pull/526

**Comment by prateekr1** [comment]
> @prateekr1 In issue 558, the problem is not completely solved, is it?

@yukiyang0729 
yes, the problem still exists when the Webpack config is having

```js
optimization: {
    runtimeChunk: true,
  },
```

**Comment by yukiyang0729** [comment]
> > @prateekr1 In issue 558, the problem is not completely solved, is it?
> 
> @yukiyang0729
> yes, the problem still exists when the Webpack config is having
> 
> ```js
> optimization: {
>     runtimeChunk: true,
>   },
> ```

Is there any other solution? The author did not reply

**Comment by yukiyang0729** [comment]
> async

Have you solved this problem ? Can i see the code ?

**Comment by yukiyang0729** [comment]
> Yeah disabling the runtime chunk meerly avoids the issue. There is still a larger issue. I still wanted to use the runtime chunk.
> 
> In my project I had to fork `@loadable/server` to make the runtime chunk not `async` (the rest still are), doing something similar to #526

Have you solved this problem ? Can i see the code ?

**Comment by theKashey** [comment]
So, once again - how to replicate?

**Comment by yukiyang0729** [comment]
> So, once again - how to replicate?

@theKashey , hi the problem still exists when the Webpack config is having

optimization: {
    runtimeChunk: true,
  },

**Comment by dr3** [comment]
@theKashey I am able to reproduce this consistently by slowing down the loading of the runtime chunk. I do this by serving the files via express and using this code to slow the runtime one down
```js
app.use('*/runtime~app.*.js', async (req, res, next) => {
  await new Promise(resolve => setTimeout(resolve, 5000));
  next();
});
```

**Comment by yukiyang0729** [comment]
> Yeah disabling the runtime chunk meerly avoids the issue. There is still a larger issue. I still wanted to use the runtime chunk.
> 
> In my project I had to fork `@loadable/server` to make the runtime chunk not `async` (the rest still are), doing something similar to #526

Is this scheme applied in the project?

**Comment by yukiyang0729** [comment]
@theKashey  hello, can you support this config #526

**Comment by dr3** [comment]
In my fork i changed `assetToScriptTag` to 
```js
function assetToScriptTag(asset, extraProps) {
  const props = handleExtraProps(asset, extraProps)
  const { async, ...rest } = props

  return `<script ${async ? 'async' : ''} data-chunk="${asset.chunk}" src="${
    asset.url
  }"${getSriHtmlAttributes(asset)}${extraPropsToString(asset, rest)}></script>`
}
```

and then use
```
extractor.getScriptTags(asset => ({
   async: !!asset && !asset.filename.includes('runtime~app'),
}))
```

Obs not ideal, we should try and fix the core issue. But this stopped us getting errors for now

**Comment by theKashey** [comment]
That strange, as long as `runtime-chunk` is the one who actually triggers script execution.

**Comment by theKashey** [comment]
Hey! I've created an [example based on this issue](https://github.com/gregberge/loadable-components/blob/master/examples/webpack/webpack4/src/server/main.js#L10) and it's... ☹️ working.
If someone can help me break it - it will be much appreciated.

The async tag definitely is a problem here, and replacing it by defer(still async!) should solve the problem. However - we need to know what exactly is broken to fix this problem once and for all.

**Comment by iwyvi** [comment]
@theKashey I modified the example and it would reproduce the error almost every time.

[In this example](https://github.com/iwyvi/loadable-components/blob/02ab0537e540b30f98c9aa75ae8b9d34e201cd08/examples/webpack/webpack4/src/server/main.js#L10) , I have three js files: `runtime`, `main`, `letters`. If these files are loaded  by the following order:
`main -> letters -> runtime`, we will get the same error mentioned above every time.

I may find the reason:

https://github.com/gregberge/loadable-components/blob/c000d24eb9ca682dfe38403e838c5c5cbec46af3/packages/component/src/loadableReady.js#L53

`loadableReady` only checks whether the loadable required chunks are listed in `window.__LOADABLE_LOADED_CHUNKS__`, but can't assure these chunks have already been loaded by webpack. Because `letters` has no relationship with `main`, so despite `letters` has not been installed, webpack runs `main` and `loadableReady` will resolve.

So if script files are loaded by following order, it will cause the error: 

all the chunks listed in `__LOADABLE_REQUIRED_CHUNKS__` are loaded after any of entry file and its dependent chunks, and `runtime` is loaded at last.

I think it will be solved if we can remove `async` in runtime's `<script>` when `getScriptTags`.

**Comment by theKashey** [comment]
Thank you @iwyvi, let me play with it a little

**Comment by theKashey** [comment]
Not fixed until a new version is released.

**Comment by theKashey** [comment]
`5.14.1` has been released 🥳

**Comment by aquelehugo** [comment]
@theKashey is webpack's issue related to this? https://github.com/webpack/webpack/issues/5429
Maybe their update solves it already.
