### ISSUE TITLE
Add the ability to customize the jsonpFunction name (__LOADABLE_LOADED_CHUNKS__)

### ISSUE THREAD

**Issue by LinusCenterstrom** [gregberge/loadable-components#635]
## 🚀 Feature Proposal
Add an option to either override, or possibly preserve the original webpack value of, the jsonpFunction name the plugin uses.

## Motivation

Currently the plugin overrides jsonpFunction here 
https://github.com/gregberge/loadable-components/blob/25b532eb53a2841229dbc8a9c91f24112a46b93f/packages/webpack-plugin/src/index.js#L76

This could potentially cause issues if the plugin is used by multiple apps on the same page. 
For instance I'm building an app that can be embedded into a site just by including a script tag.
This could potentially break the site if it is already using loadable-components. 
(Unless I'm missing something and it's already possible to namespace this somehow)

## Example

Ideally just as an option to the webpack plugin. 
Something like 
```js
new LoadablePlugin({
  jsonpFunction: "__mylib__LOADABLE_LOADED_CHUNKS__"
})
```
and possibly (but not required){
```js
new LoadablePlugin({
  jsonpFunction: false
})
```
to preserve the original value from the webpack config. (output.jsonpFunction)

Please provide an example for how this feature would be used.

## Pitch

As far as I can tell something like this would be needed to support multiple separate loadable-components apps on the same page. 
I could not find any obvious way to patch this in outside of the library.

It should be non-breaking and hopefully pretty simple to implement.
I could take a shot at it myself if you are open to PR:s for this but I have not built any webpack plugins before. 
I assume there is a way to set a variable in the plugin that's accessible in https://github.com/gregberge/loadable-components/blob/master/packages/component/src/loadableReady.js somehow

**Comment by theKashey** [comment]
You dont need to override `jsonpFunction` - it is just used to report which chunks are "available" (read: this part could not break your app) - you need to override `loadableReady` to let it await chunks from multiple apps, like expect more than one _dataElement_, reported from different apps.

However - _embedded into a site just by including a script tag_ - means that your app is not a part of SSR, and thus is not a "part" of `loadableReady`. Is there a real issue, or just potential one?

We are always open for PRs and I would encourage you to play with it a little in search of the best way to resolve this task.

**Comment by LinusCenterstrom** [comment]
> You dont need to override `jsonpFunction` - it is just used to report which chunks are "available" (read: this part could not break your app) - you need to override `loadableReady` to let it await chunks from multiple apps, like expect more than one _dataElement_, reported from different apps.

Right I was a bit unclear on this. I do not want to wait for multiple apps to be ready, I want to be sure that if my app is included on their site and their site already uses loadable-components and loadableReady my script does not break / change the behavior of their site by pushing unexpected chunks to __LOADABLE_LOADED_CHUNKS__.
I was thinking my chunks could have conflicts with theirs if some of the chunks generated by my app get the same ids as some of the chunks of their app.  The reason I think this could be a problem is that the webpack docs 
https://webpack.js.org/configuration/output/#outputjsonpfunction mention 

> if multiple webpack runtimes (from different compilations) are used on the same webpage, there is a risk of conflicts of on-demand chunks in the global namespace.

which is the reason I wanted to change the name of my jsonpFunction to something else.

> 
> However - _embedded into a site just by including a script tag_ - means that your app is not a part of SSR, and thus is not a "part" of `loadableReady`. Is there a real issue, or just potential one?
> 

Correct, the script version does not currently use loadableReady. The reason we use loadable-components is that we offer multiple ways to use the app. We also offer an iframe version, and a standalone version of the same app. Those versions do use SSR.

All versions also lazy-load components on the client and since loadable-components works great even when only used client-side we wanted to keep it simple and use it in the script-version too, even though the SSR parts are not needed there.

We have also planned to build another hybrid-version of the app in the future where the customer can make an API-call to get the initial html / scripts / css of the app to include on the page in which case we would also want to use SSR, and loadableReady.

**Comment by theKashey** [comment]
> if multiple webpack runtimes

fair point. Different bundles should have use different json_callbacks as long as different runtimes are waiting for these blocks, and the callback is a global variable and would interfere.

👉 For multi-app SSR this change is required

However, in your case you don't have any SSR for your app, and don't have to use loadable webpack plugin which does override. 
Actually it's better to ask why you are using loadable at all - we are trying to be honest and really advising to use `React.lazy` if you can use `React.lazy`.

**Comment by LinusCenterstrom** [comment]
> However, in your case you don't have any SSR for your app, and don't have to use loadable webpack plugin which does override.
> Actually it's better to ask why you are using loadable at all - we are trying to be honest and really advising to use `React.lazy` if you can use `React.lazy`.

Right, as I mentioned above we offer a few ways to integrate the app. If they use the script version there is (currently) no SSR but the iframe and stand-alone versions do use it.

As we want to share as much code as possible between the different versions of the app we would prefer to use loadable-components to handle lazy-loading in all versions, even though the script version wouldn't use the SSR feature.

**Comment by theKashey** [comment]
Got it. Then there is another question - how this situation could be solved with React.lazy only(yes). I mean - webpack will still use the "standard" jsonp_callback name, and it will interfere with the main bundle.
- so, one will need to change it for webpack
- so, if one is changing it for webpack, the same change should be used by loadable
- so, we shall not add a new option to loadable, we should read that option from webpack config

I found two options for this:
- `jsonpfunction` - https://webpack.js.org/configuration/output/#outputjsonpfunction
- `uniqueName` - https://webpack.js.org/configuration/output/#outputuniquename, which actually controls the first one

The final solution should worth with both.

**Comment by theKashey** [comment]
Adding a `bug` label, as long as jsonp callback clash will produce a bug.

**Comment by gileck** [comment]
Hey, I encountered the same issue in my app. is there any plan to fix it?
