### ISSUE TITLE
requireEntrypoint() make a multiple call with express().listen() and caused a EADDRINUSE error

### ISSUE THREAD

**Issue by Hacksign** [gregberge/loadable-components#648]
## 🐛 Bug Report

When using `requireEntrypoint()` with ssr & express().listen(), invoke `.listen()` function multiple times and cause EADDRINUSE exception.

## To Reproduce

```bash
git clone https://github.com/Hacksign/typescript-loadable-ssr-example
cd typescript-loadable-ssr-example
npm install
npm run start
```

Then access http://127.0.0.1:3000 in your browser, you will receive a crash on terminal:

```bash
Running on http://localhost:3000/
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.listen (/home/hacksign/Code/loadable-components-example/node_modules/express/lib/application.js:618:24)
    at Module.<anonymous> (/home/hacksign/Code/loadable-components-example/dist/node/server.js:1:1354)
    at r (/home/hacksign/Code/loadable-components-example/dist/node/server.js:1:124)
    at /home/hacksign/Code/loadable-components-example/dist/node/server.js:1:931
    at Object.<anonymous> (/home/hacksign/Code/loadable-components-example/dist/node/server.js:1:941)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```

When remove this line:

```javascript
>> cat src/server/index.tsx

import React from 'react'
import path from 'path'
import express from 'express'
import { ChunkExtractor } from '@loadable/server'

const nodeStats = path.resolve(process.cwd(), './dist/node/loadable-stats.json')
const app = express()
app.get('*', (req, res) => {
    const nodeExtractor = new ChunkExtractor({ statsFile: nodeStats })
    //const { default: App } = nodeExtractor.requireEntrypoint()      // REMOVE THIS LINE SOLVED THE CRASH PROBLEM

    res.end('hello world!')
})

app.listen(3000, () => {
    console.log('Running on http://localhost:3000/')
})
```

Run `npm run start` again, the crash problem is solved.

## Expected behavior

No crash on terminal.

## Link to repl or repo (highly encouraged)

https://github.com/Hacksign/typescript-loadable-ssr-example

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
>> npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard
npx: 1 安装成功，用时 1.8 秒

*** Clipboard option removed - use clipboardy or clipboard-cli directly ***


## System:
 - OS: Linux 5.9 Arch Linux
 - CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
 - Memory: 21.48 GB / 31.13 GB
 - Container: Yes
 - Shell: 3.1.2 - /usr/bin/fish
## Binaries:
 - Node: 14.14.0 - /usr/bin/node
 - Yarn: 1.22.10 - /usr/bin/yarn
 - npm: 6.14.7 - /usr/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.0 => 5.13.2 
 - @loadable/component: ^5.13.1 => 5.14.0 
 - @loadable/server: ^5.13.1 => 5.14.0 
 - @loadable/webpack-plugin: ^5.13.0 => 5.14.0 
```

**Comment by theKashey** [comment]
That means that `listen(3000)` it called twice.
Please *think* how it could be possible - only if this file is executed twice.

This could be only possible if you use a "wrong" entrypoint - `server`, not `client`.

Please specify the correct entrypoint explicitly.
```
const { default: App } = nodeExtractor.requireEntrypoint('main');
```

**Comment by Hacksign** [comment]
> That means that `listen(3000)` it called twice.
> Please _think_ how it could be possible - only if this file is executed twice.
> 
> This could be only possible if you use a "wrong" entrypoint - `server`, not `client`.
> 
> Please specify the correct entrypoint explicitly.
> 
> ```
> const { default: App } = nodeExtractor.requireEntrypoint('main');
> ```

Tried change `const { default: App } = nodeExtractor.requireEntrypoint();`  to  `const { default: App } = nodeExtractor.requireEntrypoint('main');`, problem still exists.

I think I'm using the correct entrypoint on server side.

webpack.server.js:

```javascript
>> cat build/webpack.server.js 

module.exports = {
    .....blablaba....
    entry: {
        main: path.resolve(__dirname, '../src/client/entry-node.tsx'),
        server: path.resolve(__dirname, '../src/server/index.tsx')
    },
    ....blablabla...
}
```

And the `entry-node.tsx` just invoked a Wrapper which is made by `loadable( () => import(...))` .

entry-node.tsx:

```javascript
>> cat src/client/entry-node.tsx 

import React from 'react'
import { StaticRouter } from 'react-router-dom'

import App from './app'

const AppSSR = ({ url }) => (
  <StaticRouter location={url}>
    <App />
  </StaticRouter>
)

export default AppSSR

```

app.tsx:

```javascript
import React, { FunctionComponent } from 'react'
import { Switch, Route, Link } from 'react-router-dom'
import loadable from '@loadable/component'

const Home = loadable(() => import('./pages/home'))
const About = loadable(() => import('./pages/about'))

const App: FunctionComponent = () => {
  return (
    <div>
      <nav>
        <h2>Navigation</h2>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/about">About</Link>
          </li>
        </ul>
      </nav>

      <Switch>
        <Route path="/about">
          <About />
        </Route>
        <Route path="/">
          <Home />
        </Route>
      </Switch>
    </div>
  )
}

export default App
```

I'm very confused why express server's `.listen()` executed twice, because my code logic do not do this ;(

**Comment by Hacksign** [comment]
BTW

If I just covert `src/server/index.tsx` with bable:

```bash
babel -d dist/node/server.js --extensions ".tsx" src/server/index.tsx
```

Then exucute the converted entrypoint file:

```bash
node dist/node/server.js
```

There will be **no crash**.

**Comment by Hacksign** [comment]
And there will be **NO** crash if I do this:

```bash
>> cat build/webpack.server.js 

module.exports = {
    .....blablaba....
    entry: {
        main: path.resolve(__dirname, '../src/client/entry-node.tsx'),
        //server: path.resolve(__dirname, '../src/server/index.tsx')    //REMOVE THIS LINE
    },
    ....blablabla...
}

>> npm run build     // build the source code
>> ./node_modules/.bin/babel -d dist/node/ --extensions '.tsx' src/server/index.tsx   // convert index.tsx manually
>> node dist/node/index.js 
Running on http://localhost:3000/
```

Then access http://127.0.0.1:3000, there will be no crash.

**Comment by theKashey** [comment]
> And there will be NO crash if I do this: ...

Which sounds like a wrong entrypoint is used. 
Please check what is inside `./dist/node/loadable-stats.json` - look for `namedChunkGroups` key.

**Comment by welkup** [comment]
Hi @theKashey 

I started experiencing this behavior as well (with the release of @loadable/server v5.10.3).

It appears to come from this added code to [ChunkExtractor.requireEntrypoint()](https://github.com/gregberge/loadable-components/blob/3676e488a714068baca5cefad2aa98c0de0a8fab/packages/server/src/ChunkExtractor.js#L380)

```
this.stats.assets
      .filter(({ name }) => isScriptFile(name))
      .forEach(({ name }) => {
        smartRequire(path.join(this.outputPath, cleanFileName(name)))
      })
```

The way I understand this is that it is going through ALL of the webpack assets rather than only the assets of the entrypoint passed into `requireEntryPoint`. This includes the server bundle that is starting the webserver and causing the EADDRINUSE error.

Should this code instead be referencing the local `const assets = this.getChunkAssets(entrypoint)` related to the specified entrypoint rather than `this.stats.assets` that covers assets of all entrypoints? I expect this bug would not manifest if there is only a single entrypoint given `this.stats.assets` and `assets` are the same in that scenario.

In code, would it make sense if it were instead:
```
assets
      .filter(({ name }) => isScriptFile(name))
      .forEach(({ name }) => {
        smartRequire(path.join(this.outputPath, cleanFileName(name)))
      })
```

Thanks!
