### ISSUE TITLE
how to pass props to lodables.lib()

### ISSUE THREAD

**Issue by smsivaprakaash** [gregberge/loadable-components#650]
## 💬 Questions and Help
Trying to load react-dropdown lib via lodable.lib(). it is not loading the component

**Using Ordinary import:**
```
   import Drop form 'react-dropdown';
   const dropOptions = ['one', 'two', 'three'];`
   ....
   render() {
       return (<Drop options={dropOptions/>)
   }}
```

**Using lodable.lib():**
``` 
    const Drop= loadable.lib(() => import('react-dropdown'));
    const dropOptions = ['one', 'two', 'three'];`
    ....
   render() {
       return (<Drop options={dropOptions/>)
   }}
```

It was working with ordinary import, but now with loadabl.lib

Can you help if any syntax is wrong or any extra steps is needed to load the 3rd party libs in loadable.
Thanks,

**Comment by smsivaprakaash** [comment]
@gregberge  Could you pls help with this issue.?

**Comment by smsivaprakaash** [comment]
was able to find out the syntax for it. without using lib()

```
const Drop= loadable(() => import('react-dropdown));

```

**Comment by theKashey** [comment]
yep. Everything what is `Components` is not a `lib`
