### ISSUE TITLE
[SSR] TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Guymestef** [gregberge/loadable-components#654]
## 🐛 Bug Report
When using @loadable/component library, with SSR, I get the error: 
installChunk: Cannot read property 'length' of undefined
In debug, I can see that chunk object only contains __LOADABLE_LOADED_CHUNKS__, no object modules, ids or runtime.
So it crashes on chunkIds.length

```javascript
var installChunk = (chunk) => {
	var moreModules = chunk.modules, chunkIds = chunk.ids, runtime = chunk.runtime;
	for(var moduleId in moreModules) {
		if(__webpack_require__.o(moreModules, moduleId)) {
			__webpack_require__.m[moduleId] = moreModules[moduleId];
		}
	}
	if(runtime) runtime(__webpack_require__);
	for(var i = 0; i < chunkIds.length; i++)
		installedChunks[chunkIds[i]] = 1;
};
```

## To Reproduce

Using @loadable/component library in SSR mode, with a loadable component:
```javascript
const About = loadable(() => import('components/Pages/About'), {
    resolveComponent: components => components.About,
    fallback: <Spinner loading={true} size="big" className="my-2 d-flex justify-content-center" />,
});
```

## Expected behavior
importAsync should not crash, chunk object should be filled with expected properties

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Windows 10 10.0.19041
 - CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
 - Memory: 4.20 GB / 15.73 GB
## Binaries:
 - Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2
 - @loadable/component: ^5.14.1 => 5.14.1
 - @loadable/server: ^5.14.0 => 5.14.0
 - @loadable/webpack-plugin: ^5.14.0 => 5.14.0
```

**Comment by theKashey** [comment]
Sorry, but there is not enough information to reproduce your problem. You are the first one to report it.
Please clarify:
- is it crashes on the client side or server
- whats the difference from, for example [webpack4](https://github.com/gregberge/loadable-components/tree/master/examples/webpack/webpack4) example

**Comment by Guymestef** [comment]
It was crashing on the server.
I found my mistake, my webpack config is generating 2 bundles. And I was using the loadable-stats.json file of the wrong bundle...
