### ISSUE TITLE
Styled Component Conflict

### ISSUE THREAD

**Issue by nesbtesh** [gregberge/loadable-components#656]
## 🐛 Bug Report

I am getting a bug where loadable component is conflicting with styled component and some of the styles generated by styled component are not being imported in the server. The issue appears to have no consistency it comes and goes as more users go to the site

## To Reproduce

goto https://v2.noritex.com/es/
navigate to the brand Concepts Life by clicking on the logo ->  https://v2.noritex.com/es/pages/concepts-life-mayorista-de-decoracion

Then in incognito navigate directly to https://v2.noritex.com/es/pages/concepts-life-mayorista-de-decoracion

Images Issue: https://www.noritex.com/jv8mF8ETXQJwZLMWfScreen_Shot_2020-11-03_at_5.22.04_PM.png
Expected: https://www.noritex.com/ttfjptKHqGh2bqniJScreen_Shot_2020-11-03_at_5.22.23_PM.png

Issue: https://www.noritex.com/EGrADAJTcCgjyMvC3Screen_Shot_2020-11-03_at_5.22.08_PM.png
Expected: https://www.noritex.com/aMWJrxPpFtRhq44DwScreen_Shot_2020-11-03_at_5.22.26_PM.png

## Server Code

`
            const sheet = new ServerStyleSheet();
            const extractor = new ChunkExtractor({
                statsFile: path.resolve("build/loadable-stats.json"),
                entrypoints: ["client"],
            });

            Promise.all(promises).then(async function (data) {
                const lang = req.url.split("/")[1];
                console.log(req.url);
                const isStaging =
                    (host.includes("noritex") && host.includes("staging")) ||
                    host.includes("localhost") ||
                    host.includes("arcane");

                const context = {};
                let status = 200;
                let markup = "";
                let styleTags;
                try {
                    markup = renderToString(
                        <ChunkExtractorManager extractor={extractor}>
                            <StyleSheetManager sheet={sheet.instance}>
                                <StaticRouter
                                    context={context}
                                    location={req.url}
                                >
                                    <App routes={routes} initialData={data} />
                                </StaticRouter>
                            </StyleSheetManager>
                        </ChunkExtractorManager>
                    );
                    styleTags = sheet.getStyleTags();
                } catch {
                    console.log("!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!");
                    console.log("!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!");
                    console.log("!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!");
                    console.log("!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!");
                    console.log("THERE WAS AN ERROR IN THE SERVER RENDERING");
                } finally {
                    sheet.seal();
                }

                const helmet = Helmet.renderStatic();
               // ..... etc

`

## Browser code
`
         
          function isIE() {
            var ua = navigator.userAgent;
            /* MSIE used to detect old browsers and Trident used to newer ones*/

            var is_ie = ua.indexOf("MSIE ") > -1 || ua.indexOf("Trident/") > -1;

            return is_ie;
        }

        function browserSupportsAllFeatures() {
            if (isIE()) return false;
            if (typeof window === "undefined") return true;
            return (
                window.Promise &&
                window.fetch &&
                window.Symbol &&
                window.IntersectionObserver
            );
        }

        function main() {
            loadableReady(() => {
                hydrate(
                    <BrowserRouter>
                        <App routes={routes} initialData={data} />
                    </BrowserRouter>,
                    document.getElementById("root")
                );
            });
        }

        function loadScript(src, done) {
            console.log("loading scripts");
            var js = document.createElement("script");
            js.src = src;
            js.onload = function () {
                console.log("Loaded Polyfills");
                done();
            };
            js.onerror = function () {
                done(new Error("Failed to load script " + src));
            };
            document.head.appendChild(js);
        }

        if (browserSupportsAllFeatures()) {
            console.log("browser supports all features");
            // Browsers that support all features run `main()` immediately.
            main();
        } else {
            // All other browsers loads polyfills and then run `main()`.
            loadScript("/polyfill.js", main);
            // main();
        }

`

**Comment by theKashey** [comment]
Sorry, not able to provide any guidance for the problem.

**Comment by nesbtesh** [comment]
I am closing this issue because the issue appears to be part of styled components. If anyone arrives here make sure to checkout your babelrc file. I found a partial fix by setting display name = true even in production
