### ISSUE TITLE
Webpack 5 target web, es5 error

### ISSUE THREAD

**Issue by gempir** [gregberge/loadable-components#658]
## 🐛 Bug Report

When using target ES5 in webpack I'm getting the error

```
Uncaught TypeError: Cannot read property '__LOADABLE_LOADED_CHUNKS__' of undefined
```

![image](https://user-images.githubusercontent.com/9765622/98398888-f2104080-2061-11eb-9ab7-d8bf1d3b7c3f.png)
![image](https://user-images.githubusercontent.com/9765622/98398953-081e0100-2062-11eb-8a2c-4665d05b9e4b.png)

## To Reproduce

Use webpack 5 with target: ["web", "es5"]

## Expected behavior

No error appears in the console

Issues without a reproduction link are likely to stall.

## System Info
```bash
## System:
 - OS: macOS 10.15.7
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 69.03 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 14.9.0 - /usr/local/bin/node
 - Yarn: 1.22.5 - /usr/local/bin/yarn
 - npm: 6.14.7 - /usr/local/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2
 - @loadable/component: ^5.14.1 => 5.14.1
 - @loadable/webpack-plugin: ^5.14.0 => 5.14.0
```

**Comment by theKashey** [comment]
Tracked in #636, but this is not known before behavior

**Comment by gempir** [comment]
Now that webpack and loadable-components has fixed most issues, I wanted to try this again. 

But I'm still running into the same error. Can anyone maybe give any hints what the problem is related to? Maybe some part of our babel is setup weirdly? Maybe webpack output options thats weird or something?


```
Uncaught TypeError: Cannot read property '__LOADABLE_LOADED_CHUNKS__' of undefined
```

![image](https://user-images.githubusercontent.com/9765622/110106272-c56afc00-7da9-11eb-8553-7f1523635954.png)



```
"@loadable/babel-plugin": "^5.13.2",
"@loadable/component": "^5.14.1",
"@loadable/webpack-plugin": "^5.14.2",
"webpack": "^5.24.3",
"webpack-cli": "^4.5.0"
```

**Comment by gempir** [comment]
Compiling with target web works fine, because that doesn't use the browserlist, but if I compile with no webpack target it will default to browserlist which includes IE11 

```
    "browserslist": [
        "last 2 versions",
        "iOS >= 10",
        "IE >= 11"
    ],
```

`target: ["web", "es5"]` also breaks

**Comment by DimaChervan** [comment]
I have the same issue
`Uncaught TypeError: Cannot read property '__LOADABLE_LOADED_CHUNKS__' of undefined` in IE11.
I use `target: ["web", "es5"]` and `runtimeChunk: true`.
If I understand correct, then I receive exception because during access to `this.['__LOADABLE_LOADED_CHUNKS__']` `this` is undefined due to `'use script'` in function.
@theKashey can you help?
