### ISSUE TITLE
Creating the ChunkExtractor once?

### ISSUE THREAD

**Issue by hornta** [gregberge/loadable-components#659]
I can see that in every example ChunkExtractor is created on every request and passed the statsFile object. By the looks of it the loadable-stats.json file is read once but I found out it's cached and even reloaded when the stats is changed. Shouldn't it be OK then to setup the chunkextractor outside of the request handler? 
https://github.com/gregberge/loadable-components/blob/master/examples/server-side-rendering/src/server/main.js#L42

**Comment by theKashey** [comment]
No, that would be a bad idea - ChunkExtractor is "stateful" and can carry some extra information from one request to another. Probably you don't want it.

However, there is a way to make it work much better - provide `stats` not `statsFile` - https://github.com/gregberge/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L177

**Comment by hornta** [comment]
Okay so I'll need to feed it the client stats data right?

**Comment by theKashey** [comment]
Yep. But you can skip expensive JSON transformation.
