### ISSUE TITLE
Webpack 5 sur error and chunk files error (Public url)

### ISSUE THREAD

**Issue by joacub** [gregberge/loadable-components#660]
## WEBPACK 5 SSR

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
 - Memory: 104.83 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 15.1.0 - ~/.nvm/versions/node/v15.1.0/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 7.0.8 - ~/.nvm/versions/node/v15.1.0/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2 
 - @loadable/component: ^5.14.1 => 5.14.1 
 - @loadable/server: ^5.14.0 => 5.14.0 
 - @loadable/webpack-plugin: ^5.14.0 => 5.14.0 

```
## ERROR
loadable-components: failed to synchronously load component, which expected to be available {
  fileName: './src/components/Admin/Header.js',
  chunkName: 'admin-header',
  error: "Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization"
}
MOUNT ERROR:   ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

**Comment by theKashey** [comment]
👉 #636

**Comment by ajayjaggi** [comment]
@joacub when on client side, is loadableReady getting called ??

**Comment by joacub** [comment]
> @joacub when on client side, is loadableReady getting called ??

That error in on server side render, loadableready never finish the call got stcuk
