### ISSUE TITLE
loadableReady stops working when 'react-dom' is added in shared of moduleFederationPlugin

### ISSUE THREAD

**Issue by ajayjaggi** [gregberge/loadable-components#662]
## To Reproduce

Wrap a component with loadable and then export it using exposes option of moduleFederationPlugin.
Add 'react-dom' in shared option of moduleFederationPlugin.
The remote app itself breaks on client side. The resolve function of loadableReady is never executed.
No errors are thrown.

## Expected behavior
Don't know what is happening but aap should function normally on client side

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash

```

**Comment by theKashey** [comment]
> Issues without a reproduction link are likely to stall.

**Comment by ajayjaggi** [comment]
closing this..have raised new issue with more information
