### ISSUE TITLE
How to indicate component must not render from server but still send chunk script for client?

### ISSUE THREAD

**Issue by lostpebble** [gregberge/loadable-components#665]
For example, I am exporting a client-side only library inside `Loadable_Leaflet.ts`, which I am using loadable to import like so:

```ts
loadable.lib(() => import("./modules/Loadable_Leaflet"), { ssr: false });
```

Currently the option of `ssr: false` seems to be an "all or nothing" kinda option. It won't resolve the library itself when doing SSR, which is what we want (because this browser-only library will throw an error on Node.js), but unfortunately it also seems like it also won't resolve the chunk name for this library either- which is important to give to the client so it knows what to download on first page load.

Am I missing something, or is this currently how the implementation works?

Would be great if there was a way to indicate that this library must not be resolved on the server but still be able to get the chunks- because we know its going to be loaded on the client.

**Comment by theKashey** [comment]
That is an interesting task and definitely something you can not do today, unless you do a dependency mocking via process.env like React picks dev or production mode or webpack `resolve.alias`, but this is not the way it should work so please don't take it as a advice.

**Comment by lostpebble** [comment]
Ah, okay.

I thought there might be some way that the babel plugin could transform the code, that when the server encounters `loadable.lib()` it can extract the needed chunk name without actually going through with the import somehow, which we can then pull out of the assets JSON.

But I'm guessing its quite a bit more involved than that.
