### ISSUE TITLE
Allow other names for 'loadable' in the babel plugin for server-side rendering

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [gregberge/loadable-components#670]
## 🚀 Feature Proposal

It'd be nice to be able to write utilities around `loadable` that can also work with SSR. Would you accept a PR that extends `isValidIdentifier` to allow names other than `'loadable'`?

https://github.com/gregberge/loadable-components/blob/89cf124f9079395f2d77038033e472b22c04deb6/packages/babel-plugin/src/index.js#L39

## Motivation

`loadable` assumes a default export in the loaded component. But, if you're trying to use exclusively named exports, the syntax gets a little yucky:

```js
export const MyComponent = loadable(async () => (await import('./some/path')).MyComponent);
```

## Example

I'd like to write a cute little wrapper for named exports that itself is a little yucky looking:

```js
export const namedLoadable = (importer, name, options) => {
    return loadable(async () => {
      return (await importer())[name];
    }, options);
};
```

...but makes the end-user experience nicer:

```js
export const MyComponent = namedLoadable(() => import('./some/path'), 'MyComponent');
```

## Pitch

It seems like it'd be pretty minimally intrusive to add this option into the Babel plugin, and it'd be nice for users to be able to use named exports more.

**Comment by theKashey** [comment]
> Would you accept a PR that extends isValidIdentifier to allow names other than 'loadable'?

Please refer to https://loadable-components.com/docs/babel-plugin/#loadable-detection as well as `magic-comments` one section below it.

> But, if you're trying to use exclusively named exports

Named imports are supported out of the box - https://loadable-components.com/docs/api-loadable-component/#optionsresolvecomponent using __any__ extra code around "imports" will cause a failure. So your example will not work.

----

😞  Sorry, look like we could not proceed with your proposal.
😃  Look like there is a way to do what you want to do.

**Comment by JoshuaKGoldberg** [comment]
Super, sorry for missing that part of the docs. Thanks for the quick & informative response!
