### ISSUE TITLE
How to use with redux-async-connect?

### ISSUE THREAD

**Issue by arasmussen** [gregberge/loadable-components#675]
We've got an awesome setup with webpack, react, redux, babel, react-router, server-side rendering, and redux-async-connect. We're looking to introduce code splitting by route via loadable-components.

Everything is working well, except now on page transition, the redux-async-connect functionality no longer seems to work. It'll load the page immediately without waiting for the async fetches, and our page breaks because it's expecting certain data to be there.

Any ideas on how to get these libs to play nicely with each other? I did a ton of searching and couldn't find much documentation at all.

**Comment by theKashey** [comment]
Your problem is not solvable without an example representing a broken behavior.

**Comment by arasmussen** [comment]
Sure. I don't really have time to put together an example, was just wondering if anyone had specific experience with these two libs. I'll close this out.
