### ISSUE TITLE
How to use loadable/components with SSR and react-query?

### ISSUE THREAD

**Issue by kevinvugts** [gregberge/loadable-components#678]
## 💬 Intro

First of all, nice library and works quite well out of the box. 
However it took me a while to get everything working on the server side. :-) 

Currently I am experiencing issues with my data fetching on the server. As I know data fetching is not what loadable-components is responsible for. However, the problem is slightly different in this matter.

I am using [react-query](https://react-query.tanstack.com/) for data fetching on the server and proving a hydration of caching which is managed by react-query. This mechanisme is working very good without using loadable-components.

When wrapping a component (which uses react-query data fetching function) with the loadable(() => ) function, it stops working, and remains in the isLoading callback. 

### Question

What could possibly go wrong with these two libraries in combination? 
React-query is a very promising library for data fetching and server state management. 

Hopefully we can help each other out by proving some tips in the right direction. 👍 

Thanks in advance.

### Additional

If in any case a code sandbox would help you, I am more than happy to make and share one with you.

**Comment by theKashey** [comment]
It stops working properly on the server-side, or on the client-side?
Ie is it about `cache` or `initialData`?

**Comment by kevinvugts** [comment]
@theKashey 

On the client-side it stops working properly. 

When [prefetching data on the server-side](https://react-query.tanstack.com/guides/ssr#using-other-frameworks-or-custom-ssr-frameworks) and if the api call did fail the isError and error callback properties of the [useQuery hook](https://react-query.tanstack.com/reference/useQuery) are not being called.

**Comment by theKashey** [comment]
Sounds very strange. Unfortunately I don't have any loadable+react-query projects so not able to test what is not working.
I am not sure it's something we can fix, probably it's better to ask `react-query` maintainers about where they lost your cache.

**Comment by kevinvugts** [comment]
> Sounds very strange. Unfortunately I don't have any loadable+react-query projects so not able to test what is not working.
> I am not sure it's something we can fix, probably it's better to ask `react-query` maintainers about where they lost your cache.

It's not that the cache is lost. It's just stops working properly after the react-query is wrapped around a loadable component. :) 

Would a code sandbox help?

**Comment by theKashey** [comment]
Fur Sure 😉
