### ISSUE TITLE
type is invalid react testing libarary

### ISSUE THREAD

**Issue by namuwikilover** [gregberge/loadable-components#679]
## 🐛 Bug Report
'type is invalid console.error' appear, when i run jest with react testing libarary

console.error
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `InnerLoadable`.

My loadable component re export original component like this
```
import React from 'react';
import loadable from '@loadable/component';
import SimpleLoading from 'web/components/Modal/SimpleLoading';

const Loadable = loadable(() => import('.'), {
  fallback: <SimpleLoading />,
});
export default Loadable;

```

help me ㅜㅜ

**Comment by theKashey** [comment]
InnerLoadable is `forwardRef`, which is object. There are two options for you
- update packages. You might just use little obsolete versions.
- wrap Loadable `export default (props) => <Loadable {..props}/>` to hide it's _forwardRef_ nature.

**Comment by theKashey** [comment]
Related: 
- #669

**Comment by namuwikilover** [comment]
I haven't tried yet
but i think your advice will be useful, thanks a lot :)
