### ISSUE TITLE
How to use SSR

### ISSUE THREAD

**Issue by alexlabrioche** [gregberge/loadable-components#680]
## 💬 Questions and Help

Firstly I'm sorry for the poor question i'll ask...

My boss asked me to re implement our React SSR configuration to enhance code splitting. I'm looking for the SSR Example in this repo and I can't figure out why you're building a `/lib` folder and 2 distincts `/node` and `/web` folders. 

For now our SSR working in production but the entrypoint of the app is a bundled file in `/dist`... Most of the examples i see use a compiled bundle to serve the App. 

From the package.json 
```
"start": "node dist/server.bundle.js", 
"build:client": "./node_modules/webpack/bin/webpack.js --config ./webpack.config.js",
"build:server": "./node_modules/webpack/bin/webpack.js --config ./webpack.server.config.js",
```

The server is a basic Express server serving an html temlpate string, the app uses Redux and React Router. 

My first attempt was to add the chunkExtractor() et client side wait for loadableReady it worked not so well i guess because the bundle was still big. and I receive this warning message:
```
loadable: `loadableReady()` requires state, please use `getScriptTags` or `getScriptElements`
```
I try to pass the mentioned function in the html (like it's explain in the documentation) but it breaks the app.

**Comment by theKashey** [comment]
There is no real need to "bundle" stuff into different directories, for example, I bundle everything in one, just using different prefixes for client and server scripts.

If `loadableReady` is complaining - then you definitely doing something wrong. Please double-check the documentation again.

> The server is a basic Express server serving an html temlpate string, the app uses Redux and React Router.

This is worrying me a little. Loadable would not "work" without a real React "Server Side Render" in place. "html template string" does not count as SSR.
