### ISSUE TITLE
Failed to minify code from external : @loadable/component

### ISSUE THREAD

**Issue by kri7217** [gregberge/loadable-components#682]
## 🐛 Bug Report

Build fails after using @loadable/components
Failed to minify code from external : @loadable/component

## To Reproduce

Followed the same steps as per the examples.

## Info 
   "@loadable/babel-plugin": "^5.13.0",
    "@loadable/webpack-plugin": "^5.13.0"
    "@loadable/component": "^5.13.1",
    "@loadable/server": "^5.13.1"

## Link to repl or repo (highly encouraged)
https://gist.github.com/kri7217/8f87d573d92c9b7b3a94087c9e2d1f62

https://gist.github.com/kri7217/c1843f5f47e1440e7ed7bc310bde4918

Please provide a minimal repository on GitHub.

Attached my webpack config file and screenshot,
![Screenshot from 2020-12-25 16-51-22](https://user-images.githubusercontent.com/20268760/103133788-71b9a380-46d2-11eb-9d99-e28a7887a968.png)

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash

```
## Attachment
[webpackconfig.txt](https://github.com/gregberge/loadable-components/files/5743549/webpackconfig.txt)

**Comment by kri7217** [comment]
tried only with 
externals :[nodeexternals()]. Build passed
But namedChunks is always empty [ ]

*******scripttags <script id="__LOADABLE_REQUIRED_CHUNKS__" type="application/json">[]</script><script id="__LOADABLE_REQUIRED_CHUNKS___ext" type="application/json">{"namedChunks":[]}</script>

**Comment by theKashey** [comment]
You might consider filing an issue for webpack or CRA as there is nothing loadable can fix.
Technically it was already solved - https://github.com/facebook/create-react-app/issues/1125
