### ISSUE TITLE
LoadableReady not be called if required chunks have a chunk only contains css.

### ISSUE THREAD

**Issue by jas0ncn** [gregberge/loadable-components#688]
## 🐛 Bug Report

If webpack generates a chunk only contains css file, no js, loadable ready check will fail, and callback function not be called.

https://github.com/gregberge/loadable-components/blob/dde2252136a2d7f3ff635f85deff429948130883/packages/component/src/loadableReady.js#L56-L67

## To Reproduce

create a new react webpack project, just simple import css in components, add `mini-css-extract-plugin` to webpack config, insure pack a chunk only contains css file.

## Expected behavior

Filter out the chunk only contains css file when generating `RequiredChunksScriptTag`:

https://github.com/gregberge/loadable-components/blob/dde2252136a2d7f3ff635f85deff429948130883/packages/server/src/ChunkExtractor.js#L282-L284

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 11.0.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 1.62 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.15.2 - /var/folders/9t/xn8r9ffn31z6vnk1vmfdzcd00000gn/T/fnm_multishell_25701_1610416859901/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.9 - /var/folders/9t/xn8r9ffn31z6vnk1vmfdzcd00000gn/T/fnm_multishell_25701_1610416859901/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2 
 - @loadable/component: ^5.14.1 => 5.14.1 
 - @loadable/server: ^5.14.0 => 5.14.0 
 - @loadable/webpack-plugin: ^5.14.0 => 5.14.0
```

**Comment by theKashey** [comment]
😨 we rely on `jsonpCallback` to track module loading. `No js` == `no callback` == `no tracking`.
Sounds like we have to inject our code to another place, and probably in a way some particular "CSS Plugin works"

Another option - is to detect and ignore such chunks on the clientside, as they are expected to be added into HTML output during SSR. That probably would work...

**Comment by jas0ncn** [comment]
Thanks responded! The second option sounds good, the easy way to fix this issue.

**Comment by jas0ncn** [comment]
The issue will only occur when build by webpack v5.
Here is reproduce repo: https://github.com/jas0ncn/loadable-components/blob/example%2Fsingle-css-chunk/examples/single-css-chunk/README.md
And fix PR: https://github.com/gregberge/loadable-components/pull/689
