### ISSUE TITLE
esbuild plugin support

### ISSUE THREAD

**Issue by josteph** [gregberge/loadable-components#696]
## 🚀 Feature Proposal

Have [plugin support](https://esbuild.github.io/plugins/) for esbuild, in comparison to `@loadable/babel-plugin`.

## Motivation

There are other more performant build tools rather than webpack & babel, this could be the opportunity for loadable components to support react ported to non-js solutions such as esbuild (golang).

## Pitch

Basically since both esbuild supports jsx & tsx, and people are starting to adopt it into their react application.
This feature is especially aimed to SSR react app as replacement for `@loadable/babel-plugin` for esbuild, other than that this plugin might be necessary.

**Comment by theKashey** [comment]
There are code splitting solutions which are bundler independent, but there is no one which works out of the box without at least babel.
Technically speaking babel can be replaced by eslint and required code change might be generated in a little more explicit way, not behind the scenes as usual.
That would propably work with esbuild as well.

**Comment by josteph** [comment]
Hmm this is currently stated in esbuild plugins:
> This API does not intend to cover all use cases. It's not possible to hook into every part of the bundling process. For example, it's not currently possible to modify the AST directly. This restriction exists to preserve the excellent performance characteristics of esbuild as well as to avoid exposing too much API surface which would be a maintenance burden and would prevent improvements that involve changing the AST.

I agree about your statement above though, I'll try to figure it out later without using babel somehow.

To conclude, apparently for now we can just setup a babel transform that runns only to the files that are using `@loadable/components`, during the build process. Although it defeats the meaning of using esbuild in the first place.

**Comment by theKashey** [comment]
In 100k lines project, not counting roughly the same amount from node_modules, which uses code-splitting literally for everything, I have less than 10 files with dynamic imports.
applying babel transformation as a separate build step will still be very efficient from "esbuild goal" point of view. The question is how to maintain the correct dev experience.

**Comment by olso** [comment]
Hey, so no plans for esbuild?

**Comment by theKashey** [comment]
No understanding of the road, sorry. 
In the meantime, I will pursue eslint based solutions, but no promises.
