### ISSUE TITLE
[HELP] Different collected chunks, local vs heroku

### ISSUE THREAD

**Issue by olso** [gregberge/loadable-components#698]
### Checked for these differences between Heroku and my local env

- Same build process
- Same env variables (e.g. `NODE_ENV` and others checked with `printenv`)
- Same commit
- Same `node` version v14.15.4
- Same installed packages

<img width="572" alt="Screenshot 2021-02-01 at 23 35 42" src="https://user-images.githubusercontent.com/7975158/106526752-6f731200-64e6-11eb-8f53-15b4f86abe31.png">

### Top devtools
* Is what I want
* Built on localhost

### Bottom devtools
* __Not__ what I want
* Built on Heroku
* Has extra chunks loaded, MarinaDetail, CityDetail, NotFound
* Has different chunk name see `Explore`

### Yarn

```bash
├─ @loadable/babel-plugin@5.13.2
├─ @loadable/component@5.14.1
├─ @loadable/server@5.14.0
├─ @loadable/webpack-plugin@5.14.0
├─ @types/loadable__component@5.13.1
├─ @types/loadable__server@5.12.3
├─ terser-webpack-plugin@4.2.3
├─ webpack-bundle-analyzer@3.9.0
├─ webpack-cli@3.3.12
├─ webpack-dev-middleware@3.7.3
├─ webpack-dev-server@3.11.2
├─ webpack-log@2.0.0
├─ webpack-sources@1.4.3
├─ webpack@4.46.0
│  ├─ terser-webpack-plugin@1.4.5
```

How could this even happen? Where should I even start to look?

**Comment by theKashey** [comment]
Sorry, but this is related to webpack, not loadable.
- consider using content-hash for bundles, as it's a little more _stable_. https://webpack.js.org/guides/caching/#output-filenames
- if hash still will be different - please try to find the difference in content
- if that difference will be related to loadable - feel free to reopen this issue

**Comment by olso** [comment]
@theKashey 

* I'm already using content-hash
* I checked loadable-stats.json for diff see https://gist.github.com/olso/19f59ae1de39eefa702081edb5dc4035
* I checked the difference in main.js and its only due to Terser picking different character (see screenshot)

![Screenshot 2021-02-02 at 10 57 16](https://user-images.githubusercontent.com/7975158/106583556-8432c280-6545-11eb-9e77-6f23f4b61803.png)

Do you think it is still related to webpack?
