### ISSUE TITLE
Full Typescript Support

### ISSUE THREAD

**Issue by atnpcg** [gregberge/loadable-components#699]
## 🚀 Feature Proposal

a loadable component should inheritance props from original component

## Motivation
currently when using loadable components types get lost and you lose some advantages of TS

React.lazy currently works with this feature as expected

## Example
lets say that **OriginalComponent** accepts props a and b
when doing:
```
 OtherComponent = loadable(() => import('./OriginalComponent'))
```
OtherComponent should inheritance those props and work with autoComplete or throw errors if there is a missing prop

**Comment by theKashey** [comment]
it does inherit what it should, and it works well even with named exports. 
Are you sure you use proper @types/loadable?

**Comment by atnpcg** [comment]
you're right @theKashey, I never installed types, because the package already have some typescript so the compiler does not ask for it.
btw @types/loadable does not exist but `@types/loadable__component` does the trick.
probably a good idea to update docs to mention this?.

**Comment by theKashey** [comment]
Probably it's time to autoinstall these missing types.
