### ISSUE TITLE
What's the difference between outputAsset and writeToDisk for webpack plugin?

### ISSUE THREAD

**Issue by heath-freenome** [gregberge/loadable-components#700]
## 💬 Questions and Help

It seems if I don't want to have the stats file written I need to set both of them to false. At one point all I needed to do was set `writeToDisk` to false

**Comment by theKashey** [comment]
- `outputAsset` adds stat files to webpack output
-  `writeToDisk` saves file directly

When to use: in dev mode `client` not saving anything to disk, and in order to let server read stat file it has to be saved "directly".
In prod mode writeToDisk is not expected to be used.
