### ISSUE TITLE
Loading multiple resources 

### ISSUE THREAD

**Issue by stasvas** [gregberge/loadable-components#702]
## 💬 Questions and Help

Hi, first of all, thanks for your work!

I'm considering migrating `react-loadable` to `loadable-components`, but I don't understand how a feature can be implemented that will allow loading multiple resources, as `Loadable.Map` does from `react-loadable` which is used in my codebase. https://github.com/jamiebuilds/react-loadable#loading-multiple-resources

Yes, I read in the migration guide that I need to implement alternative to `Loadable.Map` on my own, but maybe someone has already done this or will tell me with a preliminary implementation?

Any clue or help is greatly appreciated!

**Comment by theKashey** [comment]
Could not provide any guidance here. I'm afraid that Component-based interfaces, the only ones exposed by this library, are not very helpful here.
At the same time, I am not sure hot `react-loadable` keeps their examples compatible with SSR. Probably just not quite.

As long as you are the first to ask for such a feature - can you shed some light on your use case to let us find the way out. Technically speaking you might need just a hook, not component, based API, but today only [react-imported-component](https://github.com/theKashey/react-imported-component) exposes such API.

**Comment by tzimmermann** [comment]
@stasvas We hit the same issue while migrating away from `react-loadable`. The solution we found in the end was creating a custom HoC like this:

```jsx
export default WrappedComponent => props => {
    const EchartsLib = loadable.lib(() =>
        import(/* webpackPrefetch: true,  webpackChunkName: "echarts" */ 'echarts')
    )
    const EchartsForReactLib = loadable.lib(() =>
        import(/* webpackPrefetch: true, webpackChunkName: "echarts" */ 'echarts-for-react')
    )
    return (
        <EchartsLib fallback={null}>
            {({ default: echarts }) => (
                <EchartsForReactLib fallback={null}>
                    {({ default: echartsForReact }) => (
                        <WrappedComponent
                            {...props}
                            echartsForReact={echartsForReact}
                            echarts={echarts}
                        />
                    )}
                </EchartsForReactLib>
            )}
        </EchartsLib>
    )
}

```

Not really nice and scalable beyond two libs, but does the job for us 😅
