### ISSUE TITLE
Placeholder for Loadable Component

### ISSUE THREAD

**Issue by jenniredfield** [gregberge/loadable-components#703]
Hi, 

I'm trying to implement a placeholder for a loadable component to reduce shifting of the page on initial load. I have tried to use your fallback property, but that causes even more shift (fallback takes a bit to appear, disappears collapsing the space where it was, then loadable component appears). 

I was thinking then to use a hook to load this component but I'm having error after error. I was wondering if using loadable component inside an useEffect is possible at all? Also, how to use the module that is returned from loadable(() => import('/someModule')) ? Just using it normally like <SomeModule  /> is not working.

```
const useLazyContainer = (): any => {
  const Fallback = () => <div style={{ minHeight: '200px' }}>Loading</div>;
  const [component, setComponent] = useState<any>(Fallback);

  useEffect(() => {
    (function loadComponent() {
      const Module = loadable(() => {
        import('./Foundit');
      });

      setComponent(Module);
    })();
  }, []);

  return component;
};
```

Then using it:

```
const SomeComponent = useLazyContainer();

return (
     <div>
       {SomeComponent}
    </div>. 
)
```

I get error:

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {$$typeof, render, preload, load}). If you meant to render a collection of children, use an array instead.

```

It seems the module object is this {$$typeof: Symbol(react.forward_ref), render: ƒ, preload: ƒ, load: ƒ} but React is refusing to render it. 

I also tried invoking SomeComponent as <SomeComponent/>

Does anyone have any ideas about how to get this working of if its possible?

**Comment by theKashey** [comment]
First, it should be `return <Component/>;`. You have to create element, not return it. Note that you have to Capitalize it as well.

Secondly, I am not sure what you are doing, and would SSR be the right answer to handle "initial load".

Lately this is code I am using to minize content shift between different pages - remeber content size of the "content" inside Suspense boundary and use old height while new data is loading.
```jsx
const [contentRef, setContentRef] = useState<HTMLElement | null>(null);
  const [contentHeight, setContentHeight] = useState("50vh");
  useResizeObserver(contentRef, (ref) => {
    if (ref.clientHeight) {
      setContentHeight(`${ref.clientHeight}px`); // <---- remember the last content size
    }
  });

  return (
      <Suspense fallback={<TransitionDivSpacer size={contentHeight} />}>
       <main className={theme.main} ref={setContentRef}>
          {children} // code splitting inside
        </main>
     </Suspense>
 )
}
```

**Comment by jenniredfield** [comment]
Hi thanks for your answer.

That's an interesting way of handling your resize between pages, thanks.

The app I'm working on however, is SSR and I can't use Suspense. The problem is that the whole page loads first but because this particular component is called like this
 
```
const SomeComponent = loadable(() => import('./SomeComponent));

```

it gets split and loads later, only showing a few seconds after first initial load (which is what we wanted, we wanted to cut initial speed load)

I wanted a fallback that appeared at first and then disappeared when the loadable component was ready. So far all I could do was to wrap the element in another div with min-height, but then I'm introducing a new div and I didn't want to do that.

**Comment by theKashey** [comment]
> The app I'm working on however, is SSR and I can't use Suspense.

Just add this code in your SSR code `React.Suspense = React.Fragment`, and all it a day :)

> loadable(() => import('./SomeComponent));

Probably there should be a flag like [ssr:false](https://loadable-components.com/docs/server-side-rendering/#disable-ssr-on-a-specific-loadable)

In this particular case I would propose do to a "multistep" render, displaying a "div" and loading some component using a `.preload` method (returning a promise) and switching to another _display_ when component will be ready to be displayed.

**Comment by jenniredfield** [comment]
Hi,

When using ``` React.Suspense = React.Fragment ``` I won't be able to use Suspense's fallback though, right?

what do you mean loading a component using a preload method? I think what you saying is what I was trying to do, but I was unsure how to do this. Can we use the loadable() function inside useEffect or something? How can we tell a loadable component has finished loading? Is there some 'hasLoaded' trigger event?

**Comment by theKashey** [comment]
> I won't be able to use Suspense's fallback though, right?

On a Server? Yes. And you don't want to. Run this override only on the server.

> Can we use the loadable() function inside useEffect or something?

```js
const MyComponent = loadable(() => import('stuff'));

const MyApp = () => {
 const [loaded, setLoaded] = useState(false);
 useEffect(() => MyComponent.preload().then(() => setLoaded(true)), []);

 return loaded ? <MyComponent /> : <div>loading...</div>
}
```

**Comment by jenniredfield** [comment]
Hey thanks for your answer. I  couldn't use preload as it was returning undefined but I used 'load' and it worked. The shift still happens though, I think because you still get one element being removed and a split second later you add the new one.

The solution for me was just using a div wrapper on this component to not let the space collapse.

Thanks for you answer, I felt I learnt something
