### ISSUE TITLE
No error handling for dynamically loaded components that don't exist

### ISSUE THREAD

**Issue by tom-prevayl** [gregberge/loadable-components#704]
## 🐛 Bug Report

We can't be sure that a dynamically loaded component exists before runtime so there should be a way to catch the error and and preferably fallback to another component

## To Reproduce

Using the client-side example: https://github.com/gregberge/loadable-components/blob/main/examples/client-side/src/index.js

1. If you set one of the buttons to setName to component C (which doesn't exist) 
`<button type="button" onClick={() => setName('C')}>`

2. Click the button

3. Error is thrown and the app crashes:
`loadable-components: failed to asynchronously load component {fileName: undefined, chunkName: undefined, error: "Cannot find module './C'"}`

## Expected behavior

It would be nice to allow a fallback component or be able to catch the error in some way.

## Link to repl or repo (highly encouraged)
 https://github.com/gregberge/loadable-components/blob/main/examples/client-side/src/index.js

**Comment by jenniredfield** [comment]
I think you can wrap the element in an error boundary (see react docs to see how to create it). Also, the import() syntax supports catch at the end in case the component fails to load - at least I was able to do this the other day and this error seemed to have disappeared! For example:

```
 Dynamic = loadable(p => import(`./${p.name}`).catch((err) => console.log(err))

```

**Comment by theKashey** [comment]
`.catch` will be _removed_ by the babel plugin. Please don't consider it as an option.
But ErrorBoundary sounds as a good idea 👍

**Comment by tom-prevayl** [comment]
ErrorBoundary would work but it still throws errors in the console. I'm not using loadable for now and I'm doing this:
