### ISSUE TITLE
How do you use it with meteor

### ISSUE THREAD

**Issue by eugle** [gregberge/loadable-components#705]
Meteor is known to have no way to configure Webpack, is there a way to use this package in Meteor and enable SSR functionality, anyone

Thank you very much

**Comment by theKashey** [comment]
Don't have any answer for you, sorry.
Pretty sure you are not expected and should not use packages like `loadable` with meteor and pick what "the platform" provides" instead. And sorry, I have not idea what Meteor can do nowadays.
