### ISSUE TITLE
Not expecting `extractor.getStyleTags()` to return empty string

### ISSUE THREAD

**Issue by suhanw** [gregberge/loadable-components#706]
### Minimum reproducible repo
https://github.com/suhanw/wp5-loadable

### What is the current behavior?
I am able to start `webpack serve` and build/start SSR server with webpack 5. 

I was looking into using Module Federation, which requires hoisting up the client-side entrypoint to a promise, click [here](https://github.com/suhanw/wp5-loadable/blob/main/client/bootstrap.js). 

But, `extractor.getStyleTags()` is returning empty string on the server side. [This](https://github.com/suhanw/wp5-loadable/blob/main/server/renderer.js) is where it's invoked. 

### What is the expected behavior?

`extractor.getStyleTags()` should return the right CSS `link` tag on the server side. 

Further, I noticed that if I don't hoist the entrypoint to a promise (comment in line 14 and comment out line 13 [here](https://github.com/suhanw/wp5-loadable/blob/main/webpack.client.config.js#L13-L14)), `extractor.getStyleTags()` returns the `link` tag for `main.css` correctly. 

I'm not sure if this is a bug. I feel like I'm just missing one thing that will make this work with the client-side entrypoint hoisting approach. Any help will be much appreciated. Happy to provide further details or clarification. 

### Package versions
![image](https://user-images.githubusercontent.com/27381522/108933419-1f84f800-7619-11eb-8a09-c2f7b0bc8e67.png)

**Comment by jenniredfield** [comment]
Hi, I could be wrong, but you seem to have a parser for css files on both webpack.client and webpack.server and the one on server doesnt seem to be using the MiniCssExtractPlugin. Why not declare this with the MiniCssExtractPlugin on the shared webpack config?

**Comment by suhanw** [comment]
@jenniredfield thanks for your suggestion. I created a new branch to declare the MiniCssExtractPlugin on the shared webpack config: https://github.com/suhanw/wp5-loadable/tree/test

I am able to start `webpack serve` and build/start the SSR server, but the page doesn't render and throws this error:
```
ReferenceError: document is not defined
    at findStylesheet (/Users/suhanwijaya/Desktop/learn/wp5-loadable/build/server/bundle.js:324:36)
    at /Users/suhanwijaya/Desktop/learn/wp5-loadable/build/server/bundle.js:341:17
    at new Promise (<anonymous>)
    at loadStylesheet (/Users/suhanwijaya/Desktop/learn/wp5-loadable/build/server/bundle.js:338:20)
    at Object.__webpack_require__.f.miniCss (/Users/suhanwijaya/Desktop/learn/wp5-loadable/build/server/bundle.js:354:58)
    at /Users/suhanwijaya/Desktop/learn/wp5-loadable/build/server/bundle.js:249:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (/Users/suhanwijaya/Desktop/learn/wp5-loadable/build/server/bundle.js:248:67)
    at _callee$ (/Users/suhanwijaya/Desktop/learn/wp5-loadable/build/server/bundle.js:72:42)
    at tryCatch (/Users/suhanwijaya/Desktop/learn/wp5-loadable/node_modules/regenerator-runtime/runtime.js:63:40)
``` 

It would be awesome if you could take a look, and let me know if I messed anything up. 😅

**Comment by jenniredfield** [comment]
I cloned your branch and I dont get any problems when I changed the webpack config client from entry point bootstrap to index.js. Why do you have to dynamically import the index of the page anyway? 🤔 :D 

```
	// entry: './client/bootstrap.js', 
	entry: './client/index.js', 

```

**Comment by suhanw** [comment]
I was looking into using Module Federation, and one of the steps is to dynamic import the client-side entry. See here: https://module-federation.github.io/blog/get-started#getting-setup-bootstrap-the-spas

**Comment by jenniredfield** [comment]
It seems the document not defined is a css loader issue (i think) I've seen people saying to use this plugin instead https://www.npmjs.com/package/extract-css-chunks-webpack-plugin/v/4.5.7 but to be honest im not expert so maybe someone else can advise you :/

**Comment by suhanw** [comment]
@jenniredfield thanks for your help in any case!

**Comment by suhanw** [comment]
bump.. ?

**Comment by suhanw** [comment]
😢

**Comment by cherreratapia** [comment]
Hi @suhanw 
Did you find the reason or a way to fix this problem? I figured out is related to the import('./bootstrap') on root but idk why
