### ISSUE TITLE
Swallowing a loadable error in an Error Boundary leads to an infinite loop

### ISSUE THREAD

**Issue by Ephem** [gregberge/loadable-components#716]
## 🐛 Bug Report (/feature request?)

If you swallow a loadable error in an error boundary and render the same tree again, loadable will try to load that chunk once more, possibly triggering the same error, and so on.

In dev, this can lead to an infinite loop, in prod builds React might unmount instead.

Context: Some lazy-loaded components are "optional", so in our app we often just want to report that they failed loading in an error boundary, but let the users keep using the page.

## To Reproduce

1. Wrap app in an error boundary that still renders `this.props.children` after chunk errors.
2. Provoke a chunk error, for example by blocking that JS-resource in the browser network tab.

## Expected behavior

If a lazy loaded component has already failed loading once, I expect the default to be to not try again. Possibly there should be an API to configure number of retries?

Today you would have to wrap every single Loadable in it's own error boundary that renders null on chunk errors, which is very verbose and cumbersome.

## Link to repl or repo (highly encouraged)

This codesandbox works by default and because of how codesandbox works you can't block the JS-resource, BUT, you can simulate a chunk error by removing the `export default` in `LazyComponent`.

https://codesandbox.io/s/loadable-components-error-handling-xh1nn

Note that in our real app, this same error happens regardless of why the chunk failed to load, so for example timeouts or blocking the resource will have the same result.

**Comment by Ephem** [comment]
This is still an active bug report/feature request.

**Comment by theKashey** [comment]
> If a lazy loaded component has already failed loading once, I expect the default to be to not try again. Possibly there should be an API to configure number of retries?

Loadable is stateless and after some component being unmounted (basically because of error thrown) it "forgets" everything.
If you want to handle this situation properly you __have__ to use [ErrorComponent](https://loadable-components.com/docs/fallback/) (let it render `null`). ErrorBoundry is just not a correct way of doing this.
