### ISSUE TITLE
Failed to asynchronously load component in DEV

### ISSUE THREAD

**Issue by yashok111** [gregberge/loadable-components#724]
After update to webpack5, i have faced issue like this in development.
<img width="615" alt="Screenshot 2021-03-24 at 13 48 43" src="https://user-images.githubusercontent.com/19926392/112290256-7c231380-8ca8-11eb-9bb9-55e248b3361d.png">

I have checked that this file exists in dist folder and available through URL

Issue happens only in dev. I use webpack-dev-server for local development.
In production build everything works fine. 

I have tried to reproduce the issue in `/examples/client-side` but everything works fine, so i can't understand what am i doing wrong in configuration.
I hope maybe someone can suggest me how to resolve this issue.

```bash
## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 2.52 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 15.11.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.6.3 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @loadable/babel-plugin: 5.13.2 => 5.13.2
 - @loadable/component: 5.14.1 => 5.14.1
 - @loadable/server: 5.14.2 => 5.14.2
 - @loadable/webpack-plugin: 5.14.2 => 5.14.2
```

**Comment by jenniredfield** [comment]
are you using new LoadablePlugin({ writeToDisk: true }) in your webpack client config?

**Comment by theKashey** [comment]
It was able to load what is needed, __but__ not execute it. There are two possible errors:
- it's trying to __call__ something not existing
- it's something about `webpack.modules[someModuleName].call` - and that's an indication of a broken (from webpack side) code splitting.

In both cases the root cause is not on loadable side.
