### ISSUE TITLE
Loadable Components raises error `SSR requires @loadable/babel-plugin, please install it` when using TypeScript `commonjs` modules.

### ISSUE THREAD

**Issue by ludovic-lambert** [gregberge/loadable-components#726]
## 🐛 Bug Report

Dynamic import of some components randomly raise `(node:12876) UnhandledPromiseRejectionWarning: Invariant Violation: loadable: SSR requires @loadable/babel-plugin, please install it` when access any page of the app in Chrome (server is starting ok) ; while others don't. The plugin is obviously installed.
Some components randomly raise the same error not when calling them but when trying to 'display source code' in Chrome.
Some components just run fine.

## To Reproduce

This component systematically raise this error when any page is called:
```
import React, { Component } from 'react'
import { IAppDictonary, IAppSetMeta, IAppUser } from '../Shared/App'
import { siteHomepage } from 'bnc-libs/lib/page'
import { Page } from '../../libs/page'

let pageMeta = new Page()
Object.assign(pageMeta, siteHomepage)

export interface IHomeProps extends IAppDictonary, IAppUser, IAppSetMeta { }

export interface IHomeStates { }

export class Home extends Component<IHomeProps, IHomeStates> {

  componentDidMount() {
    this.props.setMeta(pageMeta)
  }

  render() {
    const d = this.props.dictionary
    return (
      <div id="mainDiv" className="homepage">
        <div className="devBanner">
          <h2>{d.devInProgressTitle}</h2>
          <div className="mainDiv center bigMargin">
            <img
              id="tortoise"
              src='/i/ui/tortoise.webp' alt={d.devInProgressTitle} /><br />
            <p>{d.devInProgressText}</p>
          </div>
        </div>
      </div>
    )
  }
}

export default Home
```

Other similar components don't raise the error when displayed, but do when trying to display source code of the page in Chrome.

## Expected behavior

No error.

## System:
 - OS: Windows 10 10.0.19041
 - CPU: (4) x64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
 - Memory: 4.61 GB / 9.98 GB
## Binaries:
 - Node: 14.16.0 - D:\DEV\nodejs\node.EXE
 - npm: 6.14.11 - D:\DEV\nodejs\npm.CMD

## Config
```
"dependencies": {
    "@loadable/component": "^5.14.1",
    "@loadable/server": "^5.14.2",
    "bnc-libs": "^0.2.33",
    "cookie-parser": "^1.4.5",
    "express": "^4.17.1",
    "isomorphic-fetch": "^3.0.0",
    "lazysizes": "^5.3.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.13.10",
    "@babel/core": "^7.13.13",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/preset-react": "^7.13.13",
    "@babel/preset-typescript": "^7.13.0",
    "@loadable/babel-plugin": "^5.13.2",
    "@loadable/webpack-plugin": "^5.14.2",
    "@types/express": "^4.17.11",
    "@types/isomorphic-fetch": "0.0.35",
    "@types/loadable__component": "^5.13.3",
    "@types/loadable__server": "^5.12.3",
    "@types/node": "^14.14.37",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "@types/react-router-dom": "^5.1.7",
    "babel-loader": "^8.2.2",
    "jshint": "^2.12.0",
    "ts-node": "^9.1.1",
    "ts-node-dev": "^1.1.6",
    "typescript": "^4.2.3",
    "webpack": "^5.28.0",
    "webpack-cli": "^4.5.0",
    "webpack-node-externals": "^2.5.2"
  }
}
```

**Comment by theKashey** [comment]
Well, can you put a breakpoint there and figure out __why__ loadable complains?

https://github.com/gregberge/loadable-components/blob/3676e488a714068baca5cefad2aa98c0de0a8fab/packages/component/src/createLoadable.js#L107

If properties the code is looking for are not present - what is present instead?

**Comment by theKashey** [comment]
`ctor.requireSync` is not defined 🤷‍♂️

**Comment by ludovic-lambert** [comment]
I've seen that. So what?

**Comment by theKashey** [comment]
- if `chunkExtractor` is then, then this is a Server Side (or at least something wrapped with ChunkExtractorManager)
- if `requireSync` is not defined, then the babel plugin is not working, even if is installed

**Comment by ludovic-lambert** [comment]
From my undestanding, `babel-plugin` is used during compilation, not at run time. Do you mean the compilation raises no error but actually doesn't complete correctly?

I have no error during compilation and compiled `App.js` contains the following code:
```
const Homepage = (0,_loadable_component__WEBPACK_IMPORTED_MODULE_2__.default)({
  resolved: {},

  chunkName() {
    return "Site-Homepage";
  },

  isReady(props) {
    const key = this.resolve(props);

    if (this.resolved[key] !== true) {
      return false;
    }

    if (true) {
      return !!__webpack_require__.m[key];
    }

    return false;
  },

  importAsync: () => __webpack_require__.e(/*! import() | Site-Homepage */ "Site-Homepage").then(__webpack_require__.bind(__webpack_require__, /*! ../Site/Homepage */ "./src/client/Site/Homepage.tsx")),

  requireAsync(props) {
    const key = this.resolve(props);
    this.resolved[key] = false;
    return this.importAsync(props).then(resolved => {
      this.resolved[key] = true;
      return resolved;
    });
  },

  requireSync(props) {
    const id = this.resolve(props);

    if (true) {
      return __webpack_require__(id);
    }

    return eval('module.require')(id);
  },

  resolve() {
    if (true) {
      return /*require.resolve*/(/*! ../Site/Homepage */ "./src/client/Site/Homepage.tsx");
    }

    return eval('require.resolve')("../Site/Homepage");
  }

}, {
  ssr: true,
  fallback: /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0__.createElement(_Shared_Parts_SpinLoader__WEBPACK_IMPORTED_MODULE_14__.default, null)
});
```
Is this not generated by the `babel-plugin`?

Also, once executed client-side, all dynamic imports, ie `const X= loadable(() => import('X'), { ssr: true, fallback: <SpinLoader /> })`, are working fine. The error occurs only during server-side rendering.

This work:
```
loadableReady(() => { hydrate(<BrowserRouter><App /></BrowserRouter>, appRoot) })
```

This don't:
```
const statsFile = path.resolve(`${process.env.APP_ROOT}${path.sep}public${path.sep}js${path.sep}loadable-stats.json`)
const extractor = new ChunkExtractor({ statsFile, publicPath: '/js' })
const jsx = extractor.collectChunks(<StaticRouter location={`/${this.requestedPage.uri}`} context={{}}><App /></StaticRouter>)
scriptTags = extractor.getScriptTags()
const ssrApp = renderToString(jsx)
```

**Comment by theKashey** [comment]
Ok. So now we know that problem occurs on the server-side, not the client-side. However, it is still unclear for which compilation target the given piece of code belongs.
Obviously not to the one with the _missing_ `requireSync`.

👉 babel plugin is required both for client and the server-side. If it will be missing - no error will occur during the compilation as long as the "your code" is correct by design (not generating any typescript errors). It will be just not consumable by loadable-components.

**Comment by ludovic-lambert** [comment]
Any piece of code containing `const X= loadable(() => import('../X'), { ssr: true, fallback: <Whatever /> })`  with X called during initial request raise this error, on server-side only. Everything is installed correctly, and particularly `@lodable/babel-plugin`.

**Comment by vancityhuddy** [comment]
I am also experiencing this issue. Loading endpoints that use Loadable are throwing this strange "SSR requires `@loadable/babel-plugin`"

Any progress made here @ludovic-lambert ?

**Comment by ludovic-lambert** [comment]
@vancityhuddy Unfortunately, no. My code just works nicely without loadable-components, and crashes with it. The error message is meaningless as the plugin is installed. Except getting deeply into loadable-components source code, which is beyond my skills, I don't know what to do.

**Comment by theKashey** [comment]
Beyond mine as well. It should work.
There are just a few lines that can work weirdly, and if you make me a minimal reproduction of your problem/setup - I should be able to help you.

**Comment by denchiklut** [comment]
the problem is in tsconfig.json
when you use module: commonjs!

if you try to change it to es2020 for example the error will gone

**Comment by theKashey** [comment]
Bingo. Absolutely correct @denchiklut: babel plugin looks for the variable with name "loadable" ( https://github.com/gregberge/loadable-components/blob/main/packages/babel-plugin/src/index.js#L39) and CJS transformation "renames" it.

**Comment by denchiklut** [comment]
@theKashey is there any chance to fix @loadable/babel-plugin to work with commonjs?

**Comment by negomansini** [comment]
Having this problem as well. Still not figured it out.

**Comment by theKashey** [comment]
Can I double-check where commonjs is coming from?
All tools are expected __not to change__ module system, and only the last one (`webpack`) to do expected transform.

So:
- tsconfig: "module": "ESNext",
- babel: `modules:false`
- webpack: does the transformation

> Don't forget to undo this for Jest/another testing framework, running without webpack.

**Comment by jjblumenfeld** [comment]
We are experiencing the same issue. We are using commonJS modules and are doing SSR using our own expressJS server on node v12.

**Comment by denchiklut** [comment]
@theKashey is there any way to make this plugin work with commonjs?

**Comment by theKashey** [comment]
you __have__ to use `import` in order to have code splitting with webpack. So the input is always expected to be non `commonjs`.

**Comment by denchiklut** [comment]
> you __have__ to use `import` in order to have code splitting with webpack. So the input is always expected to be non `commonjs`.

Yeah and on client I use esmodules but my express server where I use ChunkExtractor I use commonjs

**Comment by ludovic-lambert** [comment]
> you **have** to use `import` in order to have code splitting with webpack. So the input is always expected to be non `commonjs`.

Actually the code itself shall be `es6` to use `import` while node module could be anything like `commonjs`, meanwhile compilation target could be yet something else.

In typescript configuration parameters are clearly different:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  }
}
```

**Comment by theKashey** [comment]
Exactly. Compilation target (for babel) can be anything - it's all about the "source code".
In case of TS - it shall just do "a check".

One of the simplest ways to handle this - use babel-loader for ts + ForkTSCheckPlugin. Or, as pointed above, amend default tsconfig. 
PS: Ideally add `jsx: "preserve"` as well, to remove all "real transformations" from TS.
