### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by OSamkova** [gregberge/loadable-components#733]
## 🐛 Bug Report

We're deploying loadable components to a server that is not NODE_ENV=production, but does not support HMR. We only need the modules loaded once into the cache, and it seems that reloading does indeed leak memory. Tying that functionality to how NODE_ENV is set makes a pretty strict assumption about how users would expect loadable components to behave in all non-production environments.

**Comment by theKashey** [comment]
The main message is - "clearModuleCache is not clearing the cache" - causing memory leak.
Once upon a time (https://github.com/gregberge/loadable-components/pull/567) it was specially added to address this problem, so - are you sure there is a leak, and it is there, and your fix is fixing it?
