### ISSUE TITLE
Gatsby loadable-components default

### ISSUE THREAD

**Issue by tnorlund** [gregberge/loadable-components#736]
I've recently [implemented](https://github.com/tnorlund/Blog/blob/master/src/components/Global/index.js) loadable-components on my Gatsby-powered blog. I'd like to default to just an empty div with the same height and width while the component is loading. Is there a way to do that? I can do it uses React.lazy and React.suspense, but SSR isn't really supported yet.

```js
import React from 'react'
import { MDXProvider } from '@mdx-js/react'
import Scroll from '../Scroll'
import { DocsGrid } from '../styles'
import loadable from '@loadable/component'

const components = {
  DocsGrid,
  Analytics: loadable( () => import( `components/Flow/Analytics` ) ),
...
}

export const Providers = ( { children } ) => (
  <MDXProvider components={components}>
    {children}
    <Scroll showBelow={1500} css="position: fixed; right: 1em; bottom: 1em;" />
  </MDXProvider>
)
```

**Comment by theKashey** [comment]
> I'd like to default to just an empty div with the same height and width

To the same height and width as what?
Resently I've implemented a "smart placeholder" which keeps the size of a previously mounted component while the new one is loading (to prevent scroll bar trashing), but it's all about using the "old" data, as I don't know the "new" one.

**Comment by tnorlund** [comment]
So if I'm loading a complex SVG element with height of 300pt and a width of 200pt, I'd like to have a placeholder div in its place of the same size. 

This would be used to keep the scroll bar static.

**Comment by theKashey** [comment]
`Loadable` cannot do that a they did not _imported_ component yet to know how it should look like.
Code splitting that all, 100% of the code behind import did not exists unless you import it.

**Comment by tnorlund** [comment]
I don't know if we're talking about the same thing.  I can lazily load React components using the newest version of React. Before the component loads, I can fallback to a div with a specific height. This retains the scroll position when the components is finished loading. Can I do this with loadable-components? 

Here is an example of what I'm able to do with a standard Gatsby page.

```js
...
/** Use React Suspense and Lazy to speed up import */
const Adobe = React.lazy( () => import( `components/Icons/Adobe` ) )
...
export default function Page() {
  const isSSR = typeof window === `undefined`
  return <>
    {!isSSR && <React.Suspense fallback={<div height={`200pt`}></div>}><Adobe /></React.Suspense> }
  </>
}
```

**Comment by theKashey** [comment]
Ok - __you can do it__, using the same Suspense(if [async mode is enabled](https://loadable-components.com/docs/suspense/)), or using [custom fallback](https://loadable-components.com/docs/fallback/).

**Comment by tnorlund** [comment]
Ok. The custom fallback was what I was looking for. Thanks for the help.
