### ISSUE TITLE
Update to latest Babel

### ISSUE THREAD

**Issue by blordpluto** [gregberge/loadable-components#739]
The babel runtime referenced here is different from the latest one my app needs to use. This results in multiple versions, which is not optimal. Would appreciate a bump to latest babel in the next release.

Thank you for maintaining this, it's an essential tool!

**Comment by theKashey** [comment]
Loadable components does not _depends_ on babel - only for `babel-plugin` there is a [peerDependency](https://github.com/gregberge/loadable-components/blob/main/packages/babel-plugin/package.json#L31) for `"@babel/core": "^7.0.0-0"`

There is no way we can "fix" your problem as well as "upgrade" babel
