### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by gita-codaio** [gregberge/loadable-components#741]
## 🐛 Bug Report

V15.14.1

## To Reproduce

Unable to install the latest version (15.14.2) of @loadable/component
It seems that version 15.14.2 is not on https://www.npmjs.com/package/@loadable/component

## Expected behavior

To be able to install 15.14.2
I think it is because there is missing version and name in the package.json

**Comment by theKashey** [comment]
Not sure was it a problem before, but it's not a problem for 5.15
https://unpkg.com/browse/@loadable/component@5.15.0/package.json
