### ISSUE TITLE
Loadable Components Does not seem to work on ios versions < 14.0

### ISSUE THREAD

**Issue by kevinvugts** [gregberge/loadable-components#742]
## 🐛 Bug Report

After testing my website (react app) with browserstack I found out that my app crashes on IOS versions < 14.0.
The error I am getting is:

```
SyntaxError: Unexpected token '?'(anonymous function) @ pages-Configurator-Services.9808dfc7936d82d917d0.bundle.js:1
main.db24fa2….bundle.js:2 loadable-components: failed to asynchronously load component  
```

**Steps to reproduce the behavior:**
1. Open my website https://www.apkstationgoirle.nl
2. Navigate via the license plate input (enter 25SJJN) and click the blue next button.
3. Loadable error occurs in console

## Expected behavior
I am expecting loadable components to be compatible with all versions of os systems? 
I will post my webpack config here as well.

Webpack config: (client/server/common) https://pastebin.com/auS4TMZB
Reproduction link: https://www.apkstationgoirle.nl (check console.log)

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
 - Memory: 51.87 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.20.1 - /usr/local/opt/node@12/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.7 - ~/.npm/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2 
 - @loadable/component: ^5.14.1 => 5.14.1 
 - @loadable/server: ^5.14.0 => 5.14.2 
 - @loadable/webpack-plugin: ^5.14.0 => 5.14.2 
```

**Comment by theKashey** [comment]
Sorry, this is not a `loadable components` bug - they just report the error that happened during the loading of your script.

The description given seem to be related to the `nullish coalescing` (.?) not transpiled to the lower target.
- Please check your bundler, babel or typescript settings.
- Please disable minification of the code to be able to see the exact place and code causing the error

**Comment by kevinvugts** [comment]
@theKashey I do think this is loadable related. I am also getting the following: 

```
ChunkLoadError: Loading chunk 707 failed
Loading chunk 707 failed.↵(missing: https://www.ap…igurator-Services.9808dfc7936d82d917d0.bundle.js)
```

**Comment by theKashey** [comment]
this is not a loadable error, this is webpack reporting a failure.

Let me be clear - loadable __does nothing special__, it just connects a few other bits and pieces, like commanding webpack to load a chunk when needed. This functionality works, and the rest is not loadable responsibility.

**Comment by kevinvugts** [comment]
Okey @theKashey,

Thank you anyway. I will try to debug the webpack error.

**Comment by damechen** [comment]
How did you solve your issue Kevin?

**Comment by theKashey** [comment]
What you can do in order to debug this issue:
- configure webpack to NOT codesplit (multiple ways, usually this condifuration is used for server-side bundles)
- run your application. In case of any error in your code, and I think there is something about under-transpiling some stuff, it will be easy to catch the problem.

But in any case - this is the browser not able to load your code. Nothing to fix from loadable, or even webpack level. Start looking at babel config.

**Comment by kevinvugts** [comment]
> How did you solve your issue Kevin?

Hi,

like @theKashey stated, this is probably related to a webpack / babel misconfiguration.
