### ISSUE TITLE
Loadable in TypeScript

### ISSUE THREAD

**Issue by tnorlund** [gregberge/loadable-components#744]
I've recently switched to TypeScript; with that, a bunch of errors have appeared.

I was able to split it up before, but I'd like to ask for a recommendation. How would you guys lazily load these components using Gatsby?

I'm currently getting this error on all of my lazily loaded imports using loadable:
> No overload matches this call.

What's the proper way to handle this?

```tsx
import loadable from '@loadable/component'
...
const components = {
  Analytics: loadable(
    () => import( `../MyIcons/Analytics` ),
    { fallback: <div style={{ height:`400pt` }}/> }
  ),
...
}
...
/**
 * @typedef ProvidersProps
 * @param {JSX.Element} children
 */
 interface ProvidersProps {
  children: JSX.Element
}
export const Providers = ( { children }: ProvidersProps ) => (
  <MDXProvider components={components}>
    {children}
    <Scroll showBelow={1500} css="position: fixed; right: 1em; bottom: 1em;" />
  </MDXProvider>
)
```

**Comment by theKashey** [comment]
Sorry @tnorlund - where exactly you are getting the error? Which piece complains?

**Comment by tnorlund** [comment]
> Sorry @tnorlund - where exactly you are getting the error? Which piece complains?

The error is everywhere I now call loadable:
```tsx
Analytics: loadable(
  () => import( `../MyIcons/Analytics` ),
  { fallback: <div style={{ height:`400pt` }}/> }
)
```

The error is 
> No overload matches this call.
>  Overload 1 of 3, '(loadFn: (props: unknown) => Promise<typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")>, options: OptionsWithResolver<unknown, typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")>): LoadableComponent<...>', gave the following error.
    Argument of type '{ fallback: JSX.Element; }' is not assignable to parameter of type 'OptionsWithResolver<unknown, typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")>'.
      Property 'resolveComponent' is missing in type '{ fallback: JSX.Element; }' but required in type 'OptionsWithResolver<unknown, typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")>'.
  Overload 2 of 3, '(loadFn: (props: unknown) => Promise<DefaultComponent<unknown>>, options?: OptionsWithoutResolver<unknown> | undefined): LoadableComponent<unknown>', gave the following error.
    Type 'Promise<typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")>' is not assignable to type 'Promise<DefaultComponent<unknown>>'.
      Type 'typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")' is not assignable to type 'DefaultComponent<unknown>'.
        Property 'default' is missing in type 'typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")' but required in type 'DefaultImportedComponent<unknown>'.
  Overload 3 of 3, '(loadFn: (props: any) => Promise<ComponentClass<any, any> | { default: ComponentClass<any, any>; }>, options?: Options<any, ComponentClass<any, any>> | undefined): LoadableClassComponent<...>', gave the following error.
    Type 'Promise<typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")>' is not assignable to type 'Promise<ComponentClass<any, any> | { default: ComponentClass<any, any>; }>'.
      Type 'typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")' is not assignable to type 'ComponentClass<any, any> | { default: ComponentClass<any, any>; }'.
        Property 'default' is missing in type 'typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")' but required in type '{ default: ComponentClass<any, any>; }'.ts(2769)

**Comment by theKashey** [comment]
Sorry, but `Property 'default' is missing in type 'typeof import("/Users/tnorlund/Blog/src/components/MyIcons/Analytics/index")'`
