### ISSUE TITLE
Fallback overlaps HTML from ssr

### ISSUE THREAD

**Issue by ops1ops** [gregberge/loadable-components#748]
Hello, im using loadable with [rails ssr](https://github.com/reactjs/react-rails#server-side-rendering), so i faced the problem when my html being loaded for a while and then loadable shows fallback (so whole html become white), so question is can i disable this behavior or maybe im missing something in cofiguration

**Comment by theKashey** [comment]
Sounds like you are not waiting for `loadableReady`

**Comment by ops1ops** [comment]
@theKashey you mean that i should mount (hydrate) my components in passed callback of loadableReady (according to example with NodeJS SSR), but if i do this how to start loading components? I mean when i mount components -> loadable starts working and fetching chunks, but if i move it to loadableReady, chunks are not event loaded

**Comment by theKashey** [comment]
That's all correct - you have to configure ChunkExtractor on the server and wait using `loadableReady` for their load.
Sounds like you've skipped 2 most major steps for SSR :)

**Comment by ops1ops** [comment]
Thanks for help, closing the issue

**Comment by aligulen** [comment]
it seems that fallback makes hydration borken. 
Before script fully loaded fallback changes html structure (in order prevent showing empty page) but  it puts something else from SSR and then react hydration broken because html totally changed.

**Comment by theKashey** [comment]
this is true for React<17. One has to use `fallback={null}` for any Suspense boundaries during the initial hydration.
For React>=17, with "server side Suspense", no such magic is required.

The issue affects all React versions after 16.10 - https://github.com/atlassian-labs/react-loosely-lazy/issues/46
