### ISSUE TITLE
[webpack-plugin] How to ignore an entrypoint with the plugin-webpack?

### ISSUE THREAD

**Issue by bertho-zero** [gregberge/loadable-components#751]
How to ignore an entrypoint with the plugin-webpack?

In my webpack config I have 2 entrypoints, my app and a script called 'outdated' which displays a banner when the browser is too old.

I would like this script to be ignored by the webpack plugin, currently I have to put it in the entrypoints of the ChunkExtractor for it to run. It must be executed before and independently of everything else.

With this config my script is loaded (manually) but never executed:
```js
const extractor = new ChunkExtractor({
  statsFile: path.join(__dirname, '/dist/loadable-stats.json'),
  entrypoints: ['webapp'],
  publicPath,
});
```

It works well with this config but the extractor does not have to know this script.

```js
const extractor = new ChunkExtractor({
  statsFile: path.join(__dirname, '/dist/loadable-stats.json'),
  entrypoints: ['outdated', 'webapp'],
  publicPath,
});
```

EDIT: I don't know if it's related to the webpack plugin and I don't understand why I need to add my entrypoint a second time in ChunkExtractor, I need to just add a <script> in my html.

**Comment by bertho-zero** [comment]
Ok, I gave a small $5 :)

https://opencollective.com/loadable/donate/success?OrderId=k3z8arxv-eymko60l-xj86gl5n-bj9w704d&email=kevin.bertho%40gmail.com

**Comment by bertho-zero** [comment]
The problem is that the plugin changes the webpack config for all entry points.

https://github.com/gregberge/loadable-components/blob/main/packages/webpack-plugin/src/index.js#L92-L96

The ideal would be to be able to filter the entry points to be processed with the plugin.

**Comment by theKashey** [comment]
> The ideal would be to be able to filter the entry points to be processed with the plugin.

That is not possible, but you can do another thing, which might work better for you - run webpack twice, something known as a multi-compiler mode 
- https://webpack.js.org/api/node/#multicompiler
- https://stackoverflow.com/questions/29640996/webpack-with-an-array-provided-as-config

**Comment by bertho-zero** [comment]
It takes twice as long, the process never stops after the successfully log and I have a webpack warning that cannot write the cache.

I am however sure of my modifications, there is nothing complicated but it is buggy.
