### ISSUE TITLE
ReactJS.net - document is not defined

### ISSUE THREAD

**Issue by LorenDorez** [gregberge/loadable-components#754]
## 💬 Questions and Help

I am using ReactJS.net for our SSR. When trying to use loadable-components im getting a error 

ReferenceError: 'document' is not defined
   at requireEnsure (Server.b2d04b7c5864151519e5.min.js:95:14)
   at requireAsync (eval code:61:5)
   at InnerLoadable (eval code:177:11)
   at processChild (eval code:2994:7)
   at resolve (eval code:2959:5)
   at render (eval code:3434:7)
   at read (eval code:3372:11)
   at renderToString (eval code:3987:5)
   at Global code (Script Document [4]:1:1)

I have narrowed this down to something in the ChunkExtractor.  Is there something im missing?

The code that essentially is getting executed is something like this

```
ReactDOMServer.renderToString(extractor.collectChunks(React.createElement(HeaderView, {myProps})))
```

I have tried this with a very simple component that just renders a DIV. So nothing in my react is calling `document.`

**Comment by LorenDorez** [comment]
I feel like my loadable-stats.json file is botched. 

I cant seen anything in there that links my chunked file to the main entry point. Essentially on the Server build i render 1 JS file that has all of the React & components etc.. and it chunked out the loadable file correctly leaving me with 2 entry files..

Names are not exact to protected the innocent :P
1. Server.js
2. Chunk.js

But in the stats file there is nothing that links those 2 together at all

**Comment by LorenDorez** [comment]
So it looks like my stats file isnt being generated with the chunk.

```
"HeaderView": {
      "chunks": [
        "runtime",
        "react",
        "HeaderView"
      ],
      "assets": [
        "runtime.min.js",
        "react.min.js",
        "HeaderView.min.js"
      ],
      "children": {},
      "childAssets": {}
    },
```

There should be a chunk for `Components-Header-TradeSitesHeader-TradeSitesHeader.min.js`.

Ill try to see if i can figure out whats causing that. Might be something in the babel config

**Comment by LorenDorez** [comment]
So looks like chunks are completely missing from the loadable-stat.json file. If i dump the stats file myself they are there. Closing this until i can track that a bit more

**Comment by theKashey** [comment]
`'document' is not defined` means - document is not defined. That is all.

You are trying to access `document`, which exists only in the browser, during SSR process. Thus the exception.

**Comment by LorenDorez** [comment]
The issue was nothing I was doing was accessing the document. It was in one of the dependencies of the ChunkExtractor but was do because the chunks section in the JSON file for some reason was empty. When I rebuild the project/setup from a fresh backup the issue went away once chunks was showing in the JSON.
