### ISSUE TITLE
SSR question

### ISSUE THREAD

**Issue by undrafted** [gregberge/loadable-components#765]
## 💬 Questions and Help

Hi, first of all thanks for your work on this project.

 I've been trying to implement the loadable-components SSR in our projects by looking at the docs and the example, but can someone explain the flow of how SSR works in this library?

From what I see, the approach taken could be: On a server setting, if the component is wrapped inside a loadable, the server should still import it just like a normal import so renderToString works OK.

I'm sure there are reasons why we need to use loadable-stats, ChunkExtractors, etc. but to put more simply, why does the library care about the chunks generated on SSR? In the end the purpose of the library is to dynamically import components (JS files), so we would not add the "loadable components" script tags on the html template.

**Comment by theKashey** [comment]
With code splitting everything you've used during SSR should be there on the client before the hydration, or you will loose some pieces of already rendered application.

This is the main reason why loadable-components exist, and why they need loadable-stats - to load all required chunks before you start the application.

Frankly speaking this is just one way to implement it, and [imported-components](https://github.com/theKashey/react-imported-component), for example, does not require stats/extractor, while can still benefit from it.

**Comment by undrafted** [comment]
Thanks. Will check out the library you shared. You have a lot of cool stuff 👌
