### ISSUE TITLE
Component.preload() doesn't work?

### ISSUE THREAD

**Issue by ozgrozer** [gregberge/loadable-components#783]
Hi, I was using `react-loadable` before but since it's not maintaining anymore I gave a chance to `@loadable/component`.
The code below was working with `react-loadable` but doesn't work with `@loadable/component`.
When I hover my mouse onto a link, it doesn't load the component.
I thought it might be a bug but maybe I'm doing something wrong.

Here's my code. So is there anything wrong?

```jsx
import React from 'react'
import loadable from '@loadable/component'
import { NavLink } from 'react-router-dom'

const Component = loadable(() => import('./Component'))

export default () => {
  return (
    <NavLink to='/' onMouseOver={() => Component.preload()}>
      Component
    </NavLink>
  )
}
```

**Comment by theKashey** [comment]
Probably because you are rendering `Component` as a __string__, not as a __Component__

**Comment by ozgrozer** [comment]
I used it as described in this page.

https://loadable-components.com/docs/prefetching/#manually-preload-a-component

**Comment by theKashey** [comment]
In this case the problem is with `onMouseOver`
Can you try to add some debug information somewhere:
- `console.log` at `onMouseOver`
- `console.log` somewhere at `./Component`, which should be printed when code will be preloaded.

**Comment by ozgrozer** [comment]
When I try like this, console logs are working on mouse over but not the one in `Component`.

```jsx
<NavLink
  to='/'
  onMouseOver={() => {
    console.log('1')
    Component.preload()
    console.log('2')
  }}
>
```

I also made a demo here for you to check.
https://codesandbox.io/s/confident-mirzakhani-fulmn?file=/src/index.js

**Comment by theKashey** [comment]
Everything is working perfectly - https://codesandbox.io/s/quizzical-maxwell-qb42x?file=/src/Contact.jsx

**Comment by ozgrozer** [comment]
I think something might be wrong with my local setup. I'm actually using `parcel-builder` instead of `react-scripts`. I've used Parcel in the project below and looks like it's working. But I can't get the `Contact loaded` message in my local console. It's the same code. I don't understand what's wrong.

https://codesandbox.io/s/cool-wiles-frglv?file=/package.json
