### ISSUE TITLE
object is undefined

### ISSUE THREAD

**Issue by martingg88** [gregberge/loadable-components#789]
I do have class view.js like this

View.js
var View = {
       test: function(){ console.log('abc'); }
}

export default View;

i get Undefined issue when calling like this. 

const View = loadable(() => import('react-laravel'));

View.test

**Comment by theKashey** [comment]
Please refer to the documentation to understand what loadable can and supposed to do.
Please also provide more information on what you trying to achieve, and provided code has no sense.

Feel free to create a new issue __following__ the issue template.
