### ISSUE TITLE
Warning or error when trying to transpile a function without losing business logic

### ISSUE THREAD

**Issue by NicoBurno** [gregberge/loadable-components#796]
## 🚀 Feature Proposal

Warning or error when trying to transpile a function without losing business logic

## Motivation

We used additional business logic for loading a chunk in the `loadFn`, and everything worked well until we included `@loadable/babel-plugin`
We had an application crashing for a long time when trying to resolve the same component
If there was a warning or an error about the impossibility of transpiling the function code without breaking the business logic, we would have discovered the problem much earlier.

## Example

An attempt to transpile such a function should cause warning or an error:

```TypeScript
async function load(context: IApplicationContext) {
  const fragmentsPromise = loadFragmentsAPI(context);
  const { runApp } = await import('../runApp');
  const mdl = await runApp(context);
  await fragmentsPromise;

  return mdl.default;
}
```

**Comment by NicoBurno** [comment]
We could help with the implementation within our postmortem
We can also try to support synchronous code for transpile

**Comment by theKashey** [comment]
This was a part of [this PR](https://github.com/gregberge/loadable-components/pull/511/files#diff-1163b5c512efeae5d242ceebb975fa164a5f2ad395a1c083cf00de7595504b2aR124) which has not being implemented.

But probably this is what you are looking for.

**Comment by NicoBurno** [comment]
Yes, that's what we need
We can cherry-pick a [commit](https://github.com/gregberge/loadable-components/pull/511/commits/85b5f45e9662ac0d3eefb27a35e37e535f878449) with exception for a separate PR

Since all functions other than just import functions are unsupported functions, can we release this with a patch version?

**Comment by theKashey** [comment]
Definitely not a patch as it can be a __breaking change__ for someone.

So technically speaking, even if SSR was/is/will never work with "custom logic" in import - CSR is ok, and we need an option for babel plugin (not active by default) to disable this check and keep everything as it was.
