### ISSUE TITLE
webpackChunkName invalid

### ISSUE THREAD

**Issue by undeadfrost** [gregberge/loadable-components#797]
## 🐛 Bug Report

Use @loadable/webpack-plugin for packaging and introduce components in the following way
`const Home = loadable(() => import(/* webpackChunkName: "my-chunk-name" */ '@mobile/pages/Home'));`
But after packaging, the file name is still `xxx-bundle-xxxxx.js` It seems that the configured file name does not take effect.

I use`"webpack": "^5.36.2",`

## To Reproduce

Generate a file according to the specified name.

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 1.27 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
 - Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
## npmPackages:
 - @loadable/component: ^5.15.0 => 5.15.0 
 - @loadable/server: ^5.15.0 => 5.15.0 
 - @loadable/webpack-plugin: ^5.15.0 => 5.15.0 
```

**Comment by theKashey** [comment]
Related: #750. Webpack chunk naming is not always controllable
