### ISSUE TITLE
Getting Loadable Chunks when using renderToString , but not when using renderToNodeStream

### ISSUE THREAD

**Issue by prince267** [gregberge/loadable-components#800]
when using renderToString in react SSR, Loadable component is giving proper route based chunks. but when i change renderToString to renderToNodeStream, I'm not getting route based chunks. 
![Screenshot from 2021-07-12 11-36-07](https://user-images.githubusercontent.com/31069419/125239435-4745d580-e306-11eb-80d1-a43970dd028c.png)

![Screenshot from 2021-07-12 11-40-20](https://user-images.githubusercontent.com/31069419/125239470-5167d400-e306-11eb-86a5-a2a14029f8ca.png)

**Comment by theKashey** [comment]
Correct. Yep this is how it expected to work work with a little async renderToStream and in order to fix the problem let’s look at your code, not it’s behaviour first.

**Comment by prince267** [comment]
![Screenshot from 2021-07-16 12-00-25](https://user-images.githubusercontent.com/31069419/125902713-f72f546b-c0f6-4998-aab2-8f755f7fbe82.png)

**Comment by prince267** [comment]
in this code i just replace renderToString with renderToNodeStream

**Comment by prince267** [comment]
How i can get chunks file while using renderToNodeStream.

**Comment by theKashey** [comment]
😉 you need to wait for the stream end, which basically makes `renderToNodeStream` completely useless.
Well, not exactly true, as one can just first pipe all HTML from `renderToNodeStream` and then complete the picture dumping extracted scripts and styles, however styles are not working this way as has to be in the response before HTML they expected to style.

If you need a bit more _streaming_ streaming support - take a look at (react-imported-component)[https://github.com/theKashey/react-imported-component]

**Comment by prince267** [comment]
now get script tags. at stream.end . is there any method in loadable components to get the dynamic critical css.
Please have a look in this https://stackoverflow.com/questions/67900722/how-do-i-collect-critical-css-for-chunks-of-rendertonodestream-react-ssr

**Comment by theKashey** [comment]
- How to get script tags
```
const stream = renderToStream(
    <YourApp />
);

stream.pipe(res, { end: false });
stream.on('end', () =>
    res.end(doSomethingMoreLikeDumpingScripts); // 👈
)
```

- CSS. 
Answered at stackoverflow, but in short use https://github.com/theKashey/used-styles
