### ISSUE TITLE
lazy not using fallback without Suspense

### ISSUE THREAD

**Issue by Zanoro9000** [gregberge/loadable-components#801]
Hello! I am currently in the process of converting to loadable-components. 

I ran into an issue where I am trying to use `lazy` without `Suspense` and I get an error that there is no fallback supplied, even though I am using it like below: 

```
export function LazyLoader({ component }: any) {
  return lazy(() => pMinDelay(component(), 200), {
    fallback: <LoadingComponent />,
  });
}
```

and calling it like 

```
const Comp = LazyLoader({
  component: () => import('path/to/component.jsx'),
});
```

If I add a Suspense around component, it does not error out and works fine, but I would like to be able to do it without suspense currently as Enzyme does not play nice with Suspense yet. Am I doing something wrong or does lazy not support an in-place fallback?

Thanks!

**Comment by theKashey** [comment]
You cannot two both things you are doing here:
- you cannot use `lazy` without a corresponding `<Suspense fallback="..."`.
- you cannot _hide_ `lazy` behind `LazyLoader`, except this use case - https://loadable-components.com/docs/babel-plugin/#loadable-detection
