### ISSUE TITLE
Error with loadable component while import from another directory

### ISSUE THREAD

**Issue by danarish4** [gregberge/loadable-components#804]
## 🐛 Bug Report

When trying to import some component that is not located in the same directory babel plugin transpile the wrong path inside `resolve`.
I'm using loadable this way in my code:
`const Comp = loadable(() => import('./components/OtherComponent'))`

I'm getting this error while trying to run the code:

`Module not found: Can't resolve './components/OtherComponent' in '/node_modules/dist/loadable/viewer/es'`

My dist directory includes the next files:
OtherComponent.js
loadable.js
loadable2.js

When I'm looking at the `loadable2.js` bundled file I see 
```
  OtherComponent = loadable({
    resolved: {},
    chunkName: function() {
      return 'components-OtherComponent';
    },
    isReady: ...,
    importAsync: function() {
      return import(
        /* webpackChunkName: "components-OtherComponent" */
        './OtherComponent.js'
      );
    },
    requireAsync: ....,
    requireSync: .....,
    resolve: function resolve() {
      return require.resolveWeak
        ? require.resolveWeak('./components/OtherComponent')
        : eval('require.resolve')('./components/OtherComponent');
    },
  }),
```

You can see that babel-plugin compute the right path for `importAsync` but the wrong path for `resolve`

## Expected behavior

`resolve` will use the same path like `importAsync`.

## Link to repl or repo (highly encouraged)

This is a link to my project where loadable files
https://github.com/wix/ricos/blob/master/packages/plugin-divider/web/src/typeMapper-loadable.ts

This is my loadable entry:
https://github.com/wix/ricos/blob/master/packages/plugin-divider/web/loadable/viewer/package.json

This is how I confined babel:
https://github.com/wix/ricos/blob/master/babel.config.js#L19

And this is our rollup:
https://github.com/wix/ricos/blob/master/rollup.config.common.ts#L75

**Comment by theKashey** [comment]
> You can see that babel-plugin compute the right path for importAsync but the wrong path for resolve

However, having that
> I'm using loadable this way in my code:
`const Comp = loadable(() => import('./components/OtherComponent'))`

`'./components/OtherComponent'` is the correct path, and is _transferred_ to `resolve` "as-is", while `import` has a wrong one.

-----

@danarish4 - can you clarify why paths at the result bundle are expected to be a little different from the original one?
