### ISSUE TITLE
DOM Elements thrown away during hydration

### ISSUE THREAD

**Issue by krishnaglick** [gregberge/loadable-components#805]
## 🐛 Bug Report

During hydration my application does the following:
* SSR happens, and the page gets cached.
* Page is later hit _n_ minutes after.
* Hydration occurs and during hydration the app recognizes one piece of the dom has old data, which we do not want to show, so that component returns null. Additionally that component goes to fetch fresh data.
* The components hydrate and pieces are placed into incorrect containers.
* The out of date data is refreshed, causing the component to reappear in the wrong place.

It's worth noting that with react-lazy this functionality seems to work as expected. The issue there is react-lazy is incredibly out of date and I had to edit its js files to make it work correctly with webpack. There is a branch up [here](https://github.com/krishnaglick/hydration-error/tree/react-lazy) using it but I didn't want to go through the headache of forking, etc.

## To Reproduce

* Clone my repo
* yarn dev
* Render page with and without javascript enabled.

## Expected behavior

Excess dom elements are properly rendered

## Link to repl or repo (highly encouraged)
https://github.com/krishnaglick/hydration-error

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
 - CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
 - Memory: 10.87 GB / 25.02 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
 - npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2
 - @loadable/component: ^5.15.0 => 5.15.0
 - @loadable/server: ^5.15.0 => 5.15.0
 - @loadable/webpack-plugin: ^5.15.0 => 5.15.0
```

**Comment by theKashey** [comment]
> during hydration the app recognizes one piece of the dom has old data, which we do not want to show, so that component returns null. Additionally that component goes to fetch fresh data.

Mmm sorry but no. Hydration HAS to create absolutely the same picture your server has rendered. __No exceptions__.

The only way I know to bailout from this - is to use partial hydration, when you can ask React to "skip" some location during hydration and update it later. Look for undocumented `suppressHydrationWarning`.

**Comment by krishnaglick** [comment]
If that's the case I'm curious why react-lazy doesn't have this issue.
One solution I found was to wrap the async components with some generic html so react, at least at the top level, hydrated correctly.

**Comment by theKashey** [comment]
> react-lazy doesn't have this issue

Might be because it can handle Suspense. The real question is actually why your application even works - again probably due to `ReactDOMServer.renderToStringAsync` - as you are:
- using Suspense on Server, which is not supported by default (needs React 18)
- resolves a promise in a second, so it throws during SSR

**Comment by krishnaglick** [comment]
I know the pieces aren't fully compatible but I've found work-arounds. I was hoping to sort something out but looks like I'm outta luck.
