### ISSUE TITLE
Add some details in SSR guide

### ISSUE THREAD

**Issue by epishchalnikov-sf** [gregberge/loadable-components#817]
Hi
I was trying to use loadable-components with server side rendering, and some things seemed unclear and non-obvious.
Want to highlight them here for you to consider adding details on them.

- Should i add babel plugin for both server and client? Or client only? Or server only? Just one line in doc that specifies this would be awesome
- Same for webpack plugin (but i suspect that the answer would be the same as for babel plugin, because it generates filenames (and other stuff) most for webpack). Most projects (if not all) have different webpack configs for bundling client and server, so specifying it in doc would feel direct and straightforward, easily understandable for those who implement that in their first time
- Not sure if loadable-components would work with CRA in SSR mode. Would be useful to mention this somewhere in the doc (for example in the SSR section again).

And the last question: Is this possible to use loadable-components with the server-side rendered app created with CRA? We have basic express server for this, and we also overriding CRA's configs with [craco](https://github.com/gsoft-inc/craco)

**Comment by theKashey** [comment]
> Should i add babel plugin for both server and client? Or client only? Or server only? Just one line in doc that specifies this would be awesome

Babel Plugin is mandatory for both sides.

> Same for webpack plugin (but i suspect that the answer would be the same as for babel plugin, because it generates filenames (and other stuff) most for webpack). Most projects (if not all) have different webpack configs for bundling client and server, so specifying it in doc would feel direct and straightforward, easily understandable for those who implement that in their first time

Webpack plugin is required only for clientside it order to generate information for the server one.

> Not sure if loadable-components would work with CRA in SSR mode. Would be useful to mention this somewhere in the doc (for example in the SSR section again).

If you can change webpack and babel configs the loadable will work. Full stop. However I am really not sure one should provide a hacker guide to adapt loadable to the platform not actually supposed to be used for this use case.

**Comment by epishchalnikov-sf** [comment]
@theKashey Thank you for your answers! Really appreciate them. I'm going to submit a small PR clarifying these details.
