### ISSUE TITLE
outputPath

### ISSUE THREAD

**Issue by AndriesVDW** [gregberge/loadable-components#818]
## 💬 Questions and Help

The `loadable-stats.json` file contains the following line:
```
"outputPath": "/home/my-name/my-project/dist/frontend",
```

Which is because I put the following as my output path in the Webpack config:
```
path: resolve("./dist/frontend"),
```

Now, I'm developing locally, so the outputPath contains the name of the user on my Pc and the folder structure where my project is stored. This also happens in production mode. I'm guessing the same would happen when I deploy my website? (Although then the path would be a little different, it would still contain that kind of information).

Is that line actually needed? Can it be removed? Or am I missing something?

**Comment by theKashey** [comment]
You are right, that line is not required.
