### ISSUE TITLE
How to control the number of generated JS files

### ISSUE THREAD

**Issue by undeadfrost** [gregberge/loadable-components#819]
I used it in my project @loadable/component and @loadable/webpack-plugin.
However, after the build, there will be many files, such as xxx-xxx-bundle-xxx.js. These files are very small, from a few KB to more than ten KB. How to reduce these files?

**Comment by theKashey** [comment]
👉 https://webpack.js.org/plugins/split-chunks-plugin/ (there are no simple answers, please take your time to find yours)

**Comment by undeadfrost** [comment]
> 👉 https://webpack.js.org/plugins/split-chunks-plugin/（没有简单的答案，请花时间找到你的）

Thank you for your reply
