### ISSUE TITLE
Stale `statsFile`

### ISSUE THREAD

**Issue by Dattaya** [gregberge/loadable-components#821]
## 🐛 Bug Report

I hot reload the server in my boilerplate and for some reason `new ChunkExtractor({ statsFile })` loads old `statsFile` and it's not present in `require.cache` so `clearModuleCache` can't do anything much. Changing `smartRequire` in utils to `JSON.parse(fs.readFileSync(modulePath));` fixes the problem. I can send a PR if you're interested.

## To Reproduce

Tested on Linux, might not work on other OSs:
- `git clone https://github.com/Dattaya/ts-react-ssr-basis && cd ts-react-ssr-basis && npm i && npm start`
- Open `http://localhost:3000/` and view page source (Ctrl+U in Chrome)
- Modify `common/components/App/index.tsx`, save it, reload the page source and observe that `script src=` points to the old js file.

## Expected behavior

`ChunkExtractor.getScriptTags` returns updated assets.  

## `npx envinfo`

```bash
## System:
 - OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.3/bin/yarn
 - npm: 6.14.11 - ~/.nvm/versions/node/v14.15.3/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2 
 - @loadable/component: ^5.15.0 => 5.15.0 
 - @loadable/server: ^5.15.1 => 5.15.1 
 - @loadable/webpack-plugin: ^5.15.1 => 5.15.1
```

**Comment by rtymchyk** [comment]
@Dattaya What was the resolution here?

**Comment by Dattaya** [comment]
@rtymchyk, sorry for the delayed response. I changed my mind, because usually issues are closed when they're fixed, not when included in a new release. In the meantime you can modify `util.js` in `node_modules` manually.
