### ISSUE TITLE
Dynamic page loading, show error when file not found

### ISSUE THREAD

**Issue by gangataarun** [gregberge/loadable-components#822]
Hey,

I'm importing files dynamically using @loadable components, but sometimes a page might not exist just because it has not been developed yet. In that scenario, can we show an error or a message?

**Comment by theKashey** [comment]
Related: #717

In short - you can show an error message via `ErrorBoundary` or `ErrorComponent`, but you cannot actually understand which message to display. It would be always just an "error".
