### ISSUE TITLE
loadable.lib seems not work with ref when ssr

### ISSUE THREAD

**Issue by blinkcat** [gregberge/loadable-components#829]
## 🐛 Bug Report

loadable.lib seems not work with ref when ssr, the value of ref.current is always undefined!

## To Reproduce

As described in the second example in the [docs here](https://loadable-components.com/docs/library-splitting/), I used this example in [this example](https://github.com/gregberge/loadable-components/tree/main/examples/server-side-rendering).
But,  `this.moment.current` is alway undefined.
After studying the source code,  i found that [loadAsync](https://github.com/gregberge/loadable-components/blob/1376eec79bc32afbccd7fa403f1e84998fc67ca3/packages/component/src/createLoadable.js#L247) will not run when ssr, and [props.forwardedRef](https://github.com/gregberge/loadable-components/blob/1376eec79bc32afbccd7fa403f1e84998fc67ca3/packages/component/src/library.js#L6) will never be assigned.
Is this designed, or is it a bug?

## Expected behavior

second example should work well  on server side.

## Link to repl or repo (highly encouraged)

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash

```

**Comment by theKashey** [comment]
😅 is a bug
