### ISSUE TITLE
What should the type of `loadFn` be to allow non-FC functional components?

### ISSUE THREAD

**Issue by githorse** [gregberge/loadable-components#831]
I want to write a simple wrapper for `loadable` that displays a default loading indicator:

```
import React from "react"
import MyLoadingIndicator from './MyLoadingIndicator'
import loadableComponent from '@loadable/component'

interface LoadableOptions {
  fallback?: JSX.Element
}

export default function myLoadable(
  loadFn: ???,
  {fallback, ...opts}: LoadableOptions = {})
{
  return loadableComponent(
    loadFn,
    { fallback: fallback || <MyLoadingIndicator />, ...opts }
  )
}
```

Some of my loaded functional components do not inherit from `React.FC`:

```
export default function Foo({bar}: {bar: string}) => {
  return (<div>{bar}</div>)
}
```

I'm struggling to figure out the declared type of `loadFn` that will work with all my components (besides `Promise<any>`, which works.). It can't rely on `DefaultComponent` since ultimately that derives from `React.ComponentType`, which my components don't always meet. I've tried `loadFn: <Module> => () => Promise<Module>` but that gives me an error:

```
Type 'Promise<typeof import("/home/rct/cod/gvt/axis/packages/shared/src/components/Loadable/Foo")>' 
is not assignable to type 'Promise<Module>'.
```

Note this issue is similar to https://github.com/gregberge/loadable-components/issues/744, but I don't see any type errors when using the library directly; I just can't figure out the type in my wrapper.

Any advice on what the type of my `loadFn` should be? 

On a broader note: I've run into similar issues before. My understanding is that writing a simple functional component like this that doesn't inherit from `React.FC` is pretty common, and, in fact, there are [reasonable arguments against inheriting from `React.FC`](https://fettblog.eu/typescript-react-why-i-dont-use-react-fc/). So I'm surprised that React doesn't include a more generic "functional component type": essentially, something like `(props: {}) => JSX.Element | null`. These non-`FC` components work perfectly well in practice, but they cause me beaucoup Typescript issues. Maybe I'm missing something here? How does the Typescript community handle these components?

**Comment by theKashey** [comment]
As you haven't provided full code representing your problem I can comment only on a few moments:

- if you want to provide default options for loadable:
👉Use the the own function signature to type your one
```tsx
 const myLoadable: typeof loadableComponent = (
  loadFn,
  {fallback, ...opts}
) => 
loadableComponent(
    loadFn,
    { fallback: fallback || <MyLoadingIndicator />, ...opts }
  )
```

- if you cannot match interfaces between your code and loadable
👉 do not match. Only the input and output matters, not what in between. If it works - then it works, types does not matter _that much_.
```ts
export default function myLoadable(
  loadFn: WhateverYouNeed,
  {fallback, ...opts}: LoadableOptions = {})
{
  return loadableComponent(
    loadFn as any, // absolutely no shame
    { fallback: fallback || <MyLoadingIndicator />, ...opts }
  )
}
```

**Comment by theKashey** [comment]
>  there are reasonable arguments against inheriting from React.FC

With all respect, only the second point(FC<> always imply children) is "reasonable". The rest is not quite

**Comment by githorse** [comment]
Thanks @theKashey -- I think both your options (including the first) require me to type `loadFn` as `any` (or `Promise<any>`), which is what I'm trying to avoid. You're right, it does work fine -- but by that logic I should just abandon Typescript entirely, right? I do use `any` occasionally when I can't figure out the correct type (I assume we all do), but I try to avoid it.

I'm not sure which code is missing that might help here -- could you say more? Not sure if it helps, but to clarify, `myLoadable` is intended to be called with the same interface as `loadableComponent`: e.g. `const Foo = myLoadable(() => import('./Foo'))`.

**Comment by theKashey** [comment]
- `const myLoadable: typeof loadableComponent = (` 

is equal to 
- `myLoadable` is intended to be called with the same interface as `loadableComponent`

Please double-check existing types of loadable as it might help you understand what/why they are not working for you, as `Promise<any>` never was a case.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/loadable__component/index.d.ts#L79-L82
