### ISSUE TITLE
Usage with Vitejs

### ISSUE THREAD

**Issue by bjufre** [gregberge/loadable-components#833]
## 💬 Questions and Help

Hello, we recently had to migrate a huge Webpack app over to Vitejs. And the fact is that in the Webpack version we were using `loadable-components`. But because of its dependency on Webpack for SSR we decided that we were gonna disable it temporarly. But now, we would like to try and hook it up with Vite so that it works without problem. 

So that question is: does `loadable-components` work or has any plans to work with Vite? 
If not, the limitation right now is the SSR piece with the babel plugin as well as the chunks collector? If so, could you point us towards a possible solution? We could very much provide some PR if needed even.

Thanks!!

**Comment by theKashey** [comment]
Hey. Unfortunately `loadable-components` currently are very webpack specific. [There are plans](https://github.com/gregberge/loadable-components/pull/784#issuecomment-913115585) to make it less bound to the underlying system, but this is not something you can expect to happen soon enough.

Currently, the only "browser-independent" code splitting solution is [react-imported-component](https://github.com/theKashey/react-imported-component), which I do maintain as well, but it hasn't been tested with Vite, so no guarantees as well.

**Comment by rasel-code-dev** [comment]
please make it vitejs compatible.

**Comment by wille** [comment]
The loadable-components equivalent for Vite is https://github.com/wille/vite-preload?tab=readme-ov-file#migrating-from-loadable-components. 

React.lazy "works" in vite but server rendering any lazy modules will not include the stylesheets in the initial HTML, causing Flash Of Unstyled Content (FOUC) and the JS will not be preloaded.
