### ISSUE TITLE
Stale stats when not using HotModuleReplacementPlugin

### ISSUE THREAD

**Issue by Mordred** [gregberge/loadable-components#837]
## 💥 Regression Report

Using `module.hot` is preventing cache clear if not using HotModuleReplacementPlugin or Webpack completely for server. (8f10896058cdfd542c2aca1a982c2e14b1d9707a)

## Last working version

Worked up to version: v5.14.2

Stopped working in version: v5.15.0 (commit 8f10896058cdfd542c2aca1a982c2e14b1d9707a)

## To Reproduce

Download example https://github.com/gregberge/loadable-components/tree/main/examples/server-side-rendering. Run `npm run build:webpack -- --watch` in one terminal and `babel-node src/server/main.js` in second.

Then change *Test* in App.js to *Test 2* - you will get old bundles in the HTML and warning `Text content did not match. Server: "Test 2" Client: "Test"` if you refresh the page.

On v5.14.2 this is working as it should.

## Expected behavior

There should be no warning and correct bundles after refresh.

**Comment by kompolom** [comment]
It not working even if `HotModuleReplacementPlugin` enabled.
The `module` here is common nodejs module not webpack.
https://github.com/gregberge/loadable-components/blob/9ff66939ee6fd622922f71128a30b5d3f43f63b0/packages/server/src/util.js#L27

**Comment by Mordred** [comment]
@kompolom You have to add `HotModuleReplacementPlugin` and `/^@loadable\/server/` to `allowlist` for `nodeExternal`:

```js
configuration.externals = [
  nodeExternal({
    // @loadable/server - because it is using module.hot
    allowlist: [/^@loadable\/server/],
  }),
];
```

So that `@loadable/server` is compiled by Webpack. But it will not work till https://github.com/gregberge/loadable-components/pull/838 is released.

I think that `module.hot` should be removed, because @loadable/server must work even you are not using Webpack to process your server code - _see my To Reproduce section in first comment_.

**Comment by Mordred** [comment]
This bug still exists

**Comment by theKashey** [comment]
`module.hot` is used to understand that module cache _can_ be accessed and operated with. There are better ways to do the same and `clearModuleCache` is already contain all required checks.

👍  `module.hot` should be removed
