### ISSUE TITLE
Precheck dynamic import

### ISSUE THREAD

**Issue by rowrowrowrow** [gregberge/loadable-components#841]
I'm interested in trying out the dynamic import approach but wanted to know if it's possible to confirm a file should be available for import before attempting to import. Is there a way to get a list of available files to import? I.e. if I create a loadable like the following:

```
import loadable from '@loadable/component'
const AsyncPage = loadable(props => import(`./${props.page}`))
```

I would like to avoid hard-coding a list of potential imports to check against. Is there an internal list of potential imports that I can access client-side at runtime, either from 'AsyncPage', '@loadable/component', webpack, or someplace else?

**Comment by theKashey** [comment]
No, that is not something currently possible and requires a very different implementation to be "understood" by TypeScript and friends.
My current understanding of this problem is following -> https://github.com/theKashey/react-imported-component/issues/190

**Comment by rowrowrowrow** [comment]
Thanks for the quick response! If I knew more about eslint I'd be open to helping submit the feature but I don't.
