### ISSUE TITLE
Yarn audit shows vulnerability for lodash

### ISSUE THREAD

**Issue by SoerenSchulzReply** [gregberge/loadable-components#842]
## 💬 Questions and Help

Yarn audit shows a high vulnerability for lodash, which was fixed in Version 4.17.21.
Is there a plan to update this dependency in the near future?

**Comment by theKashey** [comment]
https://github.com/gregberge/loadable-components/blob/main/packages/server/package.json#L33
> "lodash": "^4.17.15"

such vulnerabilities are very complicated beasts, especially when they are not any vulnerabilities at all...

But I would like to advise you to fix the problem via your very own lock file first. Just find the problematic version and delete it - the newer one will be installed automatically.
Removing and Adding loadable will do the same.
