### ISSUE TITLE
requireEntrypoint actually requires all js chunks

### ISSUE THREAD

**Issue by kompolom** [gregberge/loadable-components#843]
## 🐛 Bug Report

`ChunkExtractor.requireEntrypoint(entryName)` requires not only passed entrypoint but all js assets.

As I understand, code below needs only for drop module cache:
https://github.com/gregberge/loadable-components/blob/9ff66939ee6fd622922f71128a30b5d3f43f63b0/packages/server/src/ChunkExtractor.js#L389-L393

This behavior was added at PR #431 
Relates issue #230 

## Expected behavior

Only specified entrypoint to be loaded with it dependent chunks. 

## Environment

Paste the results here:

```bash
## System:
 - OS: Windows 10 10.0.19043
 - CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
 - Memory: 2.44 GB / 11.90 GB
## Binaries:
 - Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
 - npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2
 - @loadable/component: 5.15.0 => 5.15.0
 - @loadable/server: 5.15.1 => 5.15.1
 - @loadable/webpack-plugin: 5.15.1 => 5.15.1

```

**Comment by theKashey** [comment]
Just for my information - what is the problem with requiring more than possible files?
Especially having in mind that the majority of SSR setups produces a single file for the server and generates chunks only for the client.

**Comment by kompolom** [comment]
In our project we build application for desktop, mobile and legacy devices. We have entrypoint for each of these platforms plus one entrypoint for nodejs application which runs express server.
So, the problem. When I start server and try to render (for example) mobile page, it loads and _execute_  mobile, desktop, and legacy entrypoints. That`s slowdown project. What is more important, it try to require server entrypoint which try to start new server with same config and expectedly crashes.

**Comment by theKashey** [comment]
I hear you and will try to find a solution. There is a little problem than dependencies created by `import` are not "visible" in `stats` and I could not really know what I should load in order to handle the functionality of one or another entrypoint.

However, that would be so nice to have this information. Let me ask some webpack guys about possible solution.
