### ISSUE TITLE
loadable-components: failed to asynchronously load component

### ISSUE THREAD

**Issue by AyabongaQwabi** [gregberge/loadable-components#848]
## To Reproduce

I have created module A which is a component library of my React App. Which I plan on using on module B which is my actual React App.

I have an index.js whereby I export my components from module A by using loadable components in the following fashion
 
 ```
 import loadable from '@loadable/component'
 
 export const Theme = loadable(() => import('./Theme'))
 export const OtherComponent = loadable(() => import('./OtherComponent'))
 export const OtherComponent2 = loadable(() => import('./OtherComponent2'))
 ```
I therefore build and deploy my module to npm by using the following webpack configuration

```
const path = require('path')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const TerserPlugin = require("terser-webpack-plugin")
const LoadablePlugin = require('@loadable/webpack-plugin')

module.exports = {
  mode: 'production',
  optimization: {
    usedExports: true,
    minimize: true,
    concatenateModules: false,
    minimizer: [new TerserPlugin({
      terserOptions: {
        keep_fnames: true
      }
    })],
    
  },
  entry: {
    main: './src/components/index.js',
  },
  output: {
    publicPath: ''/",
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"),
    library: "myComponentLibrary", 
    libraryTarget: "umd",
    globalObject: "this"
  },
  externals: {
    react: {
      root: 'React',
      commonjs: 'react',
      commonjs2: 'react',
      amd: 'react',
    },
  },
  plugins: [new CleanWebpackPlugin(), new LoadablePlugin()],
  module: {
    rules: [
     {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "babel-loader",
            options: {
              cacheDirectory: true
            }
          }
        ],
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/,
        type: 'asset/inline'
      },
    ]
  }
}


```
## Expected behavior

I expected that when I npm install module A on module B to be able to import and render my components but instead I get the following error.

> loadable-components: failed to asynchronously load component {
  fileName: undefined,
  chunkName: undefined,
  error: 'Loading chunk 2661 failed.\n(error: 2661.js)'
}

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```## System:
 - OS: Linux 5.8 Ubuntu 20.04.1 LTS (Focal Fossa)
 - CPU: (4) x64 Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz
 - Memory: 848.22 MB / 11.40 GB
 - Container: Yes
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
 - npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2 
 - @loadable/component: ^5.15.0 => 5.15.0 
 - @loadable/webpack-plugin: ^5.15.1 => 5.15.1 

```

**Comment by theKashey** [comment]
Sorry, but you have to build only ONE thing using webpack, not both.
`Loadable components` are "product facing" library and not supposed to be used in other packages.

Meanwhile, please check #640 for the use case _closer_ to your one, however completely different.

**Comment by bwhitty** [comment]
@theKashey follow up question to your answer:

We have a similar use case, where we have packages compiled using Rollup and we want to put code split points in them, and have applications configurated with `@loadable` consume them -- we're finding some issues with those code split points functioning.

We run Babel on these packages explicitly (for other reasons), and I was thinking that perhaps that would help `@loadable` be able to find the code split points, but your answer makes me think that this just doesn't work fundamentally? 

Do you perhaps have an issue or reason you could point us towards as to why that's the case? Is it the Babel plugin, or the Webpack plugin, etc? 

Thanks for the great library and any assistance!

**Comment by theKashey** [comment]
- loadable `babel plugin` injects webpack-chunk-name into all dynamic imports, expecting them to be named this way by webpack. It can work for node_modules as well, but you have to ensure that 1) babel is told to (default settings are excluding node_modules) 2) dynamic import is still dynamic import (or babel plugin will not find what it has to amend)
- that is all. The rest is to server/webpack packages which have to ensure that the _expectations_ of babel plugin are fulfilled. 

So please check the build output of rollup - it's better to ESM with untranspiled dynamic import.
