### ISSUE TITLE
Expose synchronous `isReady` method 

### ISSUE THREAD

**Issue by cecchi** [gregberge/loadable-components#850]
## 🚀 Feature Proposal

It would be useful to be able to synchronously check whether a Loadable is loaded/ready to be rendered. Currently we can use `load()` to access a `Promise`, but there are scenarios where async APIs aren't ideal. 

## Motivation

I am attempting to implement a wrapper component that loads a `Loadable` component in parallel to loading the data necessary to render that page. If we had access to inspecting whether a `Loadable` was ready, we could consolidate the loading state for both async operations: the data fetching and the component loading. 

## Example

```tsx
const LoadablePage = loadable(() => import('./page'));

const MyRoute = () => {
  // Using Apollo Client as an example, but could be any data fetching library
  const { data, loading } = useSomeApolloQuery() 
  
  // This default state is the use-case for `isReady()` 
  const [isComponentReady, setIsComponentReady] = useState(LoadablePage.isReady())  // <<<<<<<<<<<
   
  // On mount, load the Loadable if necessary
  useEffect(() => {
    if(!LoadablePage.isReady()) {
      LoadablePage.load().then(() => {
        setIsComponentReady(true)
      })
    }
  }, [])
   
  // Benefit of having this method is we can show a unified loading state regardless of whether the data loading or component loading is the bottleneck
  if(loading || !isComponentReady) {
    return <h1>Some Loading State</h1>
  }
  
  // Can safely render the page, knowing data is available and the fallback loading state will not be rendered
  return <LoadablePage data={data} />
}
```

Without `isReady()`, there isn't any way to determine whether the route should initially render a loading state or not. We are entirely reliant on the built-in fallback functionality. We can achieve a similar result using the `fallback` prop today, by using the same "loading" component for both the data-fetching loading state and separately as the `fallback` prop to the `Loadable`, but it's not ideal because the loading component may remount. Loading components are often animated and unnecessarily remounting them can result in janky animation.

**Comment by theKashey** [comment]
🤔 internally there is such method, it's just not static, while can be.

**Comment by theKashey** [comment]
> Without isReady(), there isn't any way to determine whether the route should initially render a loading state or not.

Well, you might not need this knowledge, and there are at least two ways to handle this:
- Suspense, let's skip it as you are not using it
- `fallback`
```tsx
  const loadingState = <h1>Some Loading State</h1>;
  if(loading) {
    return loadingState
  }
  
  return <LoadablePage
   data={data} 
   fallback={loadingState}  <-------
 />
```

**Comment by cecchi** [comment]
Thanks for the quick response. The second solution is the implementation we have today, but it's not ideal because it causes `loadingState` to remount. That wouldn't usually be the end of the world, but in our case the loading component is often a stateful component and remounting wipes state. In other cases it's a component that renders an animation, and often React animation libraries have bindings for triggering an animation on mount/unmount.

**Comment by theKashey** [comment]
Suspense is not a blocker for SSR and there are multiple ways you can manage with old or new React, but I respect your point and will add better `observability methods` to Loadable.
