### ISSUE TITLE
ChunkExtractorManager case useState not work

### ISSUE THREAD

**Issue by Statfine** [gregberge/loadable-components#851]
## 🐛 Bug Report

when i add ChunkExtractorManager Page will error caused by using useState，bug using useEffect is ok

## To Reproduce

```
const statsFile = path.resolve('./build/loadable-stats.json');

const extractor = new ChunkExtractor({ statsFile });

<ChunkExtractorManager extractor={extractor}>
```

## Expected behavior

can use useState

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.7
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 75.34 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 14.16.1 - /usr/local/bin/node
 - Yarn: 1.22.11 - /usr/local/bin/yarn
 - npm: 6.14.12 - /usr/local/bin/npm
## npmPackages:
 - @loadable/babel-plugin: 5.13.2 => 5.13.2 
 - @loadable/component: 5.15.0 => 5.15.0 
 - @loadable/server: 5.15.1 => 5.15.1 
 - @loadable/webpack-plugin: 5.15.1 => 5.15.1 
```

![1636540054274](https://user-images.githubusercontent.com/4608910/141096532-ec39916d-06c3-454b-9dd7-6f40f3713b76.jpg)

**Comment by theKashey** [comment]
Sorry, but your issue is absolutely unclear. 
There is a huge difference in the issue title and content, as well as there is no way to reproduce it by another developer.
