### ISSUE TITLE
Rescuing from a component syntax error inside an ErrorBoundary.

### ISSUE THREAD

**Issue by c4lliope** [gregberge/loadable-components#852]
Hello,

I was very pleased to come across your library; I dropped it into my application and everything functioned perfectly, as expected.

It's been about a month and I have a need to add an additional feature to my application:
rendering user-submitted components which may contain syntax errors.

To test this, I have a small component with a syntax error:
```javascript
import React from "react"
import { observer } from "mobx-react"

export default observer(({ model }) => {
  return (
    <div>
      {model.label
    </div>
  )
})
```

Note the lack of a closing bracket on `{model.label`.

My goal is for my application to realize there is a syntax error inside  the component,
which is loaded with `loadable`, and display an `<ErrorBoundary>` fallback UI.

Here is my `ErrorBoundary` class component:

```javascript
import React from "react"

class ErrorBoundary extends React.Component {
  state = {
    loadError: false,
  }

  static getDerivedStateFromError() {
    return { loadError: true }
  }

  componentDidCatch(error, info) {
    console.log("Load error!", error)
  }

  render() {
    if(this.state.loadError)
      return <div>Error</div>

    return this.props.children
  }
}

export default ErrorBoundary
```

Luckily, this `ErrorBoundary` does detect the error inside `ComponentDidCatch()`;
in the console I see:

```
Load error! Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/grace/place/assemble/pose/src/models/goal/displays/primary.js: Unterminated regular expression. (8:6)
```

Sadly, the error does not stop there - if it did I would be able to render an error message on screen and call it a day.

Instead, the error bubbles up to the top of the application, and I see the normal `webpack-dev-server` error screen:
![Screen Shot 2021-11-10 at 10 50 58 AM](https://user-images.githubusercontent.com/30454698/141146218-116af1b0-72c1-43d8-af49-3788d5090bda.png)

Please, anyone - help me rescue my error so my application can become immune to silly typos users may make in loadable components. I'm much obliged for your help. Thanks!

**Comment by theKashey** [comment]
Can it be due to some other tool, like the `error overlay`?

**Comment by c4lliope** [comment]
Good idea - there is some error handling happening from `webpackHotDevClient.js`:
![Screen Shot 2021-11-12 at 10 07 06 AM](https://user-images.githubusercontent.com/30454698/141488535-ed71bf9c-b8cf-4a45-b90e-5585f6913edd.png)

Your comment led me here - https://stackoverflow.com/a/38922621,
which recommends using a `window.onerror` function to handle the error;
I can place a debugger in the `onerror` function and intercept the error before the overlay renders.

Sadly, I still have no way of dismissing the error.

I may end up trying to run a parser over the user's input before I save it to the file on disk,
so that I never end up saving code that contains syntax errors.
This seems like a clean approach.

The only other thing I can think to do would be to disable the error overlay, but I'm not sure that's possible while retaining webpack's hot reloading feature. This path seems like it is mucking around in the weeds too much, so I'll likely avoid it.

**Comment by theKashey** [comment]
According to this `loadable` cannot help you, as a completely parallel functionality is triggering the error.
