### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by akshare** [gregberge/loadable-components#856]
I'm able to load server side html as well as get the styles using getStyleTags().

However, getScriptTags() is returning a bunch of "Uncaught ReferenceError: exports is not defined" errors on browser console.

I've searched as well as tried to fix, but nothing sticks so far.

Any insight appreciated, thank you.

This is my webpack config:

![Screen Shot 2021-12-08 at 7 54 14 PM](https://user-images.githubusercontent.com/10148279/145331732-805108f2-1c5a-4003-9023-b77487fecc76.png)

![Screen Shot 2021-12-08 at 7 51 41 PM](https://user-images.githubusercontent.com/10148279/145331554-d81fcdd6-b08e-4289-bfb3-6e1d825f9eef.png)

**Comment by kdevan** [comment]
I ran into this and it was a nightmare to debug. For me setting `sourceType: 'unambiguous'` in my babel configuration worked. 

https://babeljs.io/docs/en/options#sourcetype
