### ISSUE TITLE
Loadable doesn't seem to correctly support module script preloading

### ISSUE THREAD

**Issue by andrewscfc** [gregberge/loadable-components#864]
## 🐛 Bug Report
In our project we recently moved to start emitting modules for our javascript bundles using the [`module` config](https://webpack.js.org/configuration/output/#outputmodule) in webpack.

The default of behaviour [calling `getLinkElements`](https://github.com/bbc/simorgh/blob/1d272418eaf16305fc793a47f232a2a4ac322a30/src/server/Document/index.jsx#L107) returns invalid preload links that do not work in some browsers, our bug issue here captures the problem: https://github.com/bbc/simorgh/issues/9770 

Currently loadable emits links that look like this: `<link data-chunk="main" rel="preload" as="script" href="https://static.files.bbci.co.uk/ws/simorgh-assets/public/static/js/modern.framework.13037174.js" crossorigin="anonymous">`

`rel="preload"` is incorrect for modules as described in this post: https://developers.google.com/web/updates/2017/12/modulepreload

We are planning to workaround the issue with this PR: https://github.com/bbc/simorgh/pull/9771

## To Reproduce

1. Checkout our repo at this commit https://github.com/bbc/simorgh/tree/1d272418eaf16305fc793a47f232a2a4ac322a30 (we will shortly workaround this making latest not exhibit the behaviour.
2. Run yarn dev
3. Visit http://localhost:7080/mundo

## Expected behavior
`getLinkElements` emits preload links with `rel` set to `modulepreload`: `<link data-chunk="main" rel="modulepreload" as="script" href="https://static.files.bbci.co.uk/ws/simorgh-assets/public/static/js/modern.framework.13037174.js" crossorigin="anonymous">`

## Link to repl or repo (highly encouraged)

See above

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 40.76 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.18.4 - ~/.nodenv/shims/node
 - Yarn: 3.1.1 - ~/.nvm/versions/node/v12.18.4/bin/yarn
 - npm: 6.14.6 - ~/.nodenv/shims/npm
## npmPackages:
 - @loadable/babel-plugin: 5.13.2 => 5.13.2 
 - @loadable/component: 5.15.2 => 5.15.2 
 - @loadable/server: 5.15.2 => 5.15.2 
 - @loadable/webpack-plugin: 5.15.2 => 5.15.2 
```

**Comment by andrewscfc** [comment]
Additionally thank you for building/supporting this excellent library. I intend to look at a PR for this but have no timeline for when I'll get this finished, feel free to go ahead before I get a chance or offer some guidance so I don't go off in the wrong direction 😄

**Comment by theKashey** [comment]
Got you. Frankly speaking, I've forgotten about `type="module"` scripts, which now can work everywhere and promise some cool features like multithreaded parsing.

I'll take a look into a proper support for this.
