### ISSUE TITLE
Some questions about the SSR flow

### ISSUE THREAD

**Issue by Ptichi** [gregberge/loadable-components#865]
## 💬 Questions and Help

Hi, I'm trying to figure out how to integrate Loadable Components into my existing React SSR app and have some questions:

1. I saw in your example that you `hydrate` your app when all loadable scripts are ready. Is there a way to **not** hydrate the whole application?
1. Is there a way to control when a  chunk is loaded from the client? for example, instead of automatically loading all scripts when the page loads, Ideally I would like to control when to load a bundle and render its component (even manually). Is that behavior possible?

My goal is to avoid rendering some components in the server, and only load & render them on the client After some action has occurred (this is to reduce the main bundle size, not load what we don't need, and avoid the heavy action of hydrating the whole application and need to get all the app props to the client).

Here's some pseudo code to better clarify my line of thought:
```jsx
// server.jsx - runs in the sever
const App = () => {
  const LazyComponent = loadable(() => import('./my-component'));

  return <div id={'page-wrapper'}>
    <LazyComponent prop1="some-text" />
  </div>
}

return `<html>
<head></head>
<body>
  <App />
  <script src="client.js"></script>
</body>
</html>`;
```
```jsx
// index.jsx - runs in the browser
function onSomeButtonClick() {
  const loadableChunks = getLoadableChunks(); // Somehow get the loadable chunks by component

  const LazyComponent = await load(loadableChunks['my-component']) // Load the desired chunk and get its respective component

  ReactDOM.render(LazyComponent, document.getElementById('page-wrapper')); // Render the component
}
```

Is this (or some of this) flow achievable via Loadable Components package? if not, are there any suggested alternatives?

I'd very much appreciate any comments or feedback on this idea and love to know if anyone else encountered a similar use case.
Thanks!

**Comment by theKashey** [comment]
In general, my answer will be "yes", "it is possible".

In your case we are talking about 3 different things:
- common lazy loading without SSR. Just imagine there is no SSR and you are just conditionally rending some lazy-loaded components, which will render themself once loading is complete. Loading will not start until requested
- common partial(now called selective) hydration, when some pieces of HTML are kept as HTML untill you are ready to continue hydration. In general only one level of such components is supported (by standard "supressHydrationWarning" hack). https://github.com/theKashey/react-snap/blob/97bd886cf86b5e44c171fbd4f804a44c91d3c11f/Readme.md look for `react-prerendered-component`
- Suppressing usage tracking, or not reporting, or reporting to other channel on SSR. Just wrap locations "you want to keep at server" in extra [ChunkExtractorManager](https://loadable-components.com/docs/api-loadable-server/#chunkextractormanager). You can then preload chunks collected by another channel, or not - you will be in control.

in a general search for partial hydration docs, articles and examples. There are many.

**Comment by theKashey** [comment]
Related: 
- #749
