### ISSUE TITLE
Imperatively accessing component on server

### ISSUE THREAD

**Issue by AustinBrunkhorst** [gregberge/loadable-components#879]
I'm looking to build functionality that is similar to something like [`getServerSideProps`](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props) in Next.js. Ideally, I'd like to be able to assign a function to a loadable component, and call the function on the server.

Consider this bare bones example

**MyPage.js**
```js
const MyPage = () => { ... };

MyPage.getServerSideProps = async () => {
  // this will be passed to `MyPage` on render
  return { ... };
};

export default MyPage;
```

**routes.js**
```js
export const MyPage = loadable(() => import("./MyPage"));
```

Is there any way to access `MyPage.getServerSideProps` from a server? i.e. is there any API to resolve the original component? I'm looking to do something like this

**server.js**
```js
import { MyPage } from "./routes";

// should be MyPage from MyPage.js
const component = await MyPage.getOriginalComponent();

const serverProps = component.getServerSideProps();

const html = renderToString(<MyPage {...serverProps} />);
```

Thank you!

**Comment by theKashey** [comment]
There is a way - `loadable.lib`, but it's a different API altogether. Plus it does not work "outside" of React as in both cases it is a React Component.

A good solution for you will be to use your own loadable wrapper

__routes.js__
```jsx
import loadable from './my-loadable';
export const MyPage = loadable(() => import("./MyPage"));
```

__my-loadable__
```tsx
import realLoadable from '@loadable/component';

export default function loadable = (importer) => {
 const loadableComponent = realLoadable(importer);
 loadableComponent.getOriginalComponent = importer;
}
```

**Comment by aygee** [comment]
I spent hours trying to get this working. I tried the @theKashey method but didn't work. 

I expect calling await on the load function but it doesn't work on the first call. It seems to work on subsequent calls because the component is already loaded and cached.
```
await component.load();
const serverProps = component.getServerSideProps();
```

So I ended up with the following solution
```
let getServerSideProps;

if (component.load) {
  await component.load().then((module) => {
    getServerSideProps = module.default.getServerSideProps;
  });
} else {
  getServerSideProps = component.getServerSideProps;
}
```

**Comment by theKashey** [comment]
Of course the nature of `component` will never change. It was a `Loadable` wrapper around the real one, and always will be.

Due to this "immutability" you should write the code in a little different way
```tsx
const serverProps = 
(await component.load()) // get the component
.default // unfortunately  `.load` does not support component resolution
.getServerSideProps(); // we got it
```
