### ISSUE TITLE
Can it be used with Rollup with server side rendering?

### ISSUE THREAD

**Issue by mbrain-io** [gregberge/loadable-components#887]
Can loadable-components be used with Rollup (React library is created) but so that server side rendering works?

Is there any example of this?

Thank you!

**Comment by theKashey** [comment]
Unfortunately today `loadable-components` is very webpack specific and cannot work in any other environment.
Please take a look at [react-imported-component](https://github.com/theKashey/react-imported-component) which is not really bound to any particular bundler.

**Comment by mbrain-io** [comment]
@theKashey Thank you for the suggestion, I will give it a try!
