### ISSUE TITLE
Prefetching does not work with Vite

### ISSUE THREAD

**Issue by rwieruch** [gregberge/loadable-components#907]
I am using loadable-components with Vite, but Prefetching does not seem to work. I guess it's because Vite isn't using Webpack, so is there any other way to make this happen without having to prefetch manually? That's how I do it at the moment:

```
const Login = loadable(
	() => import(/* webpackPrefetch: true */ '~/pages/auth/login'),
	{
		resolveComponent: ({ Login }) => Login,
		fallback: <Loading isFullscreen />,
	}
);
```

**Comment by theKashey** [comment]
Loadable is designed to work only with `webpack`, as well as `webpackPrefetch` is webpack specific and has to effect in Vite world.
Sorry, but your problem does not have any solution.
