### ISSUE TITLE
Document `@swc/plugin-loadable-components`

### ISSUE THREAD

**Issue by kdy1** [gregberge/loadable-components#909]
## 💬 Questions and Help

I searched for issues but there was only request for SWC plugins.
I implemented SWC plugin for `@loadable/compoents` and it's published as `@swc/plugin-loadable-components`

A thing to note is that SWC plugin API is still experimental.
Still, I'm lefting an issue so someone search for SWC plugin can find this issue.

Git repo: https://github.com/swc-project/plugins/tree/28ab1c04df68f7347d470ed3bac4e72d7f7befa9/packages/loadable-components
Npm: https://www.npmjs.com/package/@swc/plugin-loadable-components
Documentation: https://swc.rs/docs/configuration/compilation#jscexperimentalplugins

**Comment by theKashey** [comment]
Amazing! A lot of people requesting swc based transformation and I am just happy to see how it moves forward

**Comment by adbutterfield** [comment]
@kdy1 thanks for this!

I was wondering if you can point me to a working example? I'm trying to integrate this into a project of mine right now along with swc-loader, and I just get one giant chunk. I'm guessing something wrong with my setup...
