### ISSUE TITLE
How do you configure SSR with Loadable Components on NextJS?

### ISSUE THREAD

**Issue by andrewscfc** [gregberge/loadable-components#912]
This is a repost of a StackOverflow question a hopefully more appropriate place. Thanks for any help you can offer! https://stackoverflow.com/questions/73824303/how-do-you-configure-ssr-with-loadable-components-on-nextjs

---

We have a requirement to use [Loadable Components](https://loadable-components.com/) in a new NextJS app we are building. I believe in NextJS for this use case you tend to use their native [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) feature but we are pulling in code from our mature codebase with extensive use of 'Loadable Components' throughout so replacement with dynamic imports is pretty impractical (PR is here in our main codebase: https://github.com/bbc/simorgh/pull/10305).

I have put together a representive example in a repo to demonstrate an issue we are having: https://github.com/andrewscfc/nextjs-loadable

In this example I have [introduced a loadable component](https://github.com/andrewscfc/nextjs-loadable/blob/main/pages/index.tsx#L8) to split the `Layout` component into its own bundle:
```javascript
import * as React from 'react';
import Link from 'next/link';
import loadable from '@loadable/component';

const LayoutLoadable = loadable(() => import('../components/Layout'));

const IndexPage = () => (
  <LayoutLoadable title="Home | Next.js + TypeScript Example">
    <h1>Hello Next.js 👋</h1>
    <p>
      <Link href="/about">
        <a>About</a>
      </Link>
    </p>
  </LayoutLoadable>
);

export default IndexPage;
```

You can run this repo by running:
`yarn && yarn dev` (or equivalent `npm` commands)

If you navigate to `http://localhost:3000/` the page body looks like this:
```html
<body>
    <div id="__next" data-reactroot=""></div>
    <script src="/_next/static/chunks/react-refresh.js?ts=1663916845500"></script>
    <script id="__NEXT_DATA__" type="application/json">
      {
        "props": { "pageProps": {} },
        "page": "/",
        "query": {},
        "buildId": "development",
        "nextExport": true,
        "autoExport": true,
        "isFallback": false,
        "scriptLoader": []
      }
    </script>
  </body>
```

Notice there is no html in the body other than the root div the clientside app is hydrated into: `<div id="__next" data-reactroot=""></div>`

The SSR is not working correctly but the app does hydrate and show in the browser so the clientside render works.

If you then change to a regular import:
```javascript
import * as React from 'react';
import Link from 'next/link';
import Layout from '../components/Layout';

const IndexPage = () => (
  <Layout title="Home | Next.js + TypeScript Example">
    <h1>Hello Next.js 👋</h1>
    <p>
      <Link href="/about">
        <a>About</a>
      </Link>
    </p>
  </Layout>
);

export default IndexPage;
```

The body SSRs correctly:
```html
body>
    <div id="__next" data-reactroot="">
      <div>
        <header>
          <nav>
            <a href="/">Home</a>
            <!-- -->|<!-- -->
            <a href="/about">About</a>
            <!-- -->|<!-- -->
            <a href="/users">Users List</a>
            <!-- -->| <a href="/api/users">Users API</a>
          </nav>
        </header>
        <h1>Hello Next.js 👋</h1>
        <p><a href="/about">About</a></p>
        <footer>
          <hr />
          <span>I&#x27;m here to stay (Footer)</span>
        </footer>
      </div>
    </div>
    <script src="/_next/static/chunks/react-refresh.js?ts=1663917155976"></script>
    <script id="__NEXT_DATA__" type="application/json">
      {
        "props": { "pageProps": {} },
        "page": "/",
        "query": {},
        "buildId": "development",
        "nextExport": true,
        "autoExport": true,
        "isFallback": false,
        "scriptLoader": []
      }
    </script>
  </body>
```

I have attempted to configure SSR as per [Loadable Component's documentation](https://loadable-components.com/docs/server-side-rendering/) in a custom [`_document`](https://github.com/andrewscfc/nextjs-loadable/blob/main/pages/_document.tsx) file:

```javascript
import Document, { Html, Head, Main, NextScript } from 'next/document';
import * as React from 'react';
import { ChunkExtractor } from '@loadable/server';
import path from 'path';

export default class AppDocument extends Document {
  render() {
    const statsFile = path.resolve('.next/loadable-stats.json');

    const chunkExtractor = new ChunkExtractor({
      statsFile,
    });

    return chunkExtractor.collectChunks(
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

This is not working correctly and imagine it maybe because there is no where to call `renderToString(jsx)` as per [their docs](https://loadable-components.com/docs/server-side-rendering/); I think this call happens internally to NextJS.

Has anyone successfully configured loadable components in NextJS with SSR? I can't seem to find the right place to apply [Loadable Component's](https://loadable-components.com/docs/server-side-rendering/) SSR instructions?

**Comment by theKashey** [comment]
I would not recommend using LoadableComponents with NextJS as it has quite opionated and effective code splitting mechanics by itself working out if the box via `next/dynamic`

**Comment by andrewscfc** [comment]
> I would not recommend using LoadableComponents with NextJS as it has quite opionated and effective code splitting mechanics by itself working out if the box via `next/dynamic`

Hey thanks for your advice @theKashey . I can see it probably isn't a very good idea, it was more a temporary move as we want to utilise code using `loadable/components` in a NextJS app at the same time as using that code in a Express app. Long term we would retire the express app but that is likely to be quite a long road.

I've been thinking of maybe developing a babel plugin to translate `loadable` calls to `next/dynamic` ones; can you think of any better ideas than that?

**Comment by theKashey** [comment]
You can use simple find-and-replace to replace `loadable` with "something in the middle", and then replace that "something" with `next/dynamic`
It's more about `loadable` being "prop based", while `next` uses Suspense, so you might need an "adapter" somewhere in between.
```tsx
const component=loadable(() => import('./x'))
// ⬇️
const component=adaptToLoadable(dynamic(() => import('./x')))
// ⬇️
const component=dynamic(() => import('./x'))
```
Probably there are not that many places where you use loadable, and replacing them even manually might be easier than building a new babel plugin.

**Comment by tomtom94** [comment]
You better use a home made React SSR config like this one https://github.com/tomtom94/react-easy-ssr give me a star :) Framework, it hurts @andrewscfc isn't ?

**Comment by theKashey** [comment]
Anyway, with the further development of meta frameworks, especially NextJS and Remix, the end user lost the ability to pick code splitting solutions as it is now a part of the meta-framework core, and always has been.

There is no choice. You are playing but the rules or it's not working as expected.

But the __official recommendation is NOT to use loadable-components with NextJS__, especially 13+ versions.

If this is still something you want - please consult with NextJS about a way how to _properly_ integrate something they might not want to support.
