### ISSUE TITLE
How to load a component with children?

### ISSUE THREAD

**Issue by rostero1** [gregberge/loadable-components#924]
## 💬 Questions and Help

How do I load a component with children attached to it, like `Tabs.Panels`?

Here's the export on the component: 
`export let Tab = Object.assign(TabRoot, { Group: Tabs, List, Panels, Panel })`

Also, probably a dumb question, but if I import a component that imports huge_node_module and then another that also imports the same huge_node_module, will huge_node_module be loaded twice?

**Comment by theKashey** [comment]
For such case you should use "library" adapter - https://loadable-components.com/docs/library-splitting/
