### ISSUE TITLE
Add more comprehensive testing

### ISSUE THREAD

**Issue by fivethreeo** [gregberge/loadable-components#930]
After adding a feature pull request a need for more comprehensive testing manifested itself. Was thinking I could try setting up some tests with react-testing-library. @theKashey suggested testing with a webpack build aswell.

 Adding this issue to start a discussion about how best to do that.

**Comment by fivethreeo** [comment]
Trying to set up cypress with webpack to test components. But it does not accept array webpack configuration. So maybe use patch-package to add that or go with another solution.

**Comment by fivethreeo** [comment]
Some progress, but not sure cypress is the right way to go https://github.com/fivethreeo/loadable-components/tree/testing/cypress/examples/server-side-rendering

**Comment by fivethreeo** [comment]
Selenium is a better solution for testing https://github.com/fivethreeo/loadable-components/blob/testing/selenium/examples/server-side-rendering/__tests__/selenium-test.js

**Comment by theKashey** [comment]
You are mixing Cypress __component testing__ with Selenium e2e testing.
Try Cypress e2e or Playwring e2e. Ie the "classic" modes when the test suite is used against another running artefact.

**Comment by fivethreeo** [comment]
Ah, duh :) Cypress , playwright or selenium, any preferences?

**Comment by fivethreeo** [comment]
By the way, I could move the loadable monorepo over to pnpm if you want. A lot faster and the examples don't need to clear out node_modules when packages rebuild.

**Comment by fivethreeo** [comment]
Cypress e2e seems good. Just need a test strategy. Maybe add a window method to kick off loading and hydration.

**Comment by theKashey** [comment]
I see two strategies:
- dev mode(white box testing): hook into `console.error` and `console.warning` and expect them not to happen.
  - optional: hook into `console.log` and "console.log" sequence of events: waiting for loadable, hydration, done
- prod mode(black box testing): load HTML, get references to dom elements, hydrate, except references to exists.

In both cases feel free to export required _commands_ to `window` and call them directly from Cypress.
