### ISSUE TITLE
Server rendering with dynamic imports and CSS

### ISSUE THREAD

**Issue by mikehdt** [gregberge/loadable-components#94]
So I've got `loadable-components` working wonderfully with almost everything - Webpack 4 is happy, HMR (for dev) is happy, tests where dynamic imports need to resolve first are happy, etc.

But the part I'm a bit stuck on is server-side rendering with dynamic imports and per-module CSS files. I'm using `MiniCssExtractPlugin`, as `ExtractTextPlugin` is now deprecated. The CSS is splitting just fine. As an example, if I log the Webpack assets that are generated, I can see things like:
```
Descriptions:
   { css: 'Descriptions.efb10258987bd945.css',
     js: 'Descriptions.46113354beab1663.js' },
```

...but this is a problem, as whilst `loadable-components` does a brilliant job of splitting the _JS_ and then recombining it server-side, the split CSS (and I presume other assets such as images?) _isn't_ coming along for the ride. As a result, only the "non-dynamic" CSS is delivered with a pure SSR render (client-side JS disabled to test, as the client _will_ insert the CSS once it starts up).

I've tried as a hacky solution getting `MiniCssExtractPlugin` to combine all the CSS into one file, avoiding the issue entirely, but when I do that it breaks JS entry points and all SPA functionality is lost.

Is there a recommended or known way to deal with this issue, where non-JS assets _aren't_ brought along for SSR? I can write some super-hacky code to parse the script tag string and then match chunk names against Webpack's assets, and that'll probably work _temporarily_. But if there's a better way to handle this, it'd be great to know.

**Comment by niin4** [comment]
I have same problem and can't figure out solution. Scss-files imported at component with 'import (./style.scss)' won't get dragged along for SSR. I don't want to import every single style into main css-file...
Using Parcel instead of Webpack which works fine for client side and css-chunks get inserted to DOM.

**Comment by neoziro** [comment]
I suggest you to use CSS in JS library like Styled Components or Emotion in order to solve this problem. Loadable Components is focused on JS only and will not provide a solution for CSS.

**Comment by dmitru** [comment]
@niin4 Struggling with the same problem here. Have you figured out a solution? 😃

**Comment by niin4** [comment]
@dmitru As neoziro commented above, different approach should be used for loadable components. I ended up importing all CSS to the main style file that is imported by main application. Until the project gets refactored to use CSS in JS, the size of CSS won't hinder load times too much.

**Comment by jcklpe** [comment]
> 
> 
> I suggest you to use CSS in JS library like Styled Components or Emotion in order to solve this problem. Loadable Components is focused on JS only and will not provide a solution for CSS.

@neoziro That's a little disappointing to hear. I understand why some devs like CSS in JS but there are still many devs who prefer using a SCSS/CSS build system. While many features of SCSS can be replicated in CSS in JS with some work, it's also a pain and often produces mark up which is ugly and not aligned with the original design spec of CSS.

**Comment by theKashey** [comment]
Let's reopen this issue, and figure out what out problem actually is 
> (as long as I am a CSS lover, and CSS-in-JS hater).

Q: What do we want?
A: We want to use CSS in CSS

Q: Does `loadable` support it?
A: Yes, it does. If chunk used - it would be reported as JS and CSS, see [chunkExtractor.getLinkTags](https://www.smooth-code.com/open-source/loadable-components/docs/api-loadable-server/#chunkextractorgetlinktags), including styles included in the main entry file.

Q: _client will insert the CSS once it starts up_?
A: That's `MiniCssExtractPlugin` is working. JS is importing `style.js` and a tiny js logic is loading corresponding style.

Q: Is it possible to "help" it?
A: Just include all link tags on the Server Side, and `MiniCssExtractPlugin` will detect that you did all the job and do nothing by itself.
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L387-L394

Q: What's the problem then?
A: Style ordering. I might be not preserved.
A: What else? Honestly? I don't known - it should work out of the box.

Q: Other ideas for SSR?
A: [used-styles](https://github.com/theKashey/used-styles) to extract critical CSS, but you still have to load the "full" versions, ideally backed by SSR discovery to get better Lighthouse score, and there is nothing preventing you from doing it.

So, @jcklpe, @mikehdt - could you clarify that is not working for you?

**Comment by jcklpe** [comment]
@thekashey I have to admit I'm not directly using loadable. I'm using a project called frontity which uses it and I was told in their project forum that the inability to use scss or css in that framework was a hard limitation of ssr react and then I was linked this thread.

I'll check back in with the frontity devs and maybe they will have some thoughts.

**Comment by graysonhicks** [comment]
I am having this issue, and from @theKashey comment above, the issue is with the style ordering.  I am using Gatsby for SSR.

**Comment by theKashey** [comment]
"correct" style ordering is something we could not guarantee right now. Unfortunately, you have to write more or less order-independent rules by your own.
The only theoretically possible way to solve the problem 
- remove all imports (using babel)
- compile one-big-bundle
- get the correct order of styles(rules)
- compile split version
- detect the "right" sequence of styles
- and load styles in that order, this includes some reordering of the already loaded ones on a new chunk load.
And that's not quite in `loadable` responsibility.

**Comment by theKashey** [comment]
However - please double check the size of resulting CSS, and if it's quite small (and it could be really small) - consider reconfiguration of your MiniCssPlugin(or other) to emit one big chunk if it is not really big. That would solve many problems out of the box.

**Comment by DavideDaniel** [comment]
Isn't the style ordering js logic exactly what libraries like emotion covering? I'd agree this isn't something loadable would be doing. We are using emotion in our ssr applications and the style ordering is handled by using the css in js. When we've identified global styles that need to be included in the ssr critical css it's separately compiled and included in the code that organizes the html string:

**Comment by theKashey** [comment]
The _isolation_ provided by CSS-in-JS pattern just makes it super easy to handle style ordering, as well as Emotion just inlines all styles in the HTML.
But broadly speaking correct CSS ordering might be VERY complicated.

**Comment by DavideDaniel** [comment]
I agree. That's why the `SEPARATELY_DEPLOYED_STATIC_CSS_FOR_GLOBAL_STYLING` is meant to handle it as a separate concern.
