### ISSUE TITLE
Preparing users for new lazy component

### ISSUE THREAD

**Issue by fivethreeo** [gregberge/loadable-components#946]
In the pull request for React 18 I made the new lazy loading use loadable.reactLazy, but it would be better if that could be just lazy. 

So I wonder if we could make a legacyLazy now alongside lazy. Then add warnings when people use lazy that legacyLazy must be used soon since lazy will be changed in the next major loadable. 

Then once the feature for new lazy is ready, we add it as reactLazy with a warning it will change to lazy in the next major loadable.

**Comment by theKashey** [comment]
But what are the customer-facing changes in the lazy behaviour they will need to be aware of and address during the migration? Isn't it mostly internal stuff?

**Comment by fivethreeo** [comment]
New lazy uses Suspense and not fallback.

**Comment by theKashey** [comment]
There are many things I don't really like in Loadable, something kept from the early days.
With React Suspense you are no longer supposed to use Loading/Fallback or Error components as a part of a "loadable" - it's better to be kept outside.

It's important to keep API change minimally to ease migration, but sometimes 😁 releasing a new major version could be a better idea.
To make migration easier we can provide codemod from "old lazy" to "legacyLazy"
