### ISSUE TITLE
Add importEntrypoint to CunkExtractor and don’t load stats with require.

### ISSUE THREAD

**Issue by fivethreeo** [gregberge/loadable-components#950]
## 🚀 Feature Proposal

Add importEntrypoint to CunkExtractor and don’t load stats with require.

## Motivation

For module federation and testing using import to get the entrypoint would be preferable to using require.

## Example

```js
const App = await extractor.importEntrypiont(‘test entrypoint')
// stats should be read with fs so there are no requires if we use es modules
renderToPipeableStream(App, res)
```

**Comment by theKashey** [comment]
is it technically different?
This will blow up a little with transpilation/cjs so what about moving _responsibility_ to the end user
```tsx
const App = extractor.importEntrypiont(await import('test entrypoint'))
//                                     ^ everything under user control
```

**Comment by fivethreeo** [comment]
Yeah that seems better.

**Comment by fivethreeo** [comment]
```js
const App = await extractor.importEntrypiont(‘test entrypoint', (entry) => import(entry)))
```

Maybe?

**Comment by theKashey** [comment]
That will not be statically analyzeable. Not sure if there's a need, it's not analyzable right now, but why you might need such indirection?
Lets apply occam's razor here and cut what we don't have a good reason for.

**Comment by dglozic** [comment]
Also a typo in the example (piont).

**Comment by fivethreeo** [comment]
```js
const App = await import(extractor.getEntrypointPath(‘testentrypoint'))
```
Is better perhaps.

**Comment by fivethreeo** [comment]
requireEntrypoint seems to require all script assets up front, so should it import all too?

**Comment by fivethreeo** [comment]
In the pull i added you can now do

```js
await Promise.all(extractor.getAllScriptAssetsPaths().map(asset=>import(asset)))
const App = await import(extractor.getEntrypointPath('testentrypoint'))
```

**Comment by fivethreeo** [comment]
Fixed
