### ISSUE TITLE
Loadable component SSR remote (localhost:port)

### ISSUE THREAD

**Issue by expertup** [gregberge/loadable-components#956]
Hello, I have been trying to implement a startup for my project for 3 weeks.

I need to split my project into microservices, and add loading "remote" components as CSR and SSR.

The problem is that when compiling, "webpack" can't find the remote component. In addition, I also want to have the option that when I disable a given microservice, a replacement message will appear, e.g. "Try later".

The error I have while compiling:
`Module not found: Error: Can't resolve 'app2/Login_Register'`

```
node:
  asset main.js 12.1 KiB [emitted] (name: main)
  asset loadable-stats.json 1.1 KiB [emitted] [compared for emit]
  runtime modules 997 bytes 4 modules
  built modules 3.33 KiB [built]
    cacheable modules 3 KiB
      ./server/index.js 2.33 KiB [built] [code generated]
      ./app/index.js 691 bytes [built] [code generated]
    modules by path external "@loadable/ 84 bytes
      external "@loadable/server" 42 bytes [built] [code generated]
      external "@loadable/component" 42 bytes [built] [code generated]
    external "path" 42 bytes [built] [code generated]
    external "express" 42 bytes [built] [code generated]
    external "react" 42 bytes [built] [code generated]
    external "react-dom/server" 42 bytes [built] [code generated]
    external "express-http-proxy" 42 bytes [built] [code generated]
    external "global" 42 bytes [built] [code generated]

  ERROR in ./app/index.js 5:9-38
  Module not found: Error: Can't resolve 'app2/Login_Register' in '/project/sandbox/app'
  resolve 'app2/Login_Register' in '/project/sandbox/app'
    Parsed request is a module
    using description file: /project/sandbox/package.json (relative path: ./app)
      resolve as module
        /project/sandbox/app/node_modules doesn't exist or is not a directory
        looking for modules in /project/sandbox/node_modules
          /project/sandbox/node_modules/app2 doesn't exist
        /project/node_modules doesn't exist or is not a directory
        /node_modules doesn't exist or is not a directory
   @ ./server/index.js 7:0-33 41:73-76

  node (webpack 5.75.0) compiled with 1 error in 1443 ms
```
I think webpack should only give a handle to "module federation" when compiling, not forcefully look for a link.

I have prepared 2 examples on `codesandbox.io` at what stage I am at.

Using webpack, I compile 2 versions of the code: `node` (server) and `web` (client, browser). I have the whole application in the `app` directory. In webpack I configured the federation module for `server` and `web`. In the case of a remote server, I download the module via localhost:[port], and in the browser via a proxy.

`host` - https://codesandbox.io/p/sandbox/host-so79ey
In the host I have the main application to which I want to attach remote microservices, i.e. through localhost:[port] and through a proxy. And this is where this webpack error comes in.

`login` - https://codesandbox.io/p/sandbox/login-un2qbx
Here I have text with a button and using the federation module I make the component remotely available on `localhost:3002` (in codesandbox https://un2qbx-3002.preview.csb.app/remoteEntry.js).

And the question is: how to tie it all together so that micro services work as SSR and CSR. Where am I going wrong, what have I missed?

**Comment by theKashey** [comment]
Please refer to https://github.com/gregberge/loadable-components/issues/926
Module federation support is known not to work out of the box, but not particularly in a way you've described.
