### ISSUE TITLE
Can't get `fallback` to display component

### ISSUE THREAD

**Issue by ValentinGurkov** [gregberge/loadable-components#960]
Hi everyone,

Am I not using this as inspected? I'm trying to display a placeholder component while the one I need is loading:

```jsx
const ProductSlider = loadable(() => import('../../components/product-slider'), {
    fallback: <ProductSliderSkeleton />
})

```

But the fallback component is never displayed. I just wait a bit and my real component appears. 

I'd appreciate any tips on getting this to work. I'd like to have a placeholder component in order to eliminate layout shift.

**Comment by theKashey** [comment]
Everything seems right. Are you sure `ProductSliderSkeleton` is not displayed? Could it be just _invisible_ for any reason?

**Comment by sk-roofr** [comment]
Mine works fine..

**Comment by ValentinGurkov** [comment]
Hi @theKashey , @sk-roofr ,

I apologize for bringing you into this. It was a rookie mistake. Everything is there, things were just loading too fast, so it was hard to notice. 

Thanks for trying to help.
