### ISSUE TITLE
SassError: Undefined variable

### ISSUE THREAD

**Issue by helminst** [gregberge/loadable-components#964]
## 🐛 Bug Report

import loadable from "@loadable/component";

export const AsyncPage = loadable((props) => import(`../${props.page}`), {
  cacheKey: (props) => props. Page,
  fallback: <Loading />,
});

ERROR in ./src/assets/layout/sidebar/_sidebar-base.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/assets/layout/sidebar/_sidebar-base.scss)
Module build failed (from ./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
4 │   width: $app-sidebar-width;
  │          ^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\layout\sidebar\_sidebar-base.scss 4:10  root stylesheet

ERROR in ./src/assets/layout/sidebar/modifiers/_closed-sidebar.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/assets/layout/sidebar/modifiers/_closed-sidebar.scss)
Module build failed (from ./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
8 │     width: $app-sidebar-width-collapsed;
  │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\layout\sidebar\modifiers\_closed-sidebar.scss 8:12  root stylesheet

ERROR in ./src/assets/layout/sidebar/modifiers/_fixed-sidebar.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/assets/layout/sidebar/modifiers/_fixed-sidebar.scss)
Module build failed (from ./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js):
5 │ $widget-spacer: $spacer;

please help me...!!!

**Comment by theKashey** [comment]
`SassError: Undefined variable.` Define the variable 🤷‍♂️.

Or remove loadable and import `props.page` statically (might require switch-case) to understand that the error is not connected to loadable.
