### ISSUE TITLE
If I am using react18, do I still need loadable-components

### ISSUE THREAD

**Issue by chris-nie** [gregberge/loadable-components#994]
## loadable-components

Loadable Components is meant to make React code splitting easy.

However, react 18 has `Suspense` working on the server side now. Then what are the cases where we still need to use `loadable-components`?

**Comment by theKashey** [comment]
You want them to hold hydration before rendering. This is not a "requirement" for SSR right now, but Suspense will trigger loading state dropping any context inside in case of __any external__ update - https://github.com/facebook/react/issues/22692

For situations like this you might still need orchestration provided by loadable or similar solution.

**Comment by cchaonie** [comment]
@theKashey, what do you mean by "hold hydration before rendering"?

**Comment by theKashey** [comment]
There is no need to use loadable for client side dynamic imports. Absolutely no need since you have React.lazy working better and out of the box.
For SSR/hydration you still need _something_ and from some point of view all the functionality loadable components provide - is just a `loadableReady` _delaying_ hydration before all required chunks are loaded

```tsx
loadableReady(() => {
  const root = document.getElementById('main')
  hydrate(<App />, root) // <-- delayed
})
```

**Comment by cchaonie** [comment]
Thanks for the detailed explanation, @theKashey
So loadable components now serve as a tool to collect preloaded (and prefetched) chunks on the server side and make sure those chunks are loaded accordingly on the client side. Is this understanding correct?

**Comment by theKashey** [comment]
You can think so. This is a piece of functionality not covered by React.Lazy and the one you still need around.

**Comment by chris-nie** [comment]
@theKashey Thank you for your answer, now I know what I need to do.
