### ISSUE TITLE
Add esbuild support

### ISSUE THREAD

**Issue by Skyler-Wu** [gregberge/loadable-components#995]
## 💬 Questions and Help

Hi guys, I noticed in the few past years you don't have plan to add esbuild support, in this [issue](https://github.com/gregberge/loadable-components/issues/696), now just wanna double check that you still have no plans for esbuild support, right?

**Comment by theKashey** [comment]
No plans yet.

But the "integration" is only around getting required stats from the build, so we can connect the dots. Basically create an analog of [webpack-plugin](https://github.com/gregberge/loadable-components/tree/main/packages/webpack-plugin) for esbuild/vite/you-name-it and keep the rest.

**Comment by Skyler-Wu** [comment]
Thanks first, and if I wanna use `esbuild-loader + webpack + loadable`, without `@loadable/babel-plugin`, you have some suggestions?

**Comment by theKashey** [comment]
Sorry, it would not work. Babel is the most crucial part of instrumentation and should still happen.
As a solution you can create a custom loader that will quickly scan source file and pick the right loader to use:
- if there is "@loadable/component" seen in the file, use babel-loader
- use esbuild-loader in any other case

Just a few files of the whole project require extra functionality from babel-plugin, while all others do not. By mixing loaders you can combine speed of esbuild with power of babel.

There is a separate solution a little easier to implement - create a "conditional loader" and place it before esbuild:
- it will apply loadable transformation, but not the following transpilation
- esbuild will handle the rest
